# Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
"""Agent-surface provisioning content rules (M6 task 6.3, ADR-0011): one
source of truth, materialized into every engine's router file, idempotently.

Pure content generation, the marker-delimited merge that preserves any
hand-written guidance outside vibey's block, and the digest comparison that
makes re-provisioning a no-op when nothing changed. The actual filesystem/
git I/O -- writing files, registering `.git/info/exclude` -- lives in
infrastructure/provision/, never here.
"""

import hashlib
from dataclasses import dataclass
from enum import StrEnum

BEGIN_MARKER = "<!-- vibey:begin -->"
END_MARKER = "<!-- vibey:end -->"


class RouterFile(StrEnum):
    """Agent guidance surfaces, including qwenloop's local-agent router."""

    CLAUDE = "CLAUDE.md"
    AGENTS = "AGENTS.md"
    CURSOR = "CURSOR.md"
    GEMINI = "GEMINI.md"
    QWEN = "QWEN.md"


@dataclass(frozen=True, slots=True)
class ProvisionSpec:
    non_negotiables: tuple[str, ...]
    plugins: tuple[str, ...]


def render_block(spec: ProvisionSpec) -> str:
    non_negotiables = "\n".join(f"- {item}" for item in spec.non_negotiables) or "- None"
    plugins = ", ".join(spec.plugins) if spec.plugins else "none"
    return (
        f"{BEGIN_MARKER}\n"
        "This section is generated by vibey. Do not edit inside these markers --\n"
        "changes here are overwritten on the next provisioning run.\n\n"
        "## Non-negotiables\n\n"
        f"{non_negotiables}\n\n"
        "## Skill plugins\n\n"
        f"{plugins}\n\n"
        "## Full context\n\n"
        "See .vibey/context/ for the accepted spec, acceptance criteria, "
        "NFRs, decisions, and open items.\n"
        f"{END_MARKER}\n"
    )


def merge_router(existing: str | None, block: str) -> str:
    """Preserves any hand-written content outside vibey's markers; replaces
    only vibey's own block, or appends it to unmarked existing content."""
    if not existing:
        return block
    begin = existing.find(BEGIN_MARKER)
    end = existing.find(END_MARKER)
    if begin == -1 or end == -1 or end < begin:
        separator = "" if existing.endswith("\n") else "\n"
        return f"{existing}{separator}\n{block}"
    tail = existing[end + len(END_MARKER) :]
    # render_block()'s own block already ends with a newline after
    # END_MARKER; don't duplicate it when existing's tail is just that same
    # newline, or merge_router(rendered, rendered) would never round-trip
    # to an identical string, and re-provisioning would never be a no-op.
    if block.endswith("\n") and tail.startswith("\n"):
        tail = tail[1:]
    return existing[:begin] + block + tail


def content_digest(content: str) -> str:
    return hashlib.sha256(content.encode()).hexdigest()


def needs_write(existing: str | None, rendered: str) -> bool:
    """The idempotence check: true only when writing would actually change
    the file, so a job that finds correct digests already present writes
    nothing (ADR-0011)."""
    if existing is None:
        return True
    return content_digest(existing) != content_digest(rendered)
