# Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
"""The live view seam. Textual itself stays in infrastructure."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class StreamUi(Protocol):
    """Optional full-screen stream UI — fed deltas; Textual lives in infrastructure."""

    def on_delta(self, text: str, *, turn_id: str, seq: int) -> None: ...
    def on_turn_boundary(self, *, turn_id: str, attempt: int) -> None: ...
    def on_prompt(self, text: str) -> None: ...
    def on_assistant(self, text: str) -> None: ...
    def on_tool(self, name: str, summary: str) -> None: ...
    def on_status(self, state: dict[str, Any]) -> None: ...
    def close(self) -> None: ...
