# Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
# Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger)).
"""Contracts for host package execution."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from vibey.domain.local_stack import HostOs, PackageSpec
from vibey.infrastructure.host_packages import CommandResult, StepOutcome


@runtime_checkable
class CommandExecutorInterface(Protocol):
    def run(self, argv: tuple[str, ...], *, timeout: float = 600.0) -> CommandResult: ...
    def which(self, name: str) -> str | None: ...


@runtime_checkable
class HostPackageRunnerInterface(Protocol):
    def host(self) -> HostOs | None: ...
    def host_label(self) -> str: ...
    @property
    def user(self) -> str: ...
    def precondition(self) -> str | None: ...
    def privileged(self, argv: tuple[str, ...]) -> tuple[str, ...] | None: ...
    def is_installed(self, spec: PackageSpec) -> bool: ...
    def ensure(self, spec: PackageSpec) -> StepOutcome: ...
