# Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
"""One emitter per platform. Each turns the token set into the exact bytes a surface reads.

Theme modes are the same everywhere: Light, Dark and System, System the default. The CSS
follows `prefers-color-scheme` unless `data-theme` on the root says otherwise; the TypeScript
module exports the mode type and a resolver; GTK maps the mode onto AdwStyleManager's
colour scheme; the C header carries the mapping as an enum.
"""

from __future__ import annotations

import json
import re
import urllib.parse
from pathlib import Path
from typing import Any

from interfaces.design_interface import EmitterInterface, Token, TokenSetInterface

from design.tokens import THEMES, Colour

SOURCE = "design/tokens/*.tokens.json"


class Header:
    """The "generated, do not edit" banner, in each language's comment syntax."""

    TEXT = (
        "GENERATED by scripts/design/generate.py from {source}. Do not edit: change the tokens "
        "and run `python3 scripts/design/generate.py`. tests/meta/test_design_tokens_generated.py "
        "fails on drift."
    )

    @classmethod
    def block(cls, source: str = SOURCE) -> str:
        return f"/* {cls.TEXT.format(source=source)} */\n"

    @classmethod
    def line(cls, prefix: str, source: str = SOURCE) -> str:
        return f"{prefix} {cls.TEXT.format(source=source)}\n"


class CssValue:
    """A token value as CSS text."""

    @staticmethod
    def of(token: Token) -> str:
        v = token.value
        if token.type == "color":
            return CssValue.colour(Colour.hex_of(v))
        if token.type == "dimension":
            return f"{_n(v['value'])}{v['unit']}" if v["value"] else "0"
        if token.type == "duration":
            return f"{_n(v['value'])}{v['unit']}"
        if token.type == "cubicBezier":
            return f"cubic-bezier({', '.join(_n(x) for x in v)})"
        if token.type == "fontFamily":
            names = v if isinstance(v, list) else [v]
            generic = {
                "serif",
                "sans-serif",
                "monospace",
                "ui-sans-serif",
                "ui-monospace",
                "-apple-system",
                "BlinkMacSystemFont",
            }
            return ", ".join(n if n in generic else f'"{n}"' for n in names)
        if token.type in ("fontWeight", "number"):
            return _n(v)
        if token.type == "shadow":
            layers = v if isinstance(v, list) else [v]
            if not layers:
                return "none"
            return ", ".join(
                f"{CssValue.of(Token('', 'dimension', s['offsetX']))} {CssValue.of(Token('', 'dimension', s['offsetY']))} "
                f"{CssValue.of(Token('', 'dimension', s['blur']))} {CssValue.of(Token('', 'dimension', s['spread']))} "
                f"{CssValue.colour(Colour.hex_of(s['color']))}"
                for s in layers
            )
        if token.type == "typography":
            family = CssValue.of(Token("", "fontFamily", v["fontFamily"]))
            size = CssValue.of(Token("", "dimension", v["fontSize"]))
            return f"{_n(v['fontWeight'])} {size}/{_n(v['lineHeight'])} {family}"
        if token.type == "transition":
            return (
                f"{CssValue.of(Token('', 'duration', v['duration']))} "
                f"{CssValue.of(Token('', 'cubicBezier', v['timingFunction']))} "
                f"{CssValue.of(Token('', 'duration', v['delay']))}"
            )
        raise ValueError(f"{token.path}: no CSS form for {token.type}")

    @staticmethod
    def colour(hex_value: str) -> str:
        if len(hex_value) == 7:
            return hex_value
        r, g, b = Colour.rgb(hex_value)
        return f"rgba({r}, {g}, {b}, {_n(round(int(hex_value[7:9], 16) / 255, 3))})"


def _n(value: float | int) -> str:
    """A number without a trailing `.0`. A module function: pure formatting."""
    return str(int(value)) if float(value).is_integer() else f"{value:g}"


def _css_name(path: str) -> str:
    """`theme.dark.bg.canvas` -> `--v-bg-canvas`; `color.violet.400` -> `--v-color-violet-400`."""
    parts = path.split(".")
    if parts[0] == "theme":
        parts = parts[2:]
    return "--v-" + "-".join(parts)


class CssTokens(EmitterInterface):
    """The token layer every web surface loads: custom properties, three theme modes."""

    PATH = Path("design/dist/css/tokens.css")

    def __init__(self, tokens: TokenSetInterface) -> None:
        self._t = tokens

    def layer(self) -> str:
        """The token layer as CSS text, without the file banner."""
        shared = [
            t
            for t in self._t.tokens()
            if not t.path.startswith(("theme.", "sound.", "print."))
            and not t.path.startswith("motion.reduced.")
        ]
        out = [":root {", "  color-scheme: light dark;"]
        out += [f"  {_css_name(t.path)}: {CssValue.of(t)};" for t in shared]
        out += self._theme("light")
        out.append("}")
        dark = ["  color-scheme: dark;", *self._theme("dark")]
        out += ["", "/* System: follow the operating system unless the page has chosen. */"]
        out += ["@media (prefers-color-scheme: dark) {", '  :root:not([data-theme="light"]) {']
        out += ["  " + line for line in dark]
        out += [
            "  }",
            "}",
            "",
            '/* An explicit choice: data-theme="light" | "dark" on the root element. */',
        ]
        out += [
            ':root[data-theme="dark"] {',
            *dark,
            "}",
            ':root[data-theme="light"] {',
            "  color-scheme: light;",
            "}",
        ]
        reduced = [
            f"    {_css_name(t.path.replace('motion.reduced.', 'motion.'))}: {CssValue.of(t)};"
            for t in self._t.group("motion.reduced")
        ]
        out += [
            "",
            "/* Less motion when the platform asks for it. */",
            "@media (prefers-reduced-motion: reduce) {",
            "  :root {",
            *reduced,
            "  }",
            "}",
        ]
        return "\n".join(out) + "\n"

    def _theme(self, theme: str) -> list[str]:
        lines = []
        for t in self._t.group(f"theme.{theme}"):
            lines.append(f"  {_css_name(t.path)}: {CssValue.of(t)};")
            if t.path.endswith(".text.primary"):
                r, g, b = Colour.rgb(Colour.hex_of(t.value))
                lines.append(f"  {_css_name(t.path)}-rgb: {r}, {g}, {b};")
        return lines

    def outputs(self) -> dict[Path, bytes]:
        return {self.PATH: (Header.block() + self.layer()).encode()}


class SharedStylesheet(EmitterInterface):
    """The docs sites' one stylesheet: the token layer, then `design/web/vibey.css` resolved.

    The template may write `{{hex:<token path>}}` where a literal colour is required (the
    always-dark code block, whose contrast tests read hex) and `{{mark-data-uri}}` for the
    brand mark. Every copy a site or package reads is written from this one source.
    """

    PLACEHOLDER = re.compile(r"\{\{(hex:[a-z0-9.\-]+|mark-data-uri)\}\}")

    def __init__(self, tokens: TokenSetInterface, config: dict[str, Any], mark_svg: str) -> None:
        self._t = tokens
        self._config = config
        self._mark = mark_svg

    def text(self, repo: Path) -> str:
        template = (repo / self._config["source"]).read_text(encoding="utf-8")

        def fill(match: re.Match[str]) -> str:
            key = match.group(1)
            if key == "mark-data-uri":
                return f'url("data:image/svg+xml,{urllib.parse.quote(self._mark, safe=":/=,;")}")'
            return self._t.hex(key.removeprefix("hex:"))

        body = self.PLACEHOLDER.sub(fill, template)
        if "{{" in body:
            raise ValueError(f"{self._config['source']}: an unresolved placeholder remains")
        return (
            Header.block(f"design/tokens and {self._config['source']}")
            + CssTokens(self._t).layer()
            + "\n"
            + body
        )

    def outputs(self) -> dict[Path, bytes]:
        raise NotImplementedError("SharedStylesheet needs the repository root; use outputs_for")

    def outputs_for(self, repo: Path) -> dict[Path, bytes]:
        data = self.text(repo).encode()
        return {Path(target): data for target in self._config["targets"]}


class CopiedAsset(EmitterInterface):
    """One authored file written verbatim (behind a banner) to every place a site reads it."""

    def __init__(self, config: dict[str, Any], comment: str) -> None:
        self._config = config
        self._comment = comment

    def outputs_for(self, repo: Path) -> dict[Path, bytes]:
        body = (repo / self._config["source"]).read_text(encoding="utf-8")
        data = (Header.line(self._comment, self._config["source"]) + body).encode()
        return {Path(target): data for target in self._config["targets"]}

    def outputs(self) -> dict[Path, bytes]:
        raise NotImplementedError("CopiedAsset needs the repository root; use outputs_for")


class TypeScriptTokens(EmitterInterface):
    """`design/dist/ts/tokens.ts`: typed, framework-free, for @vibey/core, React Native and webviews."""

    PATH = Path("design/dist/ts/tokens.ts")

    def __init__(self, tokens: TokenSetInterface) -> None:
        self._t = tokens

    def _tree(self, prefix: str, convert: Any) -> dict[str, Any]:
        tree: dict[str, Any] = {}
        for t in self._t.group(prefix):
            node = tree
            parts = t.path[len(prefix) + 1 :].split(".")
            for part in parts[:-1]:
                node = node.setdefault(part, {})
            node[parts[-1]] = convert(t)
        return tree

    def outputs(self) -> dict[Path, bytes]:
        def colour(t: Token) -> str:
            return Colour.hex_of(t.value)

        def plain(t: Token) -> Any:
            v = t.value
            if t.type in ("dimension", "duration"):
                return v["value"]
            if t.type == "color":
                return Colour.hex_of(v)
            if t.type == "shadow":
                return [
                    {
                        k: (Colour.hex_of(s[k]) if k == "color" else s[k]["value"])
                        for k in ("color", "offsetX", "offsetY", "blur", "spread")
                    }
                    for s in v
                ]
            if t.type == "typography":
                return {k: (x["value"] if isinstance(x, dict) else x) for k, x in v.items()}
            if t.type == "transition":
                return {
                    "duration": v["duration"]["value"],
                    "delay": v["delay"]["value"],
                    "easing": v["timingFunction"],
                }
            return v

        themes = {theme: self._tree(f"theme.{theme}", colour) for theme in THEMES}
        data = {
            "palette": self._tree("color", colour),
            "print": self._tree("print", colour),
            "font": self._tree("font", plain),
            "typography": self._tree("typography", plain),
            "space": self._tree("space", plain),
            "radius": self._tree("radius", plain),
            "borderWidth": self._tree("border-width", plain),
            "elevation": self._tree("elevation", plain),
            "motion": self._tree("motion", plain),
            "sound": {
                t.path.removeprefix("sound."): {
                    "maxMs": t.value["value"],
                    "description": t.description,
                }
                for t in self._t.group("sound")
            },
        }
        body = [
            Header.line("//"),
            "/** Colour, type, space, radius, elevation, motion and sound for every vibey client. Units: px and ms. */",
            "",
            "/** The three theme modes every GUI offers. `system` is the default and follows the OS live. */",
            'export type ThemeMode = "light" | "dark" | "system";',
            'export type ResolvedTheme = "light" | "dark";',
            'export const THEME_MODES: readonly ThemeMode[] = ["light", "dark", "system"] as const;',
            'export const DEFAULT_THEME_MODE: ThemeMode = "system";',
            "",
            "/** Resolve a mode against the OS preference (e.g. `matchMedia` or `Appearance.getColorScheme()`). */",
            "export function resolveTheme(mode: ThemeMode, systemPrefersDark: boolean): ResolvedTheme {",
            '  return mode === "system" ? (systemPrefersDark ? "dark" : "light") : mode;',
            "}",
            "",
            f"export const themes = {json.dumps(themes, indent=2)} as const;",
            "",
            "export type ThemeColours = (typeof themes)[ResolvedTheme];",
            "",
            f"export const tokens = {json.dumps(data, indent=2, ensure_ascii=False)} as const;",
            "",
            "/** The colours for a mode, resolved. */",
            "export function coloursFor(mode: ThemeMode, systemPrefersDark: boolean): ThemeColours {",
            "  return themes[resolveTheme(mode, systemPrefersDark)];",
            "}",
            "",
            "/** Motion for the platform's reduced-motion setting. */",
            "export function motionFor(reduced: boolean) {",
            "  return reduced ? tokens.motion.reduced : tokens.motion;",
            "}",
            "",
        ]
        return {self.PATH: "\n".join(body).encode()}


class GtkCss(EmitterInterface):
    """GTK 4 / libadwaita: named colours for light (`vibey.css`) and dark (`vibey-dark.css`).

    libadwaita loads `style.css` and `style-dark.css` from the app's resources and switches
    between them itself; the app maps vibey's ThemeMode onto AdwStyleManager:
    light -> ADW_COLOR_SCHEME_FORCE_LIGHT, dark -> ADW_COLOR_SCHEME_FORCE_DARK,
    system -> ADW_COLOR_SCHEME_DEFAULT (follows the desktop, live).
    """

    DIR = Path("design/dist/gtk")

    def __init__(self, tokens: TokenSetInterface) -> None:
        self._t = tokens

    def _sheet(self, theme: str) -> str:
        t = self._t.hex
        lines = [
            Header.block(),
            f"/* vibey {theme} theme. {self.__doc__.splitlines()[2].strip() if self.__doc__ else ''} */",
            "",
            "/* libadwaita's own named colours, so every stock widget wears vibey. */",
        ]
        mapping = {
            "accent_bg_color": "accent.default",
            "accent_fg_color": "text.on-accent",
            "accent_color": "text.link",
            "window_bg_color": "bg.canvas",
            "window_fg_color": "text.primary",
            "view_bg_color": "bg.surface",
            "view_fg_color": "text.primary",
            "headerbar_bg_color": "bg.surface",
            "headerbar_fg_color": "text.primary",
            "card_bg_color": "bg.raised",
            "card_fg_color": "text.primary",
            "popover_bg_color": "bg.overlay",
            "popover_fg_color": "text.primary",
            "dialog_bg_color": "bg.overlay",
            "dialog_fg_color": "text.primary",
            "sidebar_bg_color": "bg.surface",
            "sidebar_fg_color": "text.primary",
            "success_color": "status.success",
            "warning_color": "status.warning",
            "error_color": "status.danger",
            "destructive_color": "status.danger",
        }
        lines += [
            f"@define-color {name} {t(f'theme.{theme}.{path}')};" for name, path in mapping.items()
        ]
        lines += ["", "/* Every vibey semantic colour, as vibey_<group>_<name>. */"]
        for token in self._t.group(f"theme.{theme}"):
            name = "vibey_" + token.path.split(".", 2)[2].replace(".", "_").replace("-", "_")
            lines.append(f"@define-color {name} {CssValue.colour(Colour.hex_of(token.value))};")
        lines += [
            "",
            "window, .vibey { font-family: " + CssValue.of(self._t.get("font.family.ui")) + "; }",
            ".vibey-mono, .monospace { font-family: "
            + CssValue.of(self._t.get("font.family.mono"))
            + "; }",
            ".vibey-ultra { color: @vibey_status_ultra; }",
            "",
        ]
        return "\n".join(lines)

    def outputs(self) -> dict[Path, bytes]:
        return {
            self.DIR / "vibey.css": self._sheet("light").encode(),
            self.DIR / "vibey-dark.css": self._sheet("dark").encode(),
        }


class CHeader(EmitterInterface):
    """`design/dist/c/vibey_tokens.h`: C17 constants for libvibeydesktop."""

    PATH = Path("design/dist/c/vibey_tokens.h")

    def __init__(self, tokens: TokenSetInterface) -> None:
        self._t = tokens

    @staticmethod
    def _macro(path: str) -> str:
        parts = path.split(".")
        if parts[0] == "theme":
            parts = [parts[1], *parts[2:]]
        return "VIBEY_" + "_".join(parts).replace("-", "_").upper()

    def outputs(self) -> dict[Path, bytes]:
        lines = [
            Header.block(),
            "#ifndef VIBEY_TOKENS_H",
            "#define VIBEY_TOKENS_H",
            "",
            "/* Colours are 0xRRGGBBAA; *_HEX is the CSS/GTK string. Dimensions are px, durations ms. */",
            "",
            "/* The three theme modes. Map onto AdwStyleManager's AdwColorScheme:",
            " * LIGHT -> ADW_COLOR_SCHEME_FORCE_LIGHT, DARK -> ADW_COLOR_SCHEME_FORCE_DARK,",
            " * SYSTEM -> ADW_COLOR_SCHEME_DEFAULT (the default; follows the desktop live). */",
            "typedef enum {",
            "    VIBEY_THEME_MODE_SYSTEM = 0,",
            "    VIBEY_THEME_MODE_LIGHT = 1,",
            "    VIBEY_THEME_MODE_DARK = 2",
            "} VibeyThemeMode;",
            "",
            "#define VIBEY_THEME_MODE_DEFAULT VIBEY_THEME_MODE_SYSTEM",
            "",
        ]
        for token in self._t.tokens():
            if token.path.startswith(("print.", "color.")):
                continue
            name = self._macro(token.path)
            v = token.value
            if token.type == "color":
                hx = Colour.hex_of(v)
                rgba = hx[1:] + ("" if len(hx) == 9 else "ff")
                lines.append(f"#define {name} 0x{rgba.upper()}u")
                lines.append(f'#define {name}_HEX "{hx}"')
            elif token.type in ("dimension", "duration"):
                lines.append(f"#define {name} {_n(v['value'])}")
            elif token.type == "cubicBezier":
                lines.append(
                    f"#define {name} {{ {', '.join(_n(x) + ('' if '.' in _n(x) else '.0') for x in v)} }}"
                )
            elif token.type in ("fontWeight", "number"):
                lines.append(f"#define {name} {_n(v)}")
            elif token.type == "fontFamily":
                names = v if isinstance(v, list) else [v]
                lines.append(f'#define {name} "{", ".join(names)}"')
        lines += ["", "#endif /* VIBEY_TOKENS_H */", ""]
        return {self.PATH: "\n".join(lines).encode()}


class PaperPalette(EmitterInterface):
    """The paper's TikZ colours, as the module `vibey_gh/paper.py` splices into its preamble.

    The gh tenant is installed on its own (no access to `design/` at runtime), so the palette
    is generated *into* the package. Also written as a plain `.tex` for any other TeX user.
    """

    PY = Path("src/vibey_tools/gh/vibey_gh/paper_palette.py")
    TEX = Path("design/dist/tex/vibey-colours.tex")

    def __init__(self, tokens: TokenSetInterface) -> None:
        self._t = tokens

    def lines(self) -> list[str]:
        return [
            rf"\definecolor{{{t.path.removeprefix('print.')}}}{{HTML}}{{{Colour.hex_of(t.value)[1:].upper()}}}"
            for t in self._t.group("print")
        ]

    def outputs(self) -> dict[Path, bytes]:
        heart = "❤️"
        py = [
            f"# Made with {heart} by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by "
            "[Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) "
            "([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).",
            '"""The research paper\'s colour definitions, from the vibey design tokens.',
            "",
            "GENERATED by scripts/design/generate.py from design/tokens/color.print.tokens.json.",
            "Do not edit: change the tokens and regenerate. tests/meta/test_design_tokens_generated.py",
            "fails on drift.",
            '"""',
            "",
            "PAPER_COLOURS: tuple[str, ...] = (",
            *[f'    r"{line}",' for line in self.lines()],
            ")",
            "",
        ]
        tex = [Header.line("%"), *self.lines(), ""]
        return {self.PY: "\n".join(py).encode(), self.TEX: "\n".join(tex).encode()}
