# Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
"""The research paper's colour definitions, from the vibey design tokens.

GENERATED by scripts/design/generate.py from design/tokens/color.print.tokens.json.
Do not edit: change the tokens and regenerate. tests/meta/test_design_tokens_generated.py
fails on drift.
"""

PAPER_COLOURS: tuple[str, ...] = (
    r"\definecolor{vibeyink}{HTML}{17324D}",
    r"\definecolor{vibeyblue}{HTML}{2F6B9A}",
    r"\definecolor{vibeysky}{HTML}{4FA3D1}",
    r"\definecolor{vibeyteal}{HTML}{168A8A}",
    r"\definecolor{vibeymint}{HTML}{2EA97F}",
    r"\definecolor{vibeygreen}{HTML}{3A8F5B}",
    r"\definecolor{vibeygold}{HTML}{C68A19}",
    r"\definecolor{vibeyamber}{HTML}{E0A83A}",
    r"\definecolor{vibeyred}{HTML}{B24C4C}",
    r"\definecolor{vibeyrose}{HTML}{D98A8A}",
    r"\definecolor{vibeyviolet}{HTML}{6B5BD2}",
    r"\definecolor{vibeylilac}{HTML}{A89BE8}",
    r"\definecolor{vibeygray}{HTML}{64748B}",
    r"\definecolor{vibeysilver}{HTML}{A7B2C2}",
    r"\definecolor{vibeyline}{HTML}{D6E0EA}",
    r"\definecolor{vibeywash}{HTML}{EEF5FA}",
    r"\definecolor{vibeymist}{HTML}{F6F9FC}",
)
