// GENERATED by scripts/typescript_artifacts.py from clients/app/tooling/babel.config.ts. Do not edit: change the TypeScript and run `python3 scripts/typescript_artifacts.py`. tests/meta/test_typescript_artifacts.py fails on drift.
"use strict";
const config = (api) => {
    api.cache(true);
    return { presets: ['babel-preset-expo'] };
};
module.exports = config;
