// GENERATED by scripts/typescript_artifacts.py from clients/app/tooling/metro.config.ts. Do not edit: change the TypeScript and run `python3 scripts/typescript_artifacts.py`. tests/meta/test_typescript_artifacts.py fails on drift.
"use strict";
// Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
// The krypton app's Metro configuration. Expo's Metro reads `metro.config.js`; TypeScript is the
// only authored form (sub-doctrine 9.f), so scripts/typescript_artifacts.py compiles this file
// to it. It is compiled to clients/app/, so `__dirname` below is the app directory.
const path = require("node:path");
const { getDefaultConfig } = require('expo/metro-config');
const root = path.resolve(__dirname, '../..');
const config = getDefaultConfig(__dirname);
config.watchFolders = [path.join(root, 'packages/vibey-core/src'), path.join(root, 'design/dist/ts')];
config.resolver.extraNodeModules = { '@vibey/core': path.join(root, 'packages/vibey-core/src') };
config.resolver.nodeModulesPaths = [path.join(__dirname, 'node_modules')];
module.exports = config;
