# Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
"""The autonomy scorecard's record, the blocks generated from it, and the weekly workflow.

`scripts/autonomy_scorecard.py check` is the check that says out loud when a block and the
record it is generated from have drifted apart, when a line of the append-only record has
been edited, or when the latest verdicts no longer follow from its figures (sub-doctrine
12.e). CI runs it here. The rest holds the surfaces that make the page findable, and the
workflow's contract: weekly, by hand, the queue read on the self-hosted runner without a
write token, and landed only as a pull request.

Module-level test functions rather than a class with an interface beside it (ADR-0016):
pytest collects `test_*` functions, and the rule is about production code.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
PAGE = "reference/autonomy.md"
WORKFLOW = REPO / ".github" / "workflows" / "autonomy-scorecard.yml"
MARK = "<!-- BEGIN GENERATED autonomy:{} — regenerated by scripts/autonomy_scorecard.py -->"


def test_the_record_and_every_generated_block_agree() -> None:
    result = subprocess.run(
        [sys.executable, "scripts/autonomy_scorecard.py", "check"],
        cwd=REPO,
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, f"{result.stderr}\n{result.stdout}"


def test_the_page_is_in_the_reference_nav_and_linked_from_the_readme_and_landing_page() -> None:
    nav = (REPO / "properdocs.yml").read_text(encoding="utf-8")
    reference = nav.split("  - Reference:", 1)[1].split("\n  - ", 1)[0]
    assert f": {PAGE}" in reference
    assert (REPO / "docs" / PAGE).is_file()
    for document, link in (("README.md", f"docs/{PAGE}"), ("docs/index.md", PAGE)):
        text = (REPO / document).read_text(encoding="utf-8")
        status = text.split("## Status", 1)[1].split("\n## ", 1)[0]
        assert MARK.format("summary") in status, f"{document}'s Status section lacks the summary"
        assert f"]({link})" in status
        documentation = text.split("## Documentation", 1)[1].split("\n## ", 1)[0]
        assert f"]({link})" in documentation, f"{document}'s documentation table lacks {link}"


def test_the_paper_carries_one_scorecard_table_in_its_autonomy_section() -> None:
    paper = (REPO / "docs" / "paper.md").read_text(encoding="utf-8")
    begin = MARK.format("paper")
    assert paper.count(begin) == 1
    assert paper.count("<!-- END GENERATED autonomy:paper -->") == 1
    section = paper.split("### The autonomy scan of 2026-09-30", 1)[1].split("\n### ", 1)[0]
    assert begin in section, "the scorecard sits beside the scan's prose, not in a new section"
    block = paper.split(begin, 1)[1].split("<!-- END GENERATED", 1)[0]
    assert block.count(r"\label{tab:autonomy-scorecard}") == 1
    assert r"\begin{table*}" in block and r"\begin{figure" not in block
    labels = re.findall(r"\\label\{(tab:[^}]+)\}", paper)
    assert len(labels) == len(set(labels)), "a table label is used twice"


def test_the_workflow_measures_weekly_and_lands_as_a_pull_request() -> None:
    spec = yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))
    on = spec.get("on", spec.get(True))
    assert set(on) == {"schedule", "workflow_dispatch"}
    assert on["schedule"][0]["cron"].split()[4] != "*", "the schedule is weekly"
    assert spec["permissions"] == {"contents": "read"}
    forge, queue, publish = (spec["jobs"][j] for j in ("forge", "queue", "publish"))
    assert "write" not in forge["permissions"].values()
    assert queue["runs-on"] == ["self-hosted", "vibey-local-vibey"]
    assert queue["permissions"] == {"contents": "read"}, "no write token on the self-hosted runner"
    assert publish["needs"] == ["forge", "queue"] and publish["if"] == "${{ !cancelled() }}"
    script = "\n".join(step.get("run", "") for step in publish["steps"])
    assert "autonomy_scorecard.py record" in script and "autonomy_scorecard.py check" in script
    assert 'git commit -m "chore(autonomy): refresh the autonomy scorecard"' in script
    assert "git push --force-with-lease" in script and "origin develop" not in script
    assert "Made-With: " in script
