# Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
"""The minimum-requirements record, the tables generated from it, and the weekly workflow.

`scripts/minimum_specs.py check` is the check that says out loud when a table and the record
it is generated from have drifted apart, or when a derived requirement no longer follows
from its inputs (sub-doctrine 12.e). CI runs it here. The rest holds the surfaces that make
the page findable, and the workflow's contract: weekly, by hand, measured on the
self-hosted runner without a write token, and landed only as a pull request.

Module-level test functions rather than a class with an interface beside it (ADR-0016):
pytest collects `test_*` functions, and the rule is about production code.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
PAGE = "reference/system-requirements.md"
WORKFLOW = REPO / ".github" / "workflows" / "minimum-specs.yml"


def test_the_generated_tables_and_derivations_match_the_committed_record() -> None:
    result = subprocess.run(
        [sys.executable, "scripts/minimum_specs.py", "check"],
        cwd=REPO,
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, f"{result.stderr}\n{result.stdout}"


def test_the_page_is_in_the_reference_nav_and_linked_from_the_install_sections() -> None:
    nav = (REPO / "properdocs.yml").read_text(encoding="utf-8")
    reference = nav.split("  - Reference:", 1)[1].split("\n  - ", 1)[0]
    assert f"System requirements: {PAGE}" in reference
    assert (REPO / "docs" / PAGE).is_file()
    for document, link in (("README.md", f"docs/{PAGE}"), ("docs/index.md", PAGE)):
        text = (REPO / document).read_text(encoding="utf-8")
        install = text.split("## Install", 1)[1].split("\n## ", 1)[0]
        assert f"]({link})" in install, f"{document}'s install section does not link {link}"


def test_the_paper_carries_one_generated_requirements_table() -> None:
    paper = (REPO / "docs" / "paper.md").read_text(encoding="utf-8")
    begin = "<!-- BEGIN GENERATED specs:minimum-requirements — regenerated by scripts/minimum_specs.py -->"
    assert paper.count(begin) == 1
    assert paper.count("<!-- END GENERATED specs:minimum-requirements -->") == 1
    block = paper.split(begin, 1)[1].split("<!-- END GENERATED", 1)[0]
    assert block.count(r"\label{tab:minimum-requirements}") == 1
    assert r"\begin{table*}" in block and r"\begin{figure" not in block
    labels = re.findall(r"\\label\{(tab:[^}]+)\}", paper)
    assert len(labels) == len(set(labels)), "a table label is used twice"


def test_the_workflow_measures_weekly_on_the_sovereign_runner_and_lands_as_a_pull_request() -> None:
    text = WORKFLOW.read_text(encoding="utf-8")
    spec = yaml.safe_load(text)
    on = spec.get("on", spec.get(True))
    assert set(on) == {"schedule", "workflow_dispatch"}
    assert on["schedule"][0]["cron"].split()[4] != "*", "the schedule is weekly"
    assert spec["permissions"] == {"contents": "read"}
    measure, publish = spec["jobs"]["measure"], spec["jobs"]["publish"]
    assert measure["runs-on"] == ["self-hosted", "vibey-local-vibey"]
    assert measure["permissions"] == {"contents": "read"}, (
        "no write token on the self-hosted runner"
    )
    assert publish["runs-on"] == "ubuntu-latest" and publish["needs"] == ["measure", "linux"]
    assert publish["if"] == "${{ !cancelled() }}", "lands what did report; the rest goes stale"
    script = "\n".join(step.get("run", "") for step in publish["steps"])
    assert "minimum_specs.py merge --complete" in script
    assert 'git commit -m "chore(specs): remeasure minimum requirements"' in script
    assert "chore/minimum-specs-$(date -u +%Y-%m-%d)" in script
    assert "Made-With: " in script
    assert "gh pr create" in script and "--base develop" in script
    assert "origin develop" not in script and "HEAD:develop" not in script, (
        "never pushes to develop"
    )
    assert not re.search(
        r"\[(skip ci|ci skip|no ci|skip actions|actions skip)\]", text, re.IGNORECASE
    )
    assert "skip-checks" not in text


def test_the_linux_matrix_comes_from_the_configuration_and_runs_natively_per_architecture() -> None:
    spec = yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))
    plan, linux = spec["jobs"]["plan"], spec["jobs"]["linux"]
    assert "minimum_specs.py cells --json" in "\n".join(s.get("run", "") for s in plan["steps"])
    assert linux["needs"] == "plan" and linux["runs-on"] == "${{ matrix.runner }}"
    assert linux["strategy"]["matrix"] == "${{ fromJSON(needs.plan.outputs.cells) }}"
    assert linux["strategy"]["fail-fast"] is False, "one cell's failure never hides another's"
    assert linux["permissions"] == {"contents": "read"}
    run = "\n".join(step.get("run", "") for step in linux["steps"])
    assert "minimum_specs.py cell" in run
    # Each architecture's cells run on a runner of that architecture: no emulated timing.
    sys.path.insert(0, str(REPO))
    from scripts import minimum_specs as ms

    settings = ms.SpecsSettings.load(REPO / ms.DEFAULT_CONFIG)
    runners = {a: settings.linux["arches"][a]["runner"] for a in settings.linux["arches"]}
    assert runners == {"x86_64": "ubuntu-24.04", "aarch64": "ubuntu-24.04-arm"}
