"""Consume every datum the storm has written since the last run, and keep the paper honest.

    python3 storm-evidence.py                 # what would be consumed; change nothing
    python3 storm-evidence.py --consume       # append to the ledger and advance the watermark
    python3 storm-evidence.py --consume --paper   # ...and regenerate the paper's derived block
    python3 storm-evidence.py --consume --paper --report   # ...and write the delta report
    python3 storm-evidence.py --check         # prove the ledger's span; exit 1 on any gap

Sub-doctrine 10.g, made mechanical. A periodic job that turns an accumulating record into a
published figure has one failure mode worse than all the others: reading most of it. A gap in
the input does not announce itself — the totals still add up, the rates still look plausible,
and the figure is published with a confidence the data no longer supports.

WHY THE WATERMARK IS NOT A TIMESTAMP
------------------------------------
"Everything newer than the last run" loses, and loses silently:

  * records written in the same second as the cutoff, on either side depending on rounding;
  * records arriving out of order, which is normal when several producers append;
  * records written *while this job was running*, which an end-of-run stamp then declares
    already consumed;
  * everything, if a clock moves.

So the watermark is a position in the data itself. For an append-only file it is a byte
offset; for a set of records it is an identity set. Both are exact where a clock is
approximate, and both turn "have I seen this" into a question about the data.

ORDER OF OPERATIONS, WHICH IS THE WHOLE GUARANTEE
-------------------------------------------------
Read the watermark, read the sources from it, **append to the ledger and flush**, and only
then write the new watermark. A crash anywhere before the last step re-reads; a crash after
it does not. Consumption is therefore at-least-once, never at-most-once, and the duplicates
that follow are removed by identity -- because at-most-once loses records exactly when
something has already gone wrong, which is the worst possible moment to start losing them.

TRUNCATION IS A GAP, AND IS SAID SO
-----------------------------------
If a file is shorter than the offset recorded for it, it was rotated or rewritten and the
bytes between are gone. That is reported as a gap with the source named -- never repaired by
quietly resetting the offset to zero, which would re-read the survivors and call the span
complete. An unreadable source is treated the same way: named, and its watermark left where
it was so the next run covers the same ground.

WHAT IT WILL NOT TOUCH
----------------------
`src/vibey_tools/gh/docs/qwenloop-storm-2026-09-20.json`, the frozen extraction the paper
cites *as of* a cutoff. A file that silently becomes a different measurement under the same
name destroys the reproducibility the citation exists to provide (ADR-0048). New evidence is
a new record; the frozen one stays frozen. In the paper this writes only between its own
markers, and never a word of prose or a claim.
"""

import argparse
import hashlib
import json
import os
import re
import time
from pathlib import Path

import storm_paths

# .absolute(), never .resolve(): tools/ is a symlink into the planning worktree, where specs/
# resolve but lanes/ and integration/ exist only in the runtime root.
STORM = Path(__file__).absolute().parent.parent
LANES = STORM / "lanes"
# The tracked checkout that owns the ledger and the paper.
PLANS = Path(__file__).resolve().parent.parent
EVIDENCE = PLANS / "evidence"
LEDGER = EVIDENCE / "ledger.jsonl"
CHANGES = EVIDENCE / "CHANGES.md"
WATERMARK = EVIDENCE / "watermark.json"
PAPER = PLANS.parent.parent / "paper.md"

BEGIN = "<!-- BEGIN GENERATED storm-evidence — regenerated by tools/storm-evidence.py -->"
END = "<!-- END GENERATED storm-evidence -->"

# Append-only text files, consumed by byte offset. The priority log (ADR-0054) is declared in
# storm.toml rather than named here, so its name is asked of the one resolver; inside the
# storm root it is named relative to it, like the others, so its identities stay stable.
_PRIORITY = storm_paths.priority_log(STORM)
STREAMS = (
    "progress.log",
    "integrated.txt",
    "abandoned.txt",
    "bench/results.jsonl",
    str(_PRIORITY.relative_to(STORM)) if _PRIORITY.is_relative_to(STORM) else str(_PRIORITY),
)


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", "replace")).hexdigest()[:16]


def load_watermark() -> dict:
    if not WATERMARK.is_file():
        return {"offsets": {}, "seen": []}
    try:
        mark = json.loads(WATERMARK.read_text())
    except (OSError, ValueError):
        # Unreadable watermark means the span cannot be established. Starting from zero would
        # re-read everything and call it complete; the honest move is an empty mark plus the
        # gap that `--check` will then report.
        return {"offsets": {}, "seen": [], "unreadable": True}
    mark.setdefault("offsets", {})
    mark.setdefault("seen", [])
    return mark


def read_stream(name: str, offset: int) -> tuple[list[tuple[int, str]], int, str | None]:
    """(absolute byte position, line) for every line after `offset`, the new offset, any gap.

    Binary, and the position is absolute. An identity built from "the offset the reader
    started at" encodes when somebody happened to look, not where the datum sits -- so rolling
    a watermark back gives the same line a different identity, de-duplication stops working,
    and a replay silently doubles the record. The position of the line in the file is the
    same for every reader forever, which is what 10.g means by a position in the data.
    """
    path = STORM / name
    if not path.is_file():
        return [], offset, None if offset == 0 else f"{name}: source has disappeared"
    size = path.stat().st_size
    if size < offset:
        # Rotated or rewritten. The bytes between are gone and no amount of reading the
        # survivors brings them back, so it is named rather than papered over.
        return [], size, f"{name}: truncated ({size} bytes < watermark {offset}); data lost"
    if size == offset:
        return [], offset, None
    try:
        with path.open("rb") as handle:
            handle.seek(offset)
            raw = handle.read()
    except OSError as exc:
        return [], offset, f"{name}: unreadable ({exc.__class__.__name__}); watermark held"
    out: list[tuple[int, str]] = []
    position = offset
    for chunk in raw.splitlines(keepends=True):
        line = chunk.decode("utf-8", "replace").rstrip("\r\n")
        if line.strip():
            out.append((position, line))
        position += len(chunk)
    return out, size, None


def lane_records(seen: set[str]) -> list[dict]:
    """One record per lane result, identified by content so a re-read cannot duplicate it."""
    out = []
    for result in sorted(LANES.glob("*/.qwenstorm/result.json")) if LANES.is_dir() else []:
        lane = result.parent.parent.name
        try:
            body = result.read_text(errors="replace")
        except OSError:
            continue
        ident = f"lane:{lane}:{digest(body)}"
        if ident in seen:
            continue
        try:
            parsed = json.loads(body)
        except ValueError:
            parsed = {"unparsed": body[:200]}
        attempts = []
        log = result.parent / "lane.log"
        if log.is_file():
            attempts = [
                line for line in log.read_text(errors="replace").splitlines() if line.strip()
            ]
        out.append(
            {
                "id": ident,
                "kind": "lane_result",
                "lane": lane,
                "completed": bool(parsed.get("completed")),
                "result": parsed,
                "attempts": attempts,
            }
        )
    return out


def collect(mark: dict) -> tuple[list[dict], dict, list[str]]:
    """Everything since the watermark, the watermark it would advance to, and any gaps.

    Identity is checked against the LEDGER, not against the watermark. The ledger is the
    durable record and the watermark is only a shortcut to avoid re-reading; if the shortcut
    is lost, rolled back or corrupted, re-reading is safe precisely because the ledger still
    knows what it already holds. Trusting the watermark for de-duplication makes the volatile
    half authoritative, which turns a lost watermark into duplicated evidence -- and evidence
    counted twice is as wrong as evidence missed.
    """
    offsets = dict(mark["offsets"])
    seen = {row.get("id") for row in ledger_rows()} | set(mark.get("seen", []))
    records: list[dict] = []
    gaps: list[str] = []
    if mark.get("unreadable"):
        gaps.append("watermark.json was unreadable; the span before this run is unknown")

    for name in STREAMS:
        lines, new_offset, gap = read_stream(name, int(offsets.get(name, 0)))
        if gap:
            gaps.append(gap)
        for position, line in lines:
            ident = f"{name}@{position}:{digest(line)}"
            if ident in seen:
                continue
            records.append(
                {"id": ident, "kind": "stream", "source": name, "at": position, "line": line}
            )
        offsets[name] = new_offset

    records.extend(lane_records(seen))
    # The watermark carries offsets only. An ever-growing `seen` list would duplicate what the
    # ledger already holds and grow without bound, and the ledger is what de-duplication
    # actually consults.
    return records, {"offsets": offsets}, gaps


def append(records: list[dict], when: str) -> None:
    """Append and flush BEFORE the watermark moves. This ordering is the guarantee."""
    EVIDENCE.mkdir(parents=True, exist_ok=True)
    with LEDGER.open("a", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps({**record, "consumed_at": when}, sort_keys=True) + "\n")
        handle.flush()
        os.fsync(handle.fileno())


def advance(mark: dict, when: str, gaps: list[str]) -> None:
    mark = {**mark, "advanced_at": when, "gaps": gaps}
    EVIDENCE.mkdir(parents=True, exist_ok=True)
    temporary = WATERMARK.with_suffix(".json.new")
    temporary.write_text(json.dumps(mark, indent=2, sort_keys=True) + "\n")
    temporary.replace(WATERMARK)  # atomic: a half-written watermark would invent a gap


def ledger_rows() -> list[dict]:
    if not LEDGER.is_file():
        return []
    rows = []
    for line in LEDGER.read_text(errors="replace").splitlines():
        if line.strip():
            try:
                rows.append(json.loads(line))
            except ValueError:
                continue
    return rows


def summarise(rows: list[dict]) -> dict:
    lanes = {r["lane"]: r for r in rows if r.get("kind") == "lane_result"}
    starts = [r for r in rows if r.get("kind") == "stream" and " start " in r.get("line", "")]
    ends = [r for r in rows if r.get("kind") == "stream" and " end " in r.get("line", "")]
    integrated = {r["line"] for r in rows if r.get("source") == "integrated.txt"}
    abandoned = {r["line"] for r in rows if r.get("source") == "abandoned.txt"}
    turns = []
    for record in lanes.values():
        for line in record.get("attempts", []):
            found = re.search(r"\t(\d+)\s*$", line)
            if found:
                turns.append(int(found.group(1)))
    stamps = sorted(r["consumed_at"] for r in rows if r.get("consumed_at"))
    return {
        "records": len(rows),
        "lanes": len(lanes),
        "completed": sum(1 for r in lanes.values() if r.get("completed")),
        "starts": len(starts),
        "ends": len(ends),
        "integrated": len(integrated),
        "abandoned": len(abandoned),
        "attempts": len(turns),
        "turns": sum(turns),
        "first": stamps[0] if stamps else "—",
        "last": stamps[-1] if stamps else "—",
    }


def block(summary: dict, gaps: list[str]) -> str:
    gap_line = (
        "**Gaps in this span:** " + "; ".join(gaps)
        if gaps
        else "**Gaps in this span:** none; every byte and record between the watermarks was read."
    )
    return f"""{BEGIN}

*Derived from `docs/plans/qwenstorm-3.0.0/evidence/ledger.jsonl`, an append-only record consumed under sub-doctrine 10.g.*
*Regenerated automatically; do not edit inside these markers.*
*This block states figures only — every claim about them is written by a person outside it.*

| quantity | value |
|---|---|
| ledger records | {summary["records"]} |
| span consumed from | {summary["first"]} |
| span consumed to | {summary["last"]} |
| lanes observed | {summary["lanes"]} |
| lanes claiming completion | {summary["completed"]} |
| lane starts / ends logged | {summary["starts"]} / {summary["ends"]} |
| lanes integrated / abandoned | {summary["integrated"]} / {summary["abandoned"]} |
| recorded attempts | {summary["attempts"]} |
| total turns across attempts | {summary["turns"]} |

{gap_line}

{END}"""


def write_paper(text: str) -> str:
    if not PAPER.is_file():
        return f"no paper at {PAPER}"
    body = PAPER.read_text(errors="replace")
    if BEGIN in body and END in body:
        start, tail = body.index(BEGIN), body.index(END) + len(END)
        updated = body[:start] + text + body[tail:]
    else:
        # First time: the block is appended rather than inserted into an argument, because
        # where a figure belongs in a paper is a judgement and this is not making it.
        updated = body.rstrip() + "\n\n" + text + "\n"
    if updated == body:
        return "paper block already current"
    PAPER.write_text(updated)
    return "paper block regenerated"


def report(records: list[dict], when: str, gaps: list[str]) -> str:
    """What this run consumed, in prose a person can fold into the paper.

    The generated block carries the figures; this carries the events behind them. They are
    different jobs: a number can be regenerated safely because it is derived, while what a
    number *means* is a claim, and claims are written by people (12.e). This report exists so
    that writing one does not also mean going and gathering the data first.
    """
    if not records:
        return f"# Evidence delta\n\nNothing new since the last run ({when}).\n"
    streams = [r for r in records if r.get("kind") == "stream"]
    lanes = [r for r in records if r.get("kind") == "lane_result"]
    started = [r["line"] for r in streams if " start " in r.get("line", "")]
    ended = [r["line"] for r in streams if " end " in r.get("line", "")]
    settled = [r["line"] for r in streams if r.get("source") in ("integrated.txt", "abandoned.txt")]
    lines = [
        "# Evidence delta",
        "",
        f"Consumed at {when}: **{len(records)} new record(s)** "
        f"({len(streams)} log line(s), {len(lanes)} lane result(s)).",
        "",
    ]
    if gaps:
        lines += ["> **This span has gaps and the figures below are not evidence (10.g):**", ""]
        lines += [f"> - {g}" for g in gaps] + [""]
    if lanes:
        lines += ["## Lanes that finished in this span", ""]
        for record in lanes:
            claim = "claims completed" if record.get("completed") else "did not complete"
            attempts = record.get("attempts", [])
            lines.append(f"- `{record['lane']}` — {claim}, {len(attempts)} attempt line(s)")
            for attempt in attempts[:3]:
                lines.append(f"  - `{attempt}`")
        lines.append("")
    if settled:
        lines += ["## Settled in this span", ""] + [f"- `{s}`" for s in settled] + [""]
    prioritised = [r["line"] for r in streams if r.get("source") == STREAMS[-1]]
    if prioritised:
        lines += ["## Priority changes in this span", ""]
        lines += [f"- `{p}`" for p in prioritised] + [""]
    if started or ended:
        lines += [
            "## Activity",
            "",
            f"- lane starts logged: {len(started)}",
            f"- lane ends logged: {len(ended)}",
            "",
        ]
    lines += [
        "---",
        "",
        "*Written by `tools/storm-evidence.py` from the append-only ledger. It reports what",
        "happened; it makes no claim about what it means. Fold the meaning into the paper by",
        "hand — the generated block already carries the figures.*",
    ]
    return "\n".join(lines) + "\n"


def check() -> int:
    rows = ledger_rows()
    problems = []
    identities = [r.get("id") for r in rows]
    duplicates = {i for i in identities if identities.count(i) > 1}
    if duplicates:
        problems.append(f"{len(duplicates)} duplicated record id(s) in the ledger")
    mark = load_watermark()
    for name, offset in mark.get("offsets", {}).items():
        path = STORM / name
        if path.is_file() and path.stat().st_size < int(offset):
            problems.append(f"{name}: file is shorter than its watermark; data was lost")
    problems.extend(mark.get("gaps", []))
    if problems:
        for problem in problems:
            print(f"storm-evidence: GAP {problem}")
        return 1
    print(f"storm-evidence: span intact, {len(rows)} record(s), no gaps recorded")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--consume", action="store_true", help="append and advance")
    parser.add_argument("--paper", action="store_true", help="regenerate the paper's block")
    parser.add_argument("--report", action="store_true", help="write the delta report")
    parser.add_argument("--check", action="store_true", help="prove the span; exit 1 on a gap")
    args = parser.parse_args()
    if args.check:
        return check()

    when = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    mark = load_watermark()
    records, advanced, gaps = collect(mark)
    for gap in gaps:
        print(f"storm-evidence: GAP {gap}")
    if not args.consume:
        print(f"storm-evidence: would consume {len(records)} new record(s)")
        return 1 if gaps else 0

    if records:
        append(records, when)  # durable first...
    advance(advanced, when, gaps)  # ...then, and only then, the watermark moves
    print(f"storm-evidence: consumed {len(records)} record(s)")
    if args.paper:
        print(f"storm-evidence: {write_paper(block(summarise(ledger_rows()), gaps))}")
    if args.report:
        EVIDENCE.mkdir(parents=True, exist_ok=True)
        CHANGES.write_text(report(records, when, gaps))
        print(f"storm-evidence: wrote {CHANGES.name}")
    return 1 if gaps else 0


if __name__ == "__main__":
    raise SystemExit(main())
