# Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
"""The continuation prompts: render them, check them, and hand one to an agent (sub-doctrine 10.l).

    python scripts/continuation_prompts.py render     # rewrite every generated block
    python scripts/continuation_prompts.py check      # exit 1 on any broken guarantee
    python scripts/continuation_prompts.py matrix     # the prompts, as JSON, for the lane
    python scripts/continuation_prompts.py extract ID # one prompt's text
    python scripts/continuation_prompts.py plan ID    # the prompt plus its gathered evidence

`check` holds four guarantees on every pull request: every file, glob, `vibey-gh` command and
ADR a prompt names exists; every workflow and every agent skill is covered by a prompt or
exempted with a reason; every generated block is current; and the weekly lane that runs the
prompts exists, is scheduled, and still runs on GitHub. Everything it reads is declared in
`scripts/continuation_prompts.toml` (sub-doctrine 12.h).
"""

from __future__ import annotations

import glob
import json
import re
import subprocess
import sys
import tomllib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

try:
    from scripts.interfaces.continuation_prompts_interface import (
        CommandRunnerInterface,
        FactSourceInterface,
        PageRendererInterface,
        ReferenceProbeInterface,
    )
except ImportError:  # run as `python scripts/continuation_prompts.py`
    from interfaces.continuation_prompts_interface import (  # type: ignore[import-not-found,no-redef]
        CommandRunnerInterface,
        FactSourceInterface,
        PageRendererInterface,
        ReferenceProbeInterface,
    )

REPO = Path(__file__).resolve().parents[1]
SCRIPT = "scripts/continuation_prompts.py"
DEFAULT_CONFIG = "scripts/continuation_prompts.toml"
MODES = ("act", "drill")


@dataclass(frozen=True)
class Prompt:
    """One continuation prompt as declared."""

    id: str
    title: str
    page: str
    mode: str
    purpose: str
    covers: tuple[str, ...]
    gather: tuple[str, ...]


@dataclass(frozen=True)
class Settings:
    """Everything `scripts/continuation_prompts.toml` declares."""

    directory: str
    index: str
    prompts: tuple[Prompt, ...]
    exempt: Mapping[str, str]
    drill_only: tuple[str, ...]
    lane: Mapping[str, Any]
    run: Mapping[str, Any]

    @classmethod
    def load(cls, root: Path, relative: str = DEFAULT_CONFIG) -> Settings:
        raw = tomllib.loads((root / relative).read_text(encoding="utf-8"))
        prompts = tuple(
            Prompt(
                id=p["id"],
                title=p["title"],
                page=p["page"],
                mode=p["mode"],
                purpose=p["purpose"],
                covers=tuple(p.get("covers", ())),
                gather=tuple(p.get("gather", ())),
            )
            for p in raw["prompt"]
        )
        return cls(
            directory=raw["pages"]["directory"],
            index=raw["pages"]["index"],
            prompts=prompts,
            exempt=dict(raw.get("exempt", {})),
            drill_only=tuple(raw.get("authority", {}).get("drill_only", ())),
            lane=dict(raw.get("lane", {})),
            run=dict(raw.get("run", {})),
        )

    def prompt(self, prompt_id: str) -> Prompt:
        for prompt in self.prompts:
            if prompt.id == prompt_id:
                return prompt
        raise KeyError(f"no continuation prompt named {prompt_id!r}")


class GeneratedBlocks:
    """`<!-- BEGIN GENERATED continuation:NAME — regenerated by SCRIPT -->` blocks.

    Not `minimum_specs.GeneratedBlocks`: that class compiles in its own `specs:` prefix and
    its own script name, so it cannot mark another script's blocks (10.e: the gap is that its
    marker is not a parameter).
    """

    PATTERN = re.compile(
        r"<!-- BEGIN GENERATED continuation:(?P<name>[a-z0-9-]+) — regenerated by "
        + re.escape(SCRIPT)
        + r" -->\n(?P<body>.*?)<!-- END GENERATED continuation:(?P=name) -->",
        re.DOTALL,
    )

    @classmethod
    def wrap(cls, name: str, body: str) -> str:
        inner = f"{body.rstrip()}\n" if body.strip() else ""
        return (
            f"<!-- BEGIN GENERATED continuation:{name} — regenerated by {SCRIPT} -->\n"
            f"{inner}<!-- END GENERATED continuation:{name} -->"
        )

    @classmethod
    def replace_all(cls, document: str, blocks: Mapping[str, str]) -> str:
        return cls.PATTERN.sub(
            lambda m: cls.wrap(m["name"], blocks[m["name"]]) if m["name"] in blocks else m.group(0),
            document,
        )

    @classmethod
    def drift(cls, document: str, blocks: Mapping[str, str]) -> list[str]:
        present = {m["name"]: m["body"] for m in cls.PATTERN.finditer(document)}
        return sorted(
            name
            for name, body in blocks.items()
            if name not in present or present[name].strip() != body.strip()
        )


class RepositoryFacts(FactSourceInterface):
    """Reads the version, the decision records, the lanes and the skills from tracked files."""

    def __init__(self, root: Path) -> None:
        self._root = root

    def workflows(self) -> dict[str, dict[str, Any]]:
        lanes: dict[str, dict[str, Any]] = {}
        for path in sorted((self._root / ".github" / "workflows").glob("*.yml")):
            text = path.read_text(encoding="utf-8")
            name = re.search(r"^name:\s*(.+)$", text, re.MULTILINE)
            crons = re.findall(r"^\s*-\s*cron:\s*\"?([^\"\n]+)\"?", text, re.MULTILINE)
            lanes[path.name] = {
                "name": name[1].strip().strip('"') if name else path.stem,
                "crons": crons,
                # Only a `runs-on:` value says where a job runs; a comment naming a
                # self-hosted runner does not.
                "self_hosted": any(
                    "self-hosted" in value
                    for value in re.findall(r"^\s*runs-on:\s*(.+)$", text, re.MULTILINE)
                ),
            }
        return lanes

    def skills(self) -> list[str]:
        base = self._root / ".claude" / "skills"
        return sorted(p.parent.name for p in base.glob("*/SKILL.md"))

    def facts(self) -> Mapping[str, Any]:
        pyproject = tomllib.loads((self._root / "pyproject.toml").read_text(encoding="utf-8"))
        decisions = sorted((self._root / "docs" / "architecture" / "decisions").glob("[0-9]*.md"))
        latest = decisions[-1] if decisions else None
        title = ""
        if latest is not None:
            heading = re.search(r"^#\s+(.+)$", latest.read_text(encoding="utf-8"), re.MULTILINE)
            title = heading[1].strip() if heading else latest.stem
        return {
            "version": pyproject["project"]["version"],
            "adr_count": len(decisions),
            "latest_adr": title,
            "workflows": self.workflows(),
            "skills": self.skills(),
        }


class SubprocessRunner(CommandRunnerInterface):
    """Runs a declared command through the shell, in the repository, with a deadline."""

    def __init__(self, root: Path) -> None:
        self._root = root

    def run(self, command: str, timeout_s: float) -> tuple[int, str]:
        try:
            done = subprocess.run(  # nosec B602 -- commands come from the tracked TOML only
                command,
                shell=True,
                cwd=self._root,
                capture_output=True,
                text=True,
                timeout=timeout_s,
                check=False,
            )
        except subprocess.TimeoutExpired as error:
            out = error.stdout if isinstance(error.stdout, str) else ""
            return 124, out
        return done.returncode, done.stdout + done.stderr


class ReferenceProbe(ReferenceProbeInterface):
    """Every path, glob, ADR and `vibey-gh` command a prompt names must resolve."""

    PATH = re.compile(
        r"(?<![\w/.-])((?:\.github|\.claude|docs|scripts|src|research|clients|packages|tests)"
        r"/[A-Za-z0-9_./*-]*[A-Za-z0-9_*/]|CLAUDE\.md|AGENTS\.md|GEMINI\.md|\.vibey-gh\.toml"
        r"|pyproject\.toml)"
    )
    ADR = re.compile(r"\bADR-(\d{4})\b")
    VIBEY_GH = re.compile(r"\bvibey-gh ([a-z][a-z-]+)")

    def __init__(self, root: Path, runner: CommandRunnerInterface) -> None:
        self._root = root
        self._runner = runner
        self._commands: dict[str, bool] = {}

    def _path_missing(self, ref: str) -> bool:
        ref = ref.rstrip(".,;:")
        if any(ch in ref for ch in "*?["):
            return not glob.glob(str(self._root / ref))
        return not (self._root / ref).exists()

    def _command_exists(self, sub: str) -> bool:
        if sub not in self._commands:
            code, _ = self._runner.run(f"{sys.executable} -m vibey_gh {sub} --help", timeout_s=60)
            self._commands[sub] = code == 0
        return self._commands[sub]

    def missing(self, text: str) -> Sequence[str]:
        problems: list[str] = []
        for ref in sorted({m.rstrip(".,;:") for m in self.PATH.findall(text)}):
            if self._path_missing(ref):
                problems.append(f"names {ref}, which does not exist")
        decisions = self._root / "docs" / "architecture" / "decisions"
        for number in sorted(set(self.ADR.findall(text))):
            if not list(decisions.glob(f"{number}-*.md")):
                problems.append(f"names ADR-{number}, which does not exist")
        for sub in sorted(set(self.VIBEY_GH.findall(text))):
            if not self._command_exists(sub):
                problems.append(f"names `vibey-gh {sub}`, which is not a vibey-gh command")
        return problems


class PageRenderer(PageRendererInterface):
    """The state block on each prompt's page, and the table on the index."""

    def __init__(self, settings: Settings, facts: Mapping[str, Any]) -> None:
        self._settings = settings
        self._facts = facts

    def _lane(self, file: str) -> str:
        lane = self._facts["workflows"].get(file)
        if lane is None:
            return f"`{file}` (missing)"
        return (
            f"[{lane['name']}](https://github.com/the-vibey-project/vibey/actions/workflows/{file})"
        )

    def blocks(self, prompt_id: str | None) -> Mapping[str, str]:
        f = self._facts
        if prompt_id is None:
            rows = ["| Prompt | Mode | What it is for |", "|---|---|---|"]
            for p in self._settings.prompts:
                rows.append(f"| [{p.title}]({Path(p.page).name}) | {p.mode} | {p.purpose} |")
            head = (
                f"*Rendered from the repository at vibey-engine {f['version']}, with "
                f"{f['adr_count']} decision records and {len(f['workflows'])} workflow lanes, "
                f"all covered. Regenerated by `{SCRIPT}`; do not edit inside these markers.*\n\n"
            )
            return {"index": head + "\n".join(rows)}
        p = self._settings.prompt(prompt_id)
        lanes = [c for c in p.covers if c in f["workflows"]]
        skills = [c for c in p.covers if c not in f["workflows"]]
        lines = [
            f"*Rendered from the repository at vibey-engine {f['version']}; regenerated by "
            f"`{SCRIPT}`, do not edit inside these markers.*",
            "",
            f"- **Mode when GitHub runs it weekly:** {p.mode} — "
            + (
                "may open a draft pull request; never merges, approves, releases or deletes."
                if p.mode == "act"
                else "verifies and reports; changes nothing."
            ),
            f"- **What it is for:** {p.purpose}",
            f"- **Decision records:** {f['adr_count']}, the newest {f['latest_adr']}.",
        ]
        if lanes:
            lines.append(
                "- **Lanes it keeps usable:** " + ", ".join(self._lane(x) for x in lanes) + "."
            )
        if skills:
            lines.append(
                "- **Agent skills it relies on:** "
                + ", ".join(f"`.claude/skills/{s}/SKILL.md`" for s in skills)
                + "."
            )
        return {"state": "\n".join(lines)}


class PromptPage:
    """One page's prompt text: the single ```text fence under `## The prompt`."""

    FENCE = re.compile(r"^## The prompt\s*\n+```text\n(?P<body>.*?)\n```", re.MULTILINE | re.DOTALL)

    @classmethod
    def text(cls, page: str) -> str | None:
        found = cls.FENCE.search(page)
        return found["body"] if found else None


class ContinuationPrompts:
    """Render, check and hand over the continuation prompts."""

    def __init__(
        self,
        root: Path,
        settings: Settings,
        facts: FactSourceInterface,
        probe: ReferenceProbeInterface,
        runner: CommandRunnerInterface,
    ) -> None:
        self._root = root
        self._settings = settings
        self._facts = facts.facts()
        self._probe = probe
        self._runner = runner
        self._renderer = PageRenderer(settings, self._facts)

    def _pages(self) -> list[tuple[str, str | None]]:
        return [(self._settings.index, None)] + [(p.page, p.id) for p in self._settings.prompts]

    def render(self) -> list[str]:
        written = []
        for page, prompt_id in self._pages():
            path = self._root / page
            text = path.read_text(encoding="utf-8")
            new = GeneratedBlocks.replace_all(text, self._renderer.blocks(prompt_id))
            if new != text:
                path.write_text(new, encoding="utf-8")
                written.append(page)
        return written

    def problems(self) -> list[str]:
        s = self._settings
        out: list[str] = []
        ids = [p.id for p in s.prompts]
        if len(ids) != len(set(ids)):
            out.append("two prompts share an id")
        lanes = self._facts["workflows"]
        known = set(lanes) | set(self._facts["skills"])
        covered: set[str] = set()
        for p in s.prompts:
            covered |= set(p.covers)
            if p.mode not in MODES:
                out.append(f"{p.id}: mode {p.mode!r} is not one of {MODES}")
            if p.id in s.drill_only and p.mode != "drill":
                out.append(f"{p.id}: declared drill-only, but its mode is {p.mode!r}")
            for c in p.covers:
                if c not in known:
                    out.append(f"{p.id}: covers {c!r}, which is neither a workflow nor a skill")
            path = self._root / p.page
            if not path.is_file():
                out.append(f"{p.id}: its page {p.page} does not exist")
                continue
            page = path.read_text(encoding="utf-8")
            body = PromptPage.text(page)
            if body is None:
                out.append(f"{p.id}: {p.page} has no ```text block under '## The prompt'")
                continue
            out += [f"{p.id}: {m}" for m in self._probe.missing(page)]
            for name in GeneratedBlocks.drift(page, self._renderer.blocks(p.id)):
                out.append(f"{p.id}: generated block {name!r} is stale; run `{SCRIPT} render`")
        index = (self._root / s.index).read_text(encoding="utf-8")
        for name in GeneratedBlocks.drift(index, self._renderer.blocks(None)):
            out.append(f"{s.index}: generated block {name!r} is stale; run `{SCRIPT} render`")
        out += [f"{s.index}: {m}" for m in self._probe.missing(index)]
        for item in sorted(known - covered - set(s.exempt)):
            out.append(f"{item} is covered by no continuation prompt and has no exemption")
        for item, reason in s.exempt.items():
            if not str(reason).strip():
                out.append(f"exemption for {item} gives no reason")
        out += self._lane_problems(lanes)
        return out

    def _lane_problems(self, lanes: Mapping[str, Mapping[str, Any]]) -> list[str]:
        file = Path(str(self._settings.lane.get("workflow", ""))).name
        lane = lanes.get(file)
        if lane is None:
            return [f"the lane that runs the prompts ({file or 'undeclared'}) does not exist"]
        problems = []
        if not lane["crons"]:
            problems.append(f"{file} has no schedule: the prompts would never run on their own")
        text = (self._root / ".github" / "workflows" / file).read_text(encoding="utf-8")
        runs_on = str(self._settings.run.get("runs_on", ""))
        if lane["self_hosted"] or "self-hosted" in runs_on:
            problems.append(f"{file} must run on GitHub-hosted runners, not a self-hosted one")
        if "workflow_dispatch" not in text:
            problems.append(f"{file} cannot be run by hand (no workflow_dispatch)")
        return problems

    def matrix(self) -> list[dict[str, Any]]:
        """One entry per prompt, carrying the declared run settings, so the lane reads them
        from the TOML rather than compiling them into the workflow (12.h)."""
        run = self._settings.run
        return [
            {
                "id": p.id,
                "mode": p.mode,
                "title": p.title,
                "runs_on": run.get("runs_on", "ubuntu-24.04-arm"),
                "model": run.get("model", "gpt-oss:20b"),
                "max_turns": int(run.get("max_turns", 12)),
                "timeout_minutes": int(run.get("timeout_minutes", 340)),
            }
            for p in self._settings.prompts
        ]

    def extract(self, prompt_id: str) -> str:
        p = self._settings.prompt(prompt_id)
        body = PromptPage.text((self._root / p.page).read_text(encoding="utf-8"))
        if body is None:
            raise ValueError(f"{p.page} has no prompt block")
        return body

    def plan(self, prompt_id: str) -> str:
        """The prompt, its authority for this run, and the evidence its declared commands gather.

        Output past `[run] evidence_chars` is cut and says so at the cut (ADR-0075: no silent
        truncation), so a small model reads a bounded, honest context.
        """
        p = self._settings.prompt(prompt_id)
        cap = int(self._settings.run.get("evidence_chars", 12000))
        timeout = float(self._settings.run.get("gather_timeout_s", 120))
        parts = [self.extract(prompt_id), "", "## Authority for this run", ""]
        if p.mode == "act":
            parts.append(
                "You may change files in this checkout. Your changes become ONE draft pull "
                "request opened by the workflow after you finish; you never push, merge, "
                "approve, release, delete, or touch rulesets or secrets yourself."
            )
        else:
            parts.append(
                "DRILL: change nothing. Verify each instruction above against the evidence and "
                "the repository, and end with a list headed 'Does not hold:' (or 'All holds.')."
            )
        parts += ["", "## Evidence gathered for you", ""]
        for command in p.gather:
            code, out = self._runner.run(command, timeout_s=timeout)
            if len(out) > cap:
                out = out[:cap] + f"\n[... cut at {cap} characters of {len(out)} ...]"
            parts += [f"$ {command}   (exit {code})", "```", out.rstrip(), "```", ""]
        return "\n".join(parts)


class ContinuationCli:
    """The command line."""

    def __init__(self, root: Path) -> None:
        self._root = root

    def run(self, argv: Sequence[str]) -> int:
        if not argv or argv[0] not in {"render", "check", "matrix", "extract", "plan"}:
            print(__doc__, file=sys.stderr)
            return 2
        settings = Settings.load(self._root)
        runner = SubprocessRunner(self._root)
        prompts = ContinuationPrompts(
            self._root,
            settings,
            RepositoryFacts(self._root),
            ReferenceProbe(self._root, runner),
            runner,
        )
        command = argv[0]
        if command == "render":
            for page in prompts.render():
                print(f"{SCRIPT}: rendered {page}")
            return 0
        if command == "check":
            problems = prompts.problems()
            for line in problems:
                print(f"::error::{line}")
            if problems:
                return 1
            print(
                f"{SCRIPT}: {len(settings.prompts)} prompts hold, every lane and skill is covered"
            )
            return 0
        if command == "matrix":
            print(json.dumps(prompts.matrix()))
            return 0
        if len(argv) < 2:
            print(f"{SCRIPT}: {command} needs a prompt id", file=sys.stderr)
            return 2
        print(prompts.extract(argv[1]) if command == "extract" else prompts.plan(argv[1]))
        return 0


if __name__ == "__main__":
    sys.exit(ContinuationCli(REPO).run(sys.argv[1:]))
