# Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
"""Regenerate the data-driven figures in docs/paper.md from tracked sources.

Every empirical figure in the paper is a ```latex fence written between a pair of markers:

    <!-- BEGIN GENERATED figure:NAME rev:REVISION — regenerated by scripts/paper_figures.py -->
    ...the figure, as pgfplots/TikZ with its data inlined...
    <!-- END GENERATED figure:NAME -->

This script recomputes each block from the repository's own tracked records and nothing
else -- the stress record, the Qwen storm extraction, the QwenStorm 3.0.0 evidence ledger,
the host benchmark, the delivery-estimate ledger, the test-time evidence, and the git history
read at the revision the marker names -- so anyone holding the checkout can rebuild every
picture the paper shows, and a picture can never quietly disagree with the numbers beside it.

    python scripts/paper_figures.py --rev <sha>          # rewrite the blocks in docs/paper.md
    python scripts/paper_figures.py --check              # exit 1 if any block would change
    python scripts/paper_figures.py --emit DIR           # one .tex spec per figure, for a figure lab

Sub-doctrine 12.e: the toil of keeping a picture in step with its data is automated, and the
`--check` mode is the check that says out loud when the step was missed. The history figures
are pinned to a revision (`rev:` in the marker) so the check is deterministic; in a shallow
clone the pinned revision cannot be walked, and the check says so instead of pretending.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from collections import Counter, defaultdict
from collections.abc import Callable
from datetime import UTC, date, datetime, timedelta
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

from interfaces.paper_figures_interface import FigureSourceInterface, PaperFigureAtlasInterface
from paper_evidence import DEFAULT_QWEN_STORM_RECORD, DEFAULT_STRESS_RECORD, StressRecord

DEFAULT_PAPER = "docs/paper.md"
DEFAULT_STORM_DIR = "docs/plans/qwenstorm-3.0.0"
DEFAULT_FORECAST_LEDGER = ".vibey/delivery-estimates.jsonl"
DEFAULT_TEST_TIME_RECORD = "docs/runbooks/expansion/evidence/13-front1-validation.md"
DEFAULT_TIMEZONE = "America/New_York"
DEFAULT_SINCE = date(2026, 8, 9)
SCRIPT = "scripts/paper_figures.py"
PACKAGES: tuple[tuple[str, str], ...] = (
    ("vibey", "src/vibey"),
    ("vibey-gh", "src/vibey_tools/gh"),
    ("claudeloop", "src/vibey_runners/claude"),
    ("vibey-bootstrap", "src/vibey_tools/bootstrap"),
    ("agyloop", "src/vibey_runners/agy"),
    ("codexloop", "src/vibey_runners/codex"),
    ("cursorloop", "src/vibey_runners/cursor"),
    ("qwenloop", "src/vibey_runners/qwen"),
    ("vibey-skills", "src/vibey_tools/skills"),
    ("opencodeloop", "src/vibey_runners/opencode"),
    ("runners-common", "src/vibey_runners/common"),
)
LAYERS: tuple[str, ...] = ("domain", "application", "infrastructure", "cli", "tui")
TAG_PACKAGES: tuple[tuple[str, str], ...] = (
    ("vibey-v", "vibey"),
    ("claudeloop-v", "claudeloop"),
    ("agyloop-v", "agyloop"),
    ("cursorloop-v", "cursorloop"),
    ("v", "codexloop"),
)
_MARKER = re.compile(
    r"<!-- BEGIN GENERATED figure:(?P<name>[a-z0-9-]+) rev:(?P<rev>[0-9a-f]+) — regenerated by "
    + re.escape(SCRIPT)
    + r" -->\n(?P<body>.*?)<!-- END GENERATED figure:(?P=name) -->",
    re.DOTALL,
)
_TEST_DEF = re.compile(rb"^\s*(?:async\s+)?def test_", re.MULTILINE)
_FENCE = re.compile(r"^```latex\n(.*?)^```", re.DOTALL | re.MULTILINE)
_LABEL = re.compile(r"\\label\{(fig:[^}]+)\}")
_REF = re.compile(r"\[(?:Fig\.?|Figure)\s*\d*\]\(#(fig:[A-Za-z0-9:_-]+)\)")
_STREAM = re.compile(r"^(?P<at>\S+Z) (?P<verb>start|end)\s+(?P<lane>\S+)")
_PR_SUBJECT = re.compile(r"\(#\d+\)$")
_CC_TYPE = re.compile(r"^([a-z]+)(?:\([^)]*\))?!?:")


def _tex(text: str) -> str:
    """Escape the handful of characters that would break TeX inside a node label."""
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("#", r"\#")
        .replace("_", r"\_")
        .replace("$", r"\$")
    )


def _fmt(value: float, digits: int = 2) -> str:
    return f"{value:.{digits}f}"


def _thousands(value: int) -> str:
    return f"{value:,}"


# ------------------------------------------------------------------- sources


class StressTable(FigureSourceInterface):
    """The stress record's rung table with every column, plus the evidence summary."""

    def __init__(self, path: Path, record: StressRecord) -> None:
        self._path = path
        self._record = record

    def load(self) -> dict[str, Any]:
        rows: list[dict[str, float]] = []
        in_table = False
        for line in self._path.read_text(encoding="utf-8").splitlines():
            if line.startswith("| Concurrency"):
                in_table = True
                continue
            if not in_table:
                continue
            if not line.startswith("|"):
                break
            cells = [c.strip().strip("*").strip() for c in line.strip("|").split("|")]
            if set(cells[0]) <= set("-: "):
                continue
            succeeded, attempted = (int(p) for p in cells[1].split("/"))
            number = lambda cell: float(re.search(r"\d+(?:\.\d+)?", cell).group(0))  # noqa: E731
            rows.append(
                {
                    "n": int(cells[0]),
                    "attempted": attempted,
                    "succeeded": succeeded,
                    "success": succeeded / attempted,
                    "p50": number(cells[3]),
                    "max": number(cells[4]),
                    "throughput": number(cells[5]),
                    "free_memory": number(cells[6]),
                }
            )
        if not rows:
            raise ValueError(f"{self._path}: no rung table found")
        return {"rungs": rows, "summary": self._record.summary()}


class QwenRuns(FigureSourceInterface):
    """The tracked, cutoff-bounded extraction of the 2026-09-20 local Qwen storm."""

    def __init__(self, path: Path) -> None:
        self._path = path

    def load(self) -> dict[str, Any]:
        record = json.loads(self._path.read_text(encoding="utf-8"))
        runs = sorted(record["runs"], key=lambda run: run.get("started_at") or "")
        return {"runs": runs, "observed_at": record.get("observed_at", "")}


class StormLedger(FigureSourceInterface):
    """The QwenStorm 3.0.0 evidence ledger: lane results and the progress stream."""

    def __init__(self, storm_dir: Path) -> None:
        self._dir = storm_dir

    def load(self) -> dict[str, Any]:
        ledger = self._dir / "evidence" / "ledger.jsonl"
        records = [
            json.loads(line)
            for line in ledger.read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        lanes: list[dict[str, Any]] = []
        for record in records:
            if record.get("kind") != "lane_result":
                continue
            result = record.get("result", {})
            attempts = [
                {"status": str(a.get("status", "")), "turns": int(a.get("turns", 0) or 0)}
                for a in result.get("attempts", [])
            ]
            lanes.append(
                {
                    "lane": record["lane"],
                    "issue": result.get("issue"),
                    "completed": bool(record.get("completed")),
                    "attempts": attempts,
                }
            )
        lanes.sort(key=lambda lane: (lane["issue"] or 0, lane["lane"]))
        starts: dict[str, list[dict[str, Any]]] = defaultdict(list)
        segments: list[dict[str, Any]] = []
        for record in records:
            if record.get("kind") != "stream" or record.get("source") != "progress.log":
                continue
            match = _STREAM.match(record.get("line", ""))
            if not match:
                continue
            stamp = datetime.strptime(match["at"], "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=UTC)
            lane = match["lane"]
            if match["verb"] == "start":
                starts[lane].append({"lane": lane, "start": stamp, "end": None})
                segments.append(starts[lane][-1])
            elif starts[lane] and starts[lane][-1]["end"] is None:
                starts[lane][-1]["end"] = stamp
        integrated = [
            line
            for line in (self._dir / "integrated.txt").read_text(encoding="utf-8").split()
            if line
        ]
        abandoned = [
            line
            for line in (self._dir / "abandoned.txt").read_text(encoding="utf-8").split()
            if line
        ]
        watermark = json.loads(
            (self._dir / "evidence" / "watermark.json").read_text(encoding="utf-8")
        )
        return {
            "records": len(records),
            "lanes": lanes,
            "segments": segments,
            "integrated": integrated,
            "abandoned": abandoned,
            "consumed_from": records[0]["consumed_at"] if records else None,
            "consumed_to": records[-1]["consumed_at"] if records else None,
            "gaps": watermark.get("gaps", []),
        }


class HostBench(FigureSourceInterface):
    """The 2026-09-22 host benchmark and the host-tuning record it fed."""

    def __init__(self, storm_dir: Path) -> None:
        self._dir = storm_dir / "bench"

    def load(self) -> dict[str, Any]:
        rows = [
            json.loads(line)
            for line in (self._dir / "results.jsonl").read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        turns: dict[str, list[dict[str, Any]]] = defaultdict(list)
        summaries: dict[str, dict[str, Any]] = {}
        errors: dict[str, list[str]] = defaultdict(list)
        for row in rows:
            label = row["label"]
            if row.get("error"):
                errors[label].append(row["error"])
            elif row.get("summary"):
                summaries[label] = row
            else:
                turns[label].append(row)
        tuning = tomllib.loads((self._dir / "host-tuning.toml").read_text(encoding="utf-8"))
        return {
            "turns": dict(turns),
            "summaries": summaries,
            "errors": dict(errors),
            "context": tuning["context"]["measured"],
            "decision": tuning["context"]["decision"],
            "sweep": tuning["sweep"],
            "memory_before": tuning["memory"]["observed_before"],
            "host": tuning["host"],
        }


class DeliveryForecast(FigureSourceInterface):
    """The append-only delivery-estimate ledger, one forecast per record."""

    def __init__(self, path: Path) -> None:
        self._path = path

    def load(self) -> dict[str, Any]:
        records = []
        for line in self._path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            payload = json.loads(line)["payload"]
            history = payload.get("history", {})
            records.append(
                {
                    "recorded_at": payload["recorded_at"],
                    "days_low": float(payload["time"]["days_low"]),
                    "days_high": float(payload["time"]["days_high"]),
                    "remaining": float(history.get("work_units", {}).get("remaining", 0) or 0),
                    "completed": float(history.get("work_units", {}).get("completed", 0) or 0),
                    "merged": int(history.get("pull_requests", {}).get("merged", 0) or 0),
                    "open_issues": int(history.get("issues", {}).get("open", 0) or 0),
                }
            )
        return {"records": records}


class TestTimeEvidence(FigureSourceInterface):
    """The measured wall times of the test-suite parallelisation workstream."""

    def __init__(self, path: Path) -> None:
        self._path = path

    def load(self) -> dict[str, Any]:
        text = self._path.read_text(encoding="utf-8")
        suite = re.search(r"(\d+) s → (\d+) s \(\*\*([\d.]+)×\*\*\)", text)
        gates = re.search(r"\*\*(\d+) s\*\* \(was ~(\d+) s\) — \*\*([\d.]+)×\*\*", text)
        if not suite or not gates:
            raise ValueError(f"{self._path}: the before/after wall times were not found")
        return {
            "suite_before": int(suite.group(1)),
            "suite_after": int(suite.group(2)),
            "suite_factor": float(suite.group(3)),
            "gates_before": int(gates.group(2)),
            "gates_after": int(gates.group(1)),
            "gates_factor": float(gates.group(3)),
        }


class CommitSeries(FigureSourceInterface):
    """The git history at one revision as time series: days, hours, weekdays, tags, roots."""

    def __init__(
        self, repo: Path, revision: str, since: date = DEFAULT_SINCE, tz: str = DEFAULT_TIMEZONE
    ) -> None:
        self._repo = repo
        self._revision = revision
        self._since = since
        self._zone = ZoneInfo(tz)

    def _git(self, *args: str) -> str:
        return subprocess.run(
            ["git", *args], cwd=self._repo, check=True, capture_output=True, text=True
        ).stdout

    def load(self) -> dict[str, Any]:
        rev = self._revision
        head = self._git("rev-parse", rev).strip()
        head_time = int(self._git("log", "-1", "--format=%ct", rev))
        log = self._git("log", "--format=%at%x09%s", rev).splitlines()
        stamps: list[datetime] = []
        subjects: list[str] = []
        for line in log:
            stamp, _, subject = line.partition("\t")
            stamps.append(datetime.fromtimestamp(int(stamp), self._zone))
            subjects.append(subject)
        window = [
            (s, sub) for s, sub in zip(stamps, subjects, strict=True) if s.date() >= self._since
        ]
        per_day: Counter[date] = Counter(s.date() for s, _ in window)
        per_hour: Counter[int] = Counter(s.hour for s, _ in window)
        per_weekday: Counter[int] = Counter(s.weekday() for s, _ in window)
        types: Counter[str] = Counter()
        for _, subject in window:
            match = _CC_TYPE.match(subject)
            types[match.group(1) if match else "other"] += 1
        pr_days: Counter[date] = Counter(s.date() for s, sub in window if _PR_SUBJECT.search(sub))
        roots = []
        for sha in self._git("rev-list", "--max-parents=0", rev).split():
            stamp, _, subject = (
                self._git("log", "-1", "--format=%at%x09%s", sha).strip().partition("\t")
            )
            roots.append(
                {
                    "sha": sha[:8],
                    "date": datetime.fromtimestamp(int(stamp), self._zone).date(),
                    "subject": subject,
                }
            )
        roots.sort(key=lambda r: r["date"])
        tags = []
        for line in self._git(
            "for-each-ref", "--format=%(refname:short) %(creatordate:unix)", "refs/tags"
        ).splitlines():
            name, stamp = line.rsplit(" ", 1)
            if int(stamp) > head_time or name.startswith("scrapped/"):
                continue
            package = next((pkg for prefix, pkg in TAG_PACKAGES if name.startswith(prefix)), None)
            if package is None:
                continue
            tags.append(
                {
                    "name": name,
                    "package": package,
                    "date": datetime.fromtimestamp(int(stamp), self._zone).date(),
                }
            )
        tags.sort(key=lambda t: (t["date"], t["name"]))
        last_day = max(per_day) if per_day else self._since
        return {
            "head": head,
            "head_date": datetime.fromtimestamp(head_time, self._zone).date(),
            "since": self._since,
            "last_day": last_day,
            "total_commits": len(stamps),
            "window_commits": len(window),
            "per_day": {d: n for d, n in sorted(per_day.items())},
            "per_hour": [per_hour.get(h, 0) for h in range(24)],
            "per_weekday": [per_weekday.get(d, 0) for d in range(7)],
            "types": dict(types.most_common()),
            "pr_days": {d: n for d, n in sorted(pr_days.items())},
            "roots": roots,
            "tags": tags,
        }


class CodebaseShape(FigureSourceInterface):
    """Lines of Python and test functions per package and per vibey layer, at a revision."""

    def __init__(self, repo: Path, revision: str) -> None:
        self._repo = repo
        self._revision = revision

    def load(self) -> dict[str, Any]:
        rev = self._revision
        listing = subprocess.run(
            ["git", "ls-tree", "-r", "--name-only", rev],
            cwd=self._repo,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.split("\n")
        paths = [p for p in listing if p.endswith(".py")]
        batch = subprocess.run(
            ["git", "cat-file", "--batch"],
            cwd=self._repo,
            check=True,
            input="".join(f"{rev}:{p}\n" for p in paths).encode(),
            capture_output=True,
        ).stdout
        lines_by_path: dict[str, int] = {}
        tests_by_path: dict[str, int] = {}
        offset = 0
        for path in paths:
            header_end = batch.index(b"\n", offset)
            header = batch[offset:header_end].decode()
            size = int(header.split()[-1])
            content = batch[header_end + 1 : header_end + 1 + size]
            offset = header_end + 1 + size + 1
            lines_by_path[path] = content.count(b"\n")
            if re.search(r"(^|/)tests?/", path):
                tests_by_path[path] = len(_TEST_DEF.findall(content))
        packages = []
        for name, prefix in PACKAGES:
            inside = [p for p in paths if p.startswith(prefix + "/")]
            packages.append(
                {
                    "package": name,
                    "lines": sum(lines_by_path[p] for p in inside),
                    "tests": sum(tests_by_path.get(p, 0) for p in inside),
                }
            )
        root_tests = sum(n for p, n in tests_by_path.items() if p.startswith("tests/"))
        layers = {
            layer: sum(lines_by_path[p] for p in paths if p.startswith(f"src/vibey/{layer}/"))
            for layer in LAYERS
        }
        return {
            "packages": packages,
            "root_tests": root_tests,
            "layers": layers,
            "python_files": len(paths),
            "python_lines": sum(lines_by_path.values()),
            "test_functions": sum(tests_by_path.values()),
        }


# ------------------------------------------------------------------- the atlas


class PaperFigureAtlas(PaperFigureAtlasInterface):
    """Every generated figure of the paper, rendered as ```latex fences with their data inlined."""

    def __init__(
        self,
        revision: str,
        stress: FigureSourceInterface,
        qwen: FigureSourceInterface,
        storm: FigureSourceInterface,
        bench: FigureSourceInterface,
        forecast: FigureSourceInterface,
        test_time: FigureSourceInterface,
        commits: FigureSourceInterface,
        shape: FigureSourceInterface,
    ) -> None:
        self._revision = revision
        self._sources = {
            "stress": stress,
            "qwen": qwen,
            "storm": storm,
            "bench": bench,
            "forecast": forecast,
            "test_time": test_time,
            "commits": commits,
            "shape": shape,
        }
        self._loaded: dict[str, dict[str, Any]] = {}

    def _data(self, key: str) -> dict[str, Any]:
        if key not in self._loaded:
            self._loaded[key] = self._sources[key].load()
        return self._loaded[key]

    # --- the block grammar -------------------------------------------------------------

    @staticmethod
    def _fence(env: str, label: str, caption: str, body: str) -> str:
        return "\n".join(
            [
                "```latex",
                f"\\begin{{{env}}}[t]",
                r"\centering",
                body.rstrip("\n"),
                f"\\caption{{{caption}}}",
                f"\\label{{{label}}}",
                f"\\end{{{env}}}",
                "```",
            ]
        )

    def _begin(self, name: str) -> str:
        return (
            f"<!-- BEGIN GENERATED figure:{name} rev:{self._revision} — regenerated by {SCRIPT} -->"
        )

    @staticmethod
    def _end(name: str) -> str:
        return f"<!-- END GENERATED figure:{name} -->"

    # --- figures -------------------------------------------------------------------------

    def stress_dashboard(self) -> str:
        data = self._data("stress")
        rungs, summary = data["rungs"], data["summary"]
        region = summary["region"]
        low, high = region["concurrency"]
        band_lo, band_hi = region["throughput_min"], region["throughput_max"]
        coords = " ".join(f"({r['n']},{r['throughput']})" for r in rungs)
        by_class = {"good": [], "fair": [], "over": []}
        for r in rungs:
            key = "good" if r["success"] >= 0.95 else "fair" if r["success"] >= 0.875 else "over"
            by_class[key].append(r)
        success_bars = "\n".join(
            f"\\addplot[ybar,bar width=5pt,bar shift=0pt,draw=none,fill={color}] coordinates {{"
            + " ".join(f"({r['n']},{r['success'] * 100:.1f})" for r in rows)
            + "};"
            for key, color, rows in (
                ("good", "vibeygreen!80", by_class["good"]),
                ("fair", "vibeygold!90", by_class["fair"]),
                ("over", "vibeyred!75", by_class["over"]),
            )
            if rows
        )
        p50 = " ".join(f"({r['n']},{r['p50']})" for r in rungs)
        pmax = " ".join(f"({r['n']},{r['max']})" for r in rungs)
        envelope = (
            " ".join(f"({r['n']},{r['p50']})" for r in rungs)
            + " "
            + " ".join(f"({r['n']},{r['max']})" for r in reversed(rungs))
        )
        memory = " ".join(f"({r['n']},{r['free_memory']})" for r in rungs)
        peak = summary["peak"]
        last = summary["last"]
        ticks = "1,2,4,8,16,32,64,128"
        body = f"""\\begin{{tikzpicture}}
\\begin{{groupplot}}[group style={{group size=2 by 2,horizontal sep=1.7cm,vertical sep=1.45cm}},
  vibeyaxis,width=7.9cm,height=4.3cm,xmode=log,log basis x=2,xtick={{{ticks}}},xticklabels={{{ticks}}},
  xmin=0.8,xmax=160,xlabel={{offered concurrency $N$}}]
\\nextgroupplot[title={{a. Successful throughput}},ylabel={{generations / min}},ymin=0,ymax=4]
\\fill[vibeyblue!9] (axis cs:{low},0) rectangle (axis cs:{high},4);
\\node[vibeynote,text=vibeyblue,anchor=south] at (axis cs:8,3.55) {{stable region $N={low}$--${high}$}};
\\draw[vibeydashed] (axis cs:0.8,{band_lo}) -- (axis cs:160,{band_lo}) node[vibeynote,anchor=west,text=vibeygray] {{{_fmt(band_lo)}}};
\\draw[vibeydashed] (axis cs:0.8,{band_hi}) -- (axis cs:160,{band_hi}) node[vibeynote,anchor=west,text=vibeygray] {{{_fmt(band_hi)}}};
\\addplot[vibeyblue,line width=1pt,mark=*,mark size=1.4pt,mark options={{fill=white,line width=.7pt}}] coordinates {{{coords}}};
\\node[vibeycallout,anchor=south east] at (axis cs:{peak["concurrency"]},{peak["throughput"]}) {{peak {_fmt(peak["throughput"])}/min\\\\{peak["success"] * 100:.1f}\\% success}};
\\node[vibeycallout,anchor=north west] at (axis cs:{last["concurrency"]},{last["throughput"]}) {{collapse}};
\\nextgroupplot[title={{b. Success fraction}},ylabel={{succeeded (\\%)}},ymin=0,ymax=124,ytick={{0,25,50,75,100}}]
\\draw[vibeydashed] (axis cs:0.8,87.5) -- (axis cs:160,87.5) node[vibeynote,anchor=west,text=vibeygray] {{87.5}};
{success_bars}
\\node[vibeynote,anchor=north west,align=left] at (axis cs:0.9,122) {{\\textcolor{{vibeygreen}}{{$\\blacksquare$}} 100\\% \\quad \\textcolor{{vibeygold}}{{$\\blacksquare$}} 87.5--93.8\\% \\quad \\textcolor{{vibeyred}}{{$\\blacksquare$}} overloaded}};
\\nextgroupplot[title={{c. Latency against the 900\\,s deadline}},ylabel={{seconds}},ymin=0,ymax=1000,legend pos=north west]
\\addplot[fill=vibeyblue!12,draw=none,forget plot] coordinates {{{envelope}}} -- cycle;
\\draw[vibeyred,densely dashed,line width=.7pt] (axis cs:0.8,900) -- (axis cs:160,900) node[vibeycallout,anchor=south east] {{deadline}};
\\addplot[vibeyblue,line width=1pt,mark=*,mark size=1.2pt] coordinates {{{p50}}};
\\addlegendentry{{p50}}
\\addplot[vibeyteal,line width=.8pt,mark=square*,mark size=1.1pt] coordinates {{{pmax}}};
\\addlegendentry{{max}}
\\nextgroupplot[title={{d. Free memory during the rung}},ylabel={{free memory (\\%)}},ymin=0,ymax=14]
\\addplot[vibeyviolet,line width=1pt,mark=*,mark size=1.2pt,mark options={{fill=white}}] coordinates {{{memory}}};
\\node[vibeycallout,anchor=south east,align=right] at (axis cs:140,12.1) {{paging space 99.1\\%\\\\at $N=128$}};
\\node[vibeynote,anchor=south west,align=left] at (axis cs:1,0.5) {{server crashed and self-restarted\\\\at $N=64$ and $N=128$}};
\\end{{groupplot}}
\\end{{tikzpicture}}"""
        caption = (
            f"The sovereignty stress record in four views. (a) Successful throughput rises into a broad "
            f"stable band, {_fmt(band_lo)}--{_fmt(band_hi)} generations per minute, across offered concurrency "
            f"$N={low}$ to ${high}$, then peaks at {_fmt(peak['throughput'])} per minute at $N={peak['concurrency']}$ "
            f"before collapsing. (b) The success fraction stays at or above 87.5\\% through $N={high}$ and falls "
            f"beyond it. (c) Median latency and the slowest generation of each rung approach the 900\\,s deadline "
            f"as the substrate saturates. (d) Free memory oscillated in a narrow band throughout; paging space, "
            f"not free memory, marked the collapse. Every point reproduces the record's rung table."
        )
        return self._fence("figure*", "fig:stress-rate", caption, body)

    def stress_cumulative(self) -> str:
        rungs = self._data("stress")["rungs"]
        attempted, succeeded = 0, 0
        att_coords, suc_coords, labels = [], [], []
        for i, r in enumerate(rungs, 1):
            attempted += r["attempted"]
            succeeded += r["succeeded"]
            att_coords.append(f"({i},{attempted})")
            suc_coords.append(f"({i},{succeeded})")
            labels.append(str(r["n"]))
        n = len(rungs)
        body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[vibeyaxis,width=8.6cm,height=5cm,xmin=1,xmax={n},ymin=0,ymax={attempted + 30},
  xtick={{{",".join(str(i) for i in range(1, n + 1))}}},xticklabels={{{",".join(labels)}}},
  xlabel={{rung (offered concurrency $N$)}},ylabel={{generations, cumulative}},legend pos=north west]
\\addplot[fill=vibeysilver!35,draw=vibeysilver,line width=.5pt] coordinates {{{" ".join(att_coords)}}} \\closedcycle;
\\addlegendentry{{attempted}}
\\addplot[fill=vibeygreen!45,draw=vibeygreen,line width=.8pt] coordinates {{{" ".join(suc_coords)}}} \\closedcycle;
\\addlegendentry{{succeeded}}
\\node[vibeynote,anchor=south east,align=right] at (axis cs:{n},{succeeded + 8}) {{{succeeded} of {attempted}\\\\{succeeded / attempted * 100:.1f}\\% overall}};
\\end{{axis}}
\\end{{tikzpicture}}"""
        caption = (
            f"Cumulative generations across the fourteen rungs of the stress record: {attempted} attempted, "
            f"{succeeded} succeeded. The gap opens only after the stable region; every failure in the run was a "
            f"clean timeout, never a malformed response."
        )
        return self._fence("figure", "fig:stress-cumulative", caption, body)

    def qwen_runs(self) -> str:
        data = self._data("qwen")
        runs = data["runs"]
        colors = {
            "completed": "vibeygreen",
            "incomplete_verdict_only": "vibeygold",
            "incomplete_without_verdict": "vibeyred",
            "incomplete_tool_error": "vibeyred!60",
            "no_events_at_cutoff": "vibeysilver",
        }
        n = len(runs)
        ticks = ",".join(str(i) for i in range(1, n + 1))
        turns = " ".join(f"({i},{r['turns']})" for i, r in enumerate(runs, 1))
        calls = " ".join(f"({i},{r['tool_calls']})" for i, r in enumerate(runs, 1))
        tokens_in = " ".join(f"({i},{r['input_tokens'] / 1000:.1f})" for i, r in enumerate(runs, 1))
        tokens_out = " ".join(
            f"({i},{r['output_tokens'] / 1000:.1f})" for i, r in enumerate(runs, 1)
        )
        strip = "\n".join(
            f"\\node[fill={colors.get(r.get('disposition'), 'vibeygray')},minimum width=8pt,minimum height=4pt,inner sep=0pt] at (axis cs:{i},-4.5) {{}};"
            for i, r in enumerate(runs, 1)
        )
        strip_tokens = "\n".join(
            f"\\node[fill={colors.get(r.get('disposition'), 'vibeygray')},minimum width=8pt,minimum height=4pt,inner sep=0pt] at (axis cs:{i},-27) {{}};"
            for i, r in enumerate(runs, 1)
        )
        counts = Counter(r.get("disposition") for r in runs)
        body = f"""\\begin{{tikzpicture}}
\\begin{{groupplot}}[group style={{group size=2 by 1,horizontal sep=1.8cm}},vibeyaxis,width=8.6cm,height=4.6cm,
  xmin=0.3,xmax={n + 0.7},xtick={{{ticks}}},xlabel={{run, in order of start}}]
\\nextgroupplot[title={{a. Turns and tool calls per run}},ylabel={{count}},ymin=0,legend pos=north west,ybar,bar width=4pt]
\\addplot[fill=vibeyblue,draw=none] coordinates {{{turns}}};
\\addlegendentry{{model turns}}
\\addplot[fill=vibeyteal!80,draw=none] coordinates {{{calls}}};
\\addlegendentry{{tool calls}}
{strip}
\\nextgroupplot[title={{b. Tokens per run (thousands)}},ylabel={{tokens ($\\times 10^3$)}},ymin=0,legend pos=north west,ybar,bar width=4pt]
\\addplot[fill=vibeyviolet!85,draw=none] coordinates {{{tokens_in}}};
\\addlegendentry{{input}}
\\addplot[fill=vibeygold,draw=none] coordinates {{{tokens_out}}};
\\addlegendentry{{output}}
{strip_tokens}
\\end{{groupplot}}
\\node[vibeynote,anchor=north west,align=left] at ([yshift=-0.85cm]group c1r1.south west)
  {{disposition strip: \\textcolor{{vibeygreen}}{{$\\blacksquare$}} completed ({counts.get("completed", 0)}) \\;
   \\textcolor{{vibeygold}}{{$\\blacksquare$}} verdict only ({counts.get("incomplete_verdict_only", 0)}) \\;
   \\textcolor{{vibeyred}}{{$\\blacksquare$}} no verdict ({counts.get("incomplete_without_verdict", 0)}) \\;
   \\textcolor{{vibeyred!60}}{{$\\blacksquare$}} tool error ({counts.get("incomplete_tool_error", 0)}) \\;
   \\textcolor{{vibeysilver}}{{$\\blacksquare$}} no events ({counts.get("no_events_at_cutoff", 0)})}};
\\end{{tikzpicture}}"""
        total_in = sum(r["input_tokens"] for r in runs)
        total_out = sum(r["output_tokens"] for r in runs)
        caption = (
            f"The thirteen run directories of the cutoff-bounded local Qwen storm, in order of start. "
            f"(a) Model turns and tool calls; (b) input and output tokens, {_thousands(total_in)} and "
            f"{_thousands(total_out)} in all. The strip beneath each panel colours every run by its disposition "
            f"at the cutoff: only {counts.get('completed', 0)} of {n} both emitted a verdict and wrote the "
            f"completion marker, and the largest run, forty turns and {_thousands(max(r['input_tokens'] for r in runs))} "
            f"input tokens, ended without a verdict at all."
        )
        return self._fence("figure*", "fig:qwen-runs", caption, body)

    def storm_lanes(self) -> str:
        data = self._data("storm")
        lanes = data["lanes"]
        scale = 0.052  # cm per turn
        row = 0.30
        max_turns = max(sum(a["turns"] for a in lane["attempts"]) for lane in lanes)
        lines = []
        for i, lane in enumerate(lanes):
            y = -i * row
            x = 0.0
            for attempt in lane["attempts"]:
                width = attempt["turns"] * scale
                color = "vibeygreen!80" if attempt["status"] == "completed" else "vibeyred!55"
                lines.append(
                    f"\\fill[{color},rounded corners=1pt] ({x:.2f},{y - 0.11:.2f}) rectangle ({x + width:.2f},{y + 0.11:.2f});"
                )
                x += width + 0.04
            mark = (
                r"\textcolor{vibeygreen}{\ding{51}}"
                if lane["completed"]
                else r"\textcolor{vibeyred}{\ding{55}}"
            )
            lines.append(
                f"\\node[font=\\sffamily\\tiny,anchor=east,text=vibeyink] at (-0.15,{y:.2f}) {{{_tex(lane['lane'])}}};"
            )
            lines.append(
                f"\\node[font=\\sffamily\\tiny,anchor=west,text=vibeygray] at ({x + 0.05:.2f},{y:.2f}) {{\\#{lane['issue']} {mark} {sum(a['turns'] for a in lane['attempts'])}}};"
            )
        height = -(len(lanes) - 1) * row
        axis = " ".join(
            f"\\draw[vibeyline] ({t * scale:.2f},{height - 0.25:.2f}) -- ({t * scale:.2f},0.25) node[vibeynote,anchor=south] {{{t}}};"
            for t in range(0, int(max_turns) + 1, 40)
        )
        total_attempts = sum(len(lane["attempts"]) for lane in lanes)
        total_turns = sum(a["turns"] for lane in lanes for a in lane["attempts"])
        claimed = sum(1 for lane in lanes if lane["completed"])
        body = f"""\\begin{{tikzpicture}}[x=1cm,y=1cm]
\\begin{{scope}}[on background layer]
{axis}
\\end{{scope}}
\\node[vibeyhead] at (-4.0,0.55) {{lane}};
\\node[vibeyhead,anchor=south] at ({max_turns * scale / 2:.2f},0.55) {{turns spent, attempt after attempt}};
\\node[vibeyhead,anchor=south west] at ({max_turns * scale + 0.1:.2f},0.55) {{issue \\; outcome \\; turns}};
{chr(10).join(lines)}
\\node[vibeynote,anchor=north west,align=left] at (-4.0,{height - 0.5:.2f})
  {{\\textcolor{{vibeygreen!80}}{{$\\blacksquare$}} attempt completed \\quad \\textcolor{{vibeyred!55}}{{$\\blacksquare$}} attempt failed \\quad
   {len(lanes)} lanes, {total_attempts} attempts, {_thousands(total_turns)} turns; {claimed} lanes claimed completion,
   {len(data["integrated"])} were integrated and {len(data["abandoned"])} abandoned by the reviewer}};
\\end{{tikzpicture}}"""
        caption = (
            f"Every lane of the QwenStorm 3.0.0 evidence ledger, one row per lane in issue order. Each bar is one "
            f"attempt, its length the turns the local model spent, green where the attempt ended in a completion "
            f"claim and red where it failed; a lane gets at most three. Of {len(lanes)} lanes, {claimed} claimed "
            f"completion, and a claim is not delivery: the reviewer integrated {len(data['integrated'])} and abandoned "
            f"{len(data['abandoned'])} over the same span. Read from the ledger between "
            f"{data['consumed_from']} and {data['consumed_to']} with no gaps."
        )
        return self._fence("figure*", "fig:storm-lanes", caption, body)

    def storm_timeline(self) -> str:
        data = self._data("storm")
        segments = [s for s in data["segments"] if s["start"] is not None]
        if not segments:
            raise ValueError("the storm ledger holds no lane start lines")
        t0 = min(s["start"] for s in segments)
        t_end = max((s["end"] or s["start"]) for s in segments)
        span_h = max(1.0, (t_end - t0).total_seconds() / 3600)
        width = 12.4
        per_h = width / span_h
        order: list[str] = []
        for s in segments:
            if s["lane"] not in order:
                order.append(s["lane"])
        row = 0.24
        lines = []
        for s in segments:
            i = order.index(s["lane"])
            y = -i * row
            x0 = (s["start"] - t0).total_seconds() / 3600 * per_h
            if s["end"] is None:
                x1 = x0 + 0.12
                lines.append(
                    f"\\fill[vibeysilver] ({x0:.2f},{y - 0.09:.2f}) rectangle ({x1:.2f},{y + 0.09:.2f});"
                )
                if not any(f"at ({x1 + 0.03:.2f},{y:.2f})" in line for line in lines):
                    lines.append(
                        f"\\node[vibeynote,anchor=west,text=vibeysilver] at ({x1 + 0.03:.2f},{y:.2f}) {{no end}};"
                    )
            else:
                x1 = max(x0 + 0.06, (s["end"] - t0).total_seconds() / 3600 * per_h)
                lines.append(
                    f"\\fill[vibeyblue!80,rounded corners=1pt] ({x0:.2f},{y - 0.09:.2f}) rectangle ({x1:.2f},{y + 0.09:.2f});"
                )
        for i, lane in enumerate(order):
            lines.append(
                f"\\node[font=\\sffamily\\tiny,anchor=east,text=vibeyink] at (-0.12,{-i * row:.2f}) {{{_tex(lane)}}};"
            )
        height = -(len(order) - 1) * row
        ticks = []
        first_hour = t0.replace(minute=0, second=0, microsecond=0)
        hours = int(span_h) + 2
        for h in range(0, hours + 1, 2):
            stamp = first_hour.timestamp() + h * 3600
            x = (stamp - t0.timestamp()) / 3600 * per_h
            if x < 0 or x > width:
                continue
            label = datetime.fromtimestamp(stamp, UTC).strftime("%H:%M")
            ticks.append(
                f"\\draw[vibeyline] ({x:.2f},{height - 0.2:.2f}) -- ({x:.2f},0.2) node[vibeynote,anchor=south] {{{label}}};"
            )
        day_marks = []
        day = t0.replace(hour=0, minute=0, second=0, microsecond=0)
        while day <= t_end:
            if day > t0:
                x = (day - t0).total_seconds() / 3600 * per_h
                day_marks.append(
                    f"\\draw[vibeydashed] ({x:.2f},{height - 0.3:.2f}) -- ({x:.2f},0.45) node[vibeynote,anchor=south,text=vibeygray] {{{day.strftime('%Y-%m-%d')} UTC}};"
                )
            day += timedelta(days=1)
        body = f"""\\begin{{tikzpicture}}[x=1cm,y=1cm]
\\begin{{scope}}[on background layer]
{chr(10).join(ticks)}
{chr(10).join(day_marks)}
\\end{{scope}}
{chr(10).join(lines)}
\\node[vibeynote,anchor=north west,align=left] at (0,{height - 0.55:.2f})
  {{one bar per logged start--end pair; time in UTC from {t0.strftime("%Y-%m-%d %H:%M")}; a lane started twice is drawn twice}};
\\end{{tikzpicture}}"""
        caption = (
            f"Lane starts and ends as the storm's progress log recorded them, over {span_h:.1f} hours from "
            f"{t0.strftime('%Y-%m-%d %H:%M')} UTC. One local model served every lane in turn, one instance per model; "
            f"the bars therefore never overlap in time, and the blank stretches are the reviewer's and the operator's, "
            f"not the machine's."
        )
        return self._fence("figure*", "fig:storm-timeline", caption, body)

    def bench_hosts(self) -> str:
        data = self._data("bench")
        turns, summaries = data["turns"], data["summaries"]
        palette = ["vibeyblue", "vibeyteal", "vibeygold", "vibeyviolet", "vibeyred", "vibeygreen"]
        tps_plots, wall_plots, legend = [], [], []
        for i, label in enumerate(sorted(turns)):
            rows = sorted(turns[label], key=lambda r: r["turn"])
            color = palette[i % len(palette)]
            if any((r.get("gen_tps") or 0) > 0 for r in rows):
                tps_plots.append(
                    f"\\addplot[{color},line width=.9pt,mark=*,mark size=1.1pt] coordinates {{"
                    + " ".join(f"({r['turn']},{r['gen_tps']})" for r in rows)
                    + "};\n\\addlegendentry{"
                    + _tex(label)
                    + "}"
                )
            wall_plots.append(
                f"\\addplot[{color},line width=.9pt,mark=*,mark size=1.1pt] coordinates {{"
                + " ".join(f"({r['turn']},{r['wall_s']})" for r in rows)
                + "};\n\\addlegendentry{"
                + _tex(label)
                + "}"
            )
            total = summaries.get(label, {}).get("total_wall_s")
            legend.append(f"{_tex(label)}: {total:.0f}\\,s" if total is not None else _tex(label))
        errors = "; ".join(f"{_tex(k)}: {_tex(', '.join(v))}" for k, v in data["errors"].items())
        body = f"""\\begin{{tikzpicture}}
\\begin{{groupplot}}[group style={{group size=2 by 1,horizontal sep=1.8cm}},vibeyaxis,width=8.6cm,height=4.8cm,
  xmin=0.5,xmax=10.5,xtick={{1,...,10}},xlabel={{turn of a ten-turn session}}]
\\nextgroupplot[title={{a. Generation speed as the context grows}},ylabel={{tokens / s}},ymin=0,legend pos=south west]
{chr(10).join(tps_plots)}
\\nextgroupplot[title={{b. Wall time per turn}},ylabel={{seconds}},ymin=0,legend pos=north west]
{chr(10).join(wall_plots)}
\\end{{groupplot}}
\\node[vibeynote,anchor=north west,align=left] at ([yshift=-0.85cm]group c1r1.south west)
  {{whole session: {"; ".join(legend)}. {errors}}};
\\end{{tikzpicture}}"""
        caption = (
            "The host benchmark of 2026-09-22: the same ten-turn session replayed against five server "
            "configurations on one 24\\,GB machine. (a) Generation speed falls as the context fills for every "
            "llama.cpp configuration of Qwen2.5-Coder-14B, whatever the slot count or cache type. (b) The gpt-oss:20b "
            "model on Ollama completed the session in a fraction of the wall time; the same model served by "
            "llama.cpp at a 64k context failed to load at all. Every point is one row of the tracked results file."
        )
        return self._fence("figure*", "fig:bench-hosts", caption, body)

    def host_context(self) -> str:
        data = self._data("bench")
        ctx, decision, sweep = data["context"], data["decision"], data["sweep"]
        scale = 7.0 / 131072
        marks = [
            ("p50", ctx["p50"]),
            ("p90", ctx["p90"]),
            ("p95", ctx["p95"]),
            ("p99", ctx["p99"]),
            ("max", ctx["max"]),
        ]
        mark_lines = []
        for i, (name, value) in enumerate(marks):
            x = value * scale
            up = 0.55 + (i % 2) * 0.32
            mark_lines.append(
                f"\\draw[vibeyink,line width=.6pt] ({x:.2f},0.12) -- ({x:.2f},{up:.2f}) node[vibeynote,anchor=south,text=vibeyink] {{{name}\\\\{_thousands(int(value))}}};"
            )
        windows = [
            (32768, "32k: truncates " + str(ctx["turns_over_32k"]) + " turns", "vibeyred"),
            (
                65536,
                "64k: chosen, " + _thousands(int(decision["headroom_tokens"])) + " headroom",
                "vibeygreen",
            ),
            (131072, "128k: baseline, never reached", "vibeygray"),
        ]
        window_lines = []
        for j, (tokens, label, color) in enumerate(windows):
            x = tokens * scale
            depth = 0.6 + 0.38 * (j % 2)
            window_lines.append(
                f"\\draw[{color},line width=.8pt,densely dashed] ({x:.2f},-0.15) -- ({x:.2f},-{depth:.2f}) node[vibeynote,anchor=north,text={color},align=center] {{{label}}};"
            )
        sweep_lines = []
        for k, row in enumerate(sweep):
            x = row["context"] * scale
            note = (
                f"{row['config']}: {row['wired_gb']}\\,GB wired, {row['tokens_per_second']} tok/s"
                + (f", {row['result']}" if row.get("result") else "")
            )
            sweep_lines.append(
                f"\\node[vibeypill,anchor=south] at ({x:.2f},{1.35 + (k % 2) * 0.28:.2f}) {{{note}}};"
            )
        tick_marks = " ".join(
            f"\\draw[vibeyink] ({t * scale:.2f},0) -- ({t * scale:.2f},-0.08);"
            for t in range(0, 131073, 16384)
        )
        body = f"""\\begin{{tikzpicture}}[x=1cm,y=1cm]
\\shade[left color=vibeyblue!18,right color=vibeyblue!4] (0,-0.12) rectangle (7.0,0.12);
\\draw[vibeyink,line width=.6pt] (0,0) -- (7.0,0);
{tick_marks}
\\node[vibeynote,anchor=north] at (0,-0.1) {{0}};
\\node[vibeynote,anchor=north east] at (7.0,-0.1) {{131,072 tokens}};
{chr(10).join(mark_lines)}
{chr(10).join(window_lines)}
{chr(10).join(sweep_lines)}
\\node[vibeyhead,anchor=south west] at (0,1.95) {{context actually used per turn, {ctx["turns"]} storm turns}};
\\end{{tikzpicture}}"""
        caption = (
            f"Fitting the model to the iron. The percentiles mark how much context {ctx['turns']} real storm turns used; "
            f"the dashed lines are the three context windows considered. A 32k window would have truncated "
            f"{ctx['turns_over_32k']} turns, and the 128k baseline, never reached by any turn, wired "
            f"{sweep[0]['wired_gb']}\\,GB of a 24\\,GB machine. The 64k window chosen covers every recorded turn with "
            f"a third again as headroom, and the sweep's pills report what each setting cost and delivered."
        )
        return self._fence("figure", "fig:host-context", caption, body)

    def commits_daily(self) -> str:
        data = self._data("commits")
        since, last = data["since"], data["last_day"]
        days = (last - since).days
        per_day = data["per_day"]
        coords = " ".join(f"({(d - since).days},{n})" for d, n in per_day.items())
        peak_day, peak = max(per_day.items(), key=lambda kv: kv[1])
        ticks, labels = [], []
        d = since
        while d <= last:
            ticks.append(str((d - since).days))
            labels.append(d.strftime("%b %-d"))
            d = date.fromordinal(d.toordinal() + 7)
        tag_marks = []
        by_day: dict[date, list[str]] = defaultdict(list)
        for tag in data["tags"]:
            if tag["package"] == "vibey" and tag["date"] >= since:
                by_day[tag["date"]].append(tag["name"].removeprefix("vibey-"))
        for day, names in sorted(by_day.items()):
            x = (day - since).days
            y = per_day.get(day, 0)
            tag_marks.append(
                f"\\node[vibeyanchor,fill=vibeygold] at (axis cs:{x},{y + 6}) {{}};\n"
                f"\\node[font=\\sffamily\\tiny,text=vibeygold,rotate=60,anchor=south west,inner sep=1pt] at (axis cs:{x},{y + 9}) {{{', '.join(names)}}};"
            )
        # the longest gap
        active = sorted(per_day)
        gap_len, gap_from, gap_to = 0, None, None
        for a, b in zip(active, active[1:], strict=False):
            if (b - a).days - 1 > gap_len:
                gap_len, gap_from, gap_to = (b - a).days - 1, a, b
        gap_note = ""
        if gap_from and gap_to and gap_len:
            x0, x1 = (gap_from - since).days + 1, (gap_to - since).days - 1
            gap_note = (
                f"\\draw[decorate,decoration={{brace,amplitude=3pt}},vibeygray] (axis cs:{x0},6) -- (axis cs:{x1},6);\n"
                f"\\node[vibeynote,anchor=south] at (axis cs:{(x0 + x1) / 2},10) {{{gap_len} days without a commit}};"
            )
        body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[vibeyaxis,width=17.2cm,height=5.6cm,ybar,bar width=4.2pt,xmin=-0.7,xmax={days + 0.7},ymin=0,ymax={peak + 40},
  xtick={{{",".join(ticks)}}},xticklabels={{{",".join(labels)}}},xlabel={{day ({since.year}, {data["head"][:8]} and earlier)}},ylabel={{commits}}]
\\addplot[fill=vibeyblue,draw=none] coordinates {{{coords}}};
{chr(10).join(tag_marks)}
{gap_note}
\\node[vibeycallout,anchor=east] at (axis cs:{(peak_day - since).days - 0.6},{peak - 6}) {{{peak} on {peak_day.strftime("%b %-d")}}};
\\node[vibeynote,anchor=north west,align=left] at (axis description cs:0.01,0.97) {{\\textcolor{{vibeygold}}{{$\\bullet$}} vibey release tag}};
\\end{{axis}}
\\end{{tikzpicture}}"""
        caption = (
            f"Commits per day since {since.isoformat()}, when the family's own development begins, read at "
            f"revision {data['head'][:8]}: {_thousands(data['window_commits'])} commits on {len(per_day)} active days, "
            f"with the busiest day at {peak}. Gold marks are the {sum(len(v) for v in by_day.values())} "
            f"\\texttt{{vibey}} release tags in the window; the brace marks the longest pause."
        )
        return self._fence("figure*", "fig:commits-daily", caption, body)

    def commit_rhythm(self) -> str:
        data = self._data("commits")
        hours = data["per_hour"]
        peak = max(hours)
        r_scale = 2.15 / peak
        sectors = []
        for h, n in enumerate(hours):
            a1 = 90 - h * 15
            a2 = a1 - 15
            r = n * r_scale
            color = (
                "vibeyblue!85"
                if n != peak and n != min(hours)
                else ("vibeygold" if n == peak else "vibeyred!70")
            )
            sectors.append(
                f"\\fill[{color},draw=white,line width=.4pt] (0,0) -- ({a1}:{r:.3f}) arc[start angle={a1},end angle={a2},radius={r:.3f}] -- cycle;"
            )
        rings = " ".join(
            f"\\draw[vibeyline] (0,0) circle ({v * r_scale:.3f});" for v in (25, 50, 75)
        )
        hour_labels = " ".join(
            f"\\node[vibeynote,text=vibeygray] at ({90 - h * 15 - 7.5}:2.42) {{{h}}};"
            for h in range(0, 24, 3)
        )
        weekdays = data["per_weekday"]
        names = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
        wd_coords = " ".join(f"({i},{n})" for i, n in enumerate(weekdays))
        types = list(data["types"].items())[:8]
        ty_coords = " ".join(f"({i},{n})" for i, (_, n) in enumerate(types))
        ty_labels = ",".join(_tex(t) for t, _ in types)
        busiest = hours.index(peak)
        quietest = hours.index(min(hours))
        body = f"""\\begin{{tikzpicture}}
\\begin{{scope}}[xshift=-5.4cm]
{rings}
{chr(10).join(sectors)}
{hour_labels}
\\node[vibeynote,anchor=south west,text=vibeygray] at (-2.6,2.45) {{commits by hour, US Eastern}};
\\node[vibeynote,anchor=north west,text=vibeygray,align=left] at (-2.6,-2.45) {{rings at 25, 50, 75 commits\\\\\\textcolor{{vibeygold}}{{$\\blacksquare$}} busiest {busiest:02d}:00 ({peak}) \\; \\textcolor{{vibeyred!70}}{{$\\blacksquare$}} quietest {quietest:02d}:00 ({min(hours)})}};
\\end{{scope}}
\\begin{{axis}}[vibeybars,at={{(0.0cm,-2.6cm)}},anchor=south west,width=5.3cm,height=5.2cm,bar width=9pt,xmin=-0.6,xmax=6.6,ymin=0,
  xtick={{0,...,6}},xticklabels={{{",".join(names)}}},title={{commits by weekday}},ylabel={{commits}}]
\\addplot[fill=vibeyblue,draw=none] coordinates {{{wd_coords}}};
\\end{{axis}}
\\begin{{axis}}[vibeybars,at={{(6.1cm,-2.6cm)}},anchor=south west,width=5.3cm,height=5.2cm,bar width=9pt,xmin=-0.6,xmax={len(types) - 0.4},ymin=0,
  xtick={{0,...,{len(types) - 1}}},xticklabels={{{ty_labels}}},x tick label style={{rotate=45,anchor=north east,font=\\sffamily\\tiny}},title={{Conventional Commit types}},ylabel={{commits}}]
\\addplot[fill=vibeyteal!85,draw=none] coordinates {{{ty_coords}}};
\\end{{axis}}
\\end{{tikzpicture}}"""
        caption = (
            f"The rhythm of production since {data['since'].isoformat()}, at revision {data['head'][:8]}. Left, a "
            f"24-hour clock of commits in US Eastern time: every hour of the day carries commits, the busiest at "
            f"{busiest:02d}:00 with {peak} and the quietest at {quietest:02d}:00 with {min(hours)}. Centre, the weekday "
            f"distribution. Right, the Conventional Commit types the pre-commit hook enforces, most common first."
        )
        return self._fence("figure*", "fig:commit-rhythm", caption, body)

    def cumulative_commits(self) -> str:
        data = self._data("commits")
        since, last = data["since"], data["last_day"]
        days = (last - since).days
        running, coords = 0, ["(0,0)"]
        per_day = data["per_day"]
        for i in range(days + 1):
            running += per_day.get(date.fromordinal(since.toordinal() + i), 0)
            coords.append(f"({i},{running})")
        pr_running, pr_coords = 0, ["(0,0)"]
        for i in range(days + 1):
            pr_running += data["pr_days"].get(date.fromordinal(since.toordinal() + i), 0)
            pr_coords.append(f"({i},{pr_running})")
        roots = []
        for root in data["roots"]:
            if root["date"] < since:
                continue
            x = (root["date"] - since).days
            roots.append(f"\\node[vibeyanchor,fill=vibeyviolet] at (axis cs:{x},0) {{}};")
        ticks, labels = [], []
        d = since
        while d <= last:
            ticks.append(str((d - since).days))
            labels.append(d.strftime("%b %-d"))
            d = date.fromordinal(d.toordinal() + 7)
        earlier = data["total_commits"] - data["window_commits"]
        body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[vibeyaxis,width=17.2cm,height=5.4cm,xmin=0,xmax={days},ymin=0,ymax={running + 80},
  xtick={{{",".join(ticks)}}},xticklabels={{{",".join(labels)}}},xlabel={{day}},ylabel={{cumulative}},legend pos=north west]
\\addplot[fill=vibeyblue!14,draw=vibeyblue,line width=1pt] coordinates {{{" ".join(coords)}}} \\closedcycle;
\\addlegendentry{{commits since {since.strftime("%b %-d")} ({_thousands(data["window_commits"])}; {earlier} earlier)}}
\\addplot[vibeyteal,line width=1pt] coordinates {{{" ".join(pr_coords)}}};
\\addlegendentry{{commit subjects closing a pull request ({pr_running})}}
{chr(10).join(roots)}
\\node[vibeynote,anchor=south east,align=right] at (axis description cs:0.99,0.04) {{\\textcolor{{vibeyviolet}}{{$\\bullet$}} a package's root commit: {len([r for r in data["roots"] if r["date"] >= since])} of {len(data["roots"])} root histories begin in the window}};
\\end{{axis}}
\\end{{tikzpicture}}"""
        caption = (
            f"Cumulative production at revision {data['head'][:8]}: commits since {since.isoformat()} and, beneath them, "
            f"the commits whose subject closes a pull request. The violet marks on the baseline are the days on which "
            f"the absorbed packages' own histories begin; the family was written as several repositories and merged "
            f"into one tree with every history preserved."
        )
        return self._fence("figure*", "fig:cumulative-commits", caption, body)

    def release_cadence(self) -> str:
        data = self._data("commits")
        tags = data["tags"]
        packages = [pkg for _, pkg in TAG_PACKAGES]
        lanes = [pkg for pkg in packages if any(t["package"] == pkg for t in tags)]
        first = min(t["date"] for t in tags)
        last = max(t["date"] for t in tags)
        span = max(1, (last - first).days)
        width = 15.4
        per_day = width / span
        row = 0.62
        lines = []
        colors = {
            "vibey": "vibeyblue",
            "claudeloop": "vibeyteal",
            "codexloop": "vibeygold",
            "agyloop": "vibeyviolet",
            "cursorloop": "vibeymint",
        }
        for i, pkg in enumerate(lanes):
            y = -i * row
            lines.append(f"\\draw[vibeyline,line width=.5pt] (0,{y:.2f}) -- ({width:.2f},{y:.2f});")
            lines.append(
                f"\\node[font=\\sffamily\\tiny\\bfseries,anchor=east,text=vibeyink] at (-0.15,{y:.2f}) {{{pkg}}};"
            )
            by_day: dict[date, list[str]] = defaultdict(list)
            for tag in [t for t in tags if t["package"] == pkg]:
                version = (
                    tag["name"].split("-v")[-1] if "-v" in tag["name"] else tag["name"].lstrip("v")
                )
                by_day[tag["date"]].append(version)
            last_x = -9.0
            lift = 0.0
            for day, versions in sorted(by_day.items()):
                x = (day - first).days * per_day
                lift = 0.42 if (x - last_x) < 1.1 and lift == 0.0 else 0.0
                last_x = x
                label = versions[0] if len(versions) == 1 else f"{versions[0]}--{versions[-1]}"
                lines.append(
                    f"\\node[vibeyanchor,fill={colors.get(pkg, 'vibeyink')}] at ({x:.2f},{y:.2f}) {{}};"
                )
                if len(versions) > 1:
                    lines.append(
                        f"\\node[font=\\sffamily\\tiny\\bfseries,text=white,fill={colors.get(pkg, 'vibeyink')},circle,inner sep=.6pt,anchor=north] at ({x:.2f},{y - 0.09:.2f}) {{{len(versions)}}};"
                    )
                if lift:
                    lines.append(
                        f"\\draw[vibeyline] ({x:.2f},{y + 0.06:.2f}) -- ({x:.2f},{y + 0.06 + lift:.2f});"
                    )
                lines.append(
                    f"\\node[font=\\sffamily\\tiny,text={colors.get(pkg, 'vibeyink')},rotate=55,anchor=south west,inner sep=1pt] at ({x + 0.02:.2f},{y + 0.06 + lift:.2f}) {{{label}}};"
                )
        height = -(len(lanes) - 1) * row
        month_marks = []
        d = date(first.year, first.month, 1)
        while d <= last:
            if d >= first:
                x = (d - first).days * per_day
                month_marks.append(
                    f"\\draw[vibeydashed] ({x:.2f},{height - 0.3:.2f}) -- ({x:.2f},0.35);\\node[vibeynote,anchor=north] at ({x:.2f},{height - 0.32:.2f}) {{{d.strftime('%b %Y')}}};"
                )
            d = date(d.year + (d.month // 12), d.month % 12 + 1, 1)
        for label, day in ((first.strftime("%b %-d"), first), (last.strftime("%b %-d"), last)):
            x = (day - first).days * per_day
            month_marks.append(
                f"\\node[vibeynote,anchor=north] at ({x:.2f},{height - 0.32:.2f}) {{{label}}};"
            )
        body = f"""\\begin{{tikzpicture}}[x=1cm,y=1cm]
{chr(10).join(month_marks)}
{chr(10).join(lines)}
\\end{{tikzpicture}}"""
        counts = Counter(t["package"] for t in tags)
        vibey_tags = [t for t in tags if t["package"] == "vibey"]
        caption = (
            f"Every release tag reachable at revision {data['head'][:8]}, one lane per package: "
            + ", ".join(f"{n} for {pkg}" for pkg, n in counts.most_common())
            + f". The {len(vibey_tags)} \\texttt{{vibey}} releases run from {vibey_tags[0]['name']} on "
            f"{vibey_tags[0]['date'].isoformat()} to {vibey_tags[-1]['name']} on {vibey_tags[-1]['date'].isoformat()}; "
            f"since the packages were absorbed into one tree, one version number ships the whole family."
        )
        return self._fence("figure*", "fig:release-cadence", caption, body)

    def codebase_shape(self) -> str:
        data = self._data("shape")
        packages = sorted(data["packages"], key=lambda p: p["lines"], reverse=True)
        n = len(packages)
        names = ",".join(p["package"] for p in packages)
        loc = " ".join(f"({p['lines']},{i})" for i, p in enumerate(packages))
        tests = " ".join(f"({p['tests']},{i})" for i, p in enumerate(packages))
        layers = data["layers"]
        layer_coords = " ".join(f"({layers[layer]},{i})" for i, layer in enumerate(LAYERS))
        floors = {"domain", "application", "infrastructure", "cli"}
        # Plot c prints no value beside its bars: the line count rides inside the pill that
        # names the layer's gate, so the two never collide however narrow the axis.
        floor_marks = " ".join(
            f"\\node[vibeypill,anchor=west,fill=vibeygreen!15,text=vibeygreen!60!black] at (axis cs:{layers[layer] + 900},{i}) {{{_thousands(layers[layer])} $\\cdot$ 100\\% branch floor}};"
            if layer in floors
            else f"\\node[vibeypill,anchor=west,fill=vibeysilver!30,text=vibeygray] at (axis cs:{layers[layer] + 900},{i}) {{{_thousands(layers[layer])} $\\cdot$ exempt}};"
            for i, layer in enumerate(LAYERS)
        )
        body = f"""\\begin{{tikzpicture}}
\\begin{{groupplot}}[group style={{group size=3 by 1,horizontal sep=1.9cm}},vibeyaxis,height=5.6cm,
  y dir=reverse,ytick={{0,...,{n - 1}}},ymin=-0.7,ymax={n - 0.3},xmin=0,y tick label style={{font=\\sffamily\\tiny}},
  scaled x ticks=false,x tick label style={{/pgf/number format/fixed,/pgf/number format/1000 sep={{{{,}}}}}},point meta=x,
  nodes near coords,every node near coord/.append style={{font=\\sffamily\\tiny,text=vibeygray,/pgf/number format/fixed,/pgf/number format/1000 sep={{{{,}}}}}}]
\\nextgroupplot[title={{a. Lines of Python per package}},xbar,bar width=6pt,width=5.9cm,yticklabels={{{names}}},xlabel={{lines}}]
\\addplot[fill=vibeyblue,draw=none] coordinates {{{loc}}};
\\nextgroupplot[title={{b. Test functions per package}},xbar,bar width=6pt,width=4.9cm,yticklabels={{,,,,,,,,,,,}},xlabel={{tests}}]
\\addplot[fill=vibeyteal!85,draw=none] coordinates {{{tests}}};
\\nextgroupplot[title={{c. The orchestrator's layers}},xbar,bar width=6pt,width=4.9cm,ytick={{0,...,{len(LAYERS) - 1}}},yticklabels={{{",".join(LAYERS)}}},ymin=-0.7,ymax={len(LAYERS) - 0.3},xlabel={{lines}},xmax={max(layers.values()) * 1.9:.0f},nodes near coords={{}}]
\\addplot[fill=vibeyviolet!85,draw=none] coordinates {{{layer_coords}}};
{floor_marks}
\\end{{groupplot}}
\\end{{tikzpicture}}"""
        caption = (
            f"The shape of the tree at revision {self._revision[:8]}: {_thousands(data['python_lines'])} lines of Python in "
            f"{_thousands(data['python_files'])} files and {_thousands(data['test_functions'])} test functions. "
            f"(a) Lines per package; (b) test functions per package, with {_thousands(data['root_tests'])} more in the "
            f"orchestrator's own top-level suite; (c) the orchestrator's layers, four of which fail the build below "
            f"100\\% branch coverage."
        )
        return self._fence("figure*", "fig:codebase-shape", caption, body)

    def forecast(self) -> str:
        records = self._data("forecast")["records"]
        n = len(records)
        ticks = ",".join(str(i) for i in range(1, n + 1))
        labels = ",".join(
            datetime.fromisoformat(r["recorded_at"].replace("Z", "+00:00")).strftime("%b %-d")
            for r in records
        )
        remaining = " ".join(f"({i},{r['remaining']:.0f})" for i, r in enumerate(records, 1))
        completed = " ".join(f"({i},{r['completed']:.0f})" for i, r in enumerate(records, 1))
        band = (
            " ".join(f"({i},{r['days_low']:.2f})" for i, r in enumerate(records, 1))
            + " "
            + " ".join(
                f"({i},{r['days_high']:.2f})" for i, r in reversed(list(enumerate(records, 1)))
            )
        )
        low = " ".join(f"({i},{r['days_low']:.2f})" for i, r in enumerate(records, 1))
        high = " ".join(f"({i},{r['days_high']:.2f})" for i, r in enumerate(records, 1))
        top = max(r["remaining"] for r in records)
        body = f"""\\begin{{tikzpicture}}
\\begin{{groupplot}}[group style={{group size=2 by 1,horizontal sep=1.7cm}},vibeyaxis,width=7.9cm,height=4.6cm,
  xmin=0.5,xmax={n + 0.5},xtick={{{ticks}}},xticklabels={{{labels}}},x tick label style={{rotate=30,anchor=north east}},xlabel={{forecast record}}]
\\nextgroupplot[title={{a. Work units in the tracker}},ylabel={{units}},ymin=0,ymax={top * 1.25:.0f},legend pos=north west]
\\addplot[vibeyred,line width=1pt,mark=*,mark size=1.3pt] coordinates {{{remaining}}};
\\addlegendentry{{remaining}}
\\addplot[vibeygreen,line width=1pt,mark=square*,mark size=1.2pt] coordinates {{{completed}}};
\\addlegendentry{{completed}}
\\nextgroupplot[title={{b. Forecast active days to completion}},ylabel={{active days}},ymin=0,legend pos=north west]
\\addplot[fill=vibeyblue!14,draw=none,forget plot] coordinates {{{band}}} -- cycle;
\\addplot[vibeyblue,line width=1pt,mark=*,mark size=1.2pt] coordinates {{{low}}};
\\addlegendentry{{$W/r_{{\\max}}$}}
\\addplot[vibeyblue!60,line width=1pt,mark=o,mark size=1.2pt] coordinates {{{high}}};
\\addlegendentry{{$W/r_{{\\min}}$}}
\\end{{groupplot}}
\\end{{tikzpicture}}"""
        last = records[-1]
        caption = (
            f"The delivery-estimate ledger, one forecast per record. (a) Remaining and completed work units as the tracker "
            f"held them: remaining jumped from {records[-3]['remaining']:.0f} to {records[-2]['remaining']:.0f} when the "
            f"storm filed its lanes as issues. (b) The zero-shortfall time to completion the forecast derives from the "
            f"observed merge rate, {last['days_low']:.0f}--{last['days_high']:.0f} active days at the last record, "
            f"with every material coordinate unmeasured and so at $\\phi_i = 1$."
        )
        return self._fence("figure*", "fig:forecast", caption, body)

    def governance_time(self) -> str:
        t = self._data("test_time")
        body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[vibeybars,width=8.6cm,height=4.8cm,bar width=11pt,xmin=-0.6,xmax=3.6,ymin=0,ymax={t["gates_before"] * 1.2:.0f},
  xtick={{0,1,2,3}},xticklabels={{four gates before,four gates after,suite before,suite after}},
  x tick label style={{font=\\sffamily\\tiny,align=center,text width=1.6cm}},ylabel={{seconds}},
  nodes near coords,every node near coord/.append style={{font=\\sffamily\\tiny,text=vibeygray}}]
\\addplot[fill=vibeyred!70,draw=none] coordinates {{(0,{t["gates_before"]})}};
\\addplot[fill=vibeygreen!80,draw=none] coordinates {{(1,{t["gates_after"]})}};
\\addplot[fill=vibeyred!70,draw=none] coordinates {{(2,{t["suite_before"]})}};
\\addplot[fill=vibeygreen!80,draw=none] coordinates {{(3,{t["suite_after"]})}};
\\node[vibeycallout,anchor=south] at (axis cs:1,{t["gates_after"] + t["gates_before"] * 0.09:.0f}) {{${t["gates_factor"]}\\times$ faster}};
\\node[vibeycallout,anchor=south] at (axis cs:3,{t["suite_after"] + t["gates_before"] * 0.09:.0f}) {{${t["suite_factor"]}\\times$ faster}};
\\end{{axis}}
\\end{{tikzpicture}}"""
        caption = (
            f"A governance dilation made smaller without lowering the bar. Computing the four per-layer coverage floors "
            f"from one instrumented run took the gates from about {_thousands(t['gates_before'])}\\,s to "
            f"{t['gates_after']}\\,s, and the suite itself from {t['suite_before']}\\,s to {t['suite_after']}\\,s, with no gate removed."
        )
        return self._fence("figure", "fig:governance-time", caption, body)

    def completion_band(self) -> str:
        summary = self._data("stress")["summary"]
        t0 = summary["t0_minutes"]
        lo, hi, serial = t0["lower"], t0["upper"], t0["serial"]
        scale = 7.6 / 300
        ticks = " ".join(
            f"\\draw[vibeyink] ({m * scale:.2f},0) -- ({m * scale:.2f},-0.08) node[vibeynote,anchor=north] {{{m}}};"
            for m in range(0, 301, 50)
        )
        body = f"""\\begin{{tikzpicture}}[x=1cm,y=1cm]
\\draw[vibeyink,line width=.6pt] (0,0) -- (7.8,0);
{ticks}
\\node[vibeynote,anchor=north] at (8.0,-0.08) {{min}};
\\shade[left color=vibeyblue!35,right color=vibeyblue!10] ({lo * scale:.2f},0.35) rectangle ({hi * scale:.2f},0.75);
\\draw[vibeyblue,line width=1pt] ({lo * scale:.2f},0.35) rectangle ({hi * scale:.2f},0.75);
\\node[vibeynote,text=vibeyblue,anchor=south] at ({(lo + hi) / 2 * scale:.2f},0.8) {{stable band: $T_0 \\in [{lo:.0f}, {hi:.0f}]$ min for $W = {t0["work_units"]:.0f}$}};
\\node[vibeynote,anchor=north] at ({lo * scale:.2f},0.3) {{{lo:.0f}}};
\\node[vibeynote,anchor=north] at ({hi * scale:.2f},0.3) {{{hi:.0f}}};
\\draw[vibeyred,line width=1.2pt] ({serial * scale:.2f},0.35) -- ({serial * scale:.2f},0.75);
\\node[vibeycallout,anchor=south,align=center] at ({serial * scale:.2f},0.8) {{serial substrate\\\\{serial:.0f} min}};
\\draw[vibeyarrow,draw=vibeygray] ({hi * scale + 0.1:.2f},1.55) -- ({serial * scale - 0.1:.2f},1.55) node[midway,vibeynote,anchor=south] {{every shortfall dilates $T_0$; none shortens it}};
\\end{{tikzpicture}}"""
        caption = (
            f"The completion-time prediction. At the stable band's rates, {t0['work_units']:.0f} units of the task class "
            f"take between {lo:.0f} and {hi:.0f} minutes on the fixed substrate with every coordinate at its target; "
            f"the serial rung alone would take about {serial:.0f}. Shortfalls in any material coordinate stretch the "
            f"interval to the right and never shorten it."
        )
        return self._fence("figure", "fig:completion-band", caption, body)

    # --- composition ---------------------------------------------------------------------

    def figures(self, skip: frozenset[str] = frozenset()) -> dict[str, str]:
        """Every generated figure by name, in the paper's order, except those in `skip`.

        Skipping is how a clone without the pinned history stays honest: the figures whose
        source it cannot read are left out and named, never computed over a partial log.
        """
        makers: dict[str, Callable[[], str]] = {
            "stress-dashboard": self.stress_dashboard,
            "stress-cumulative": self.stress_cumulative,
            "qwen-runs": self.qwen_runs,
            "storm-lanes": self.storm_lanes,
            "storm-timeline": self.storm_timeline,
            "bench-hosts": self.bench_hosts,
            "host-context": self.host_context,
            "commits-daily": self.commits_daily,
            "commit-rhythm": self.commit_rhythm,
            "cumulative-commits": self.cumulative_commits,
            "release-cadence": self.release_cadence,
            "codebase-shape": self.codebase_shape,
            "forecast": self.forecast,
            "governance-time": self.governance_time,
            "completion-band": self.completion_band,
        }
        return {name: make() for name, make in makers.items() if name not in skip}

    def block(self, name: str, body: str) -> str:
        return f"{self._begin(name)}\n{body}\n{self._end(name)}"

    def apply(self, markdown: str) -> str:
        figures = self.figures()
        seen: set[str] = set()

        def replace(match: re.Match[str]) -> str:
            name = match["name"]
            if name not in figures:
                raise ValueError(
                    f"docs/paper.md carries a generated block {name!r} this script does not know"
                )
            seen.add(name)
            return self.block(name, figures[name])

        result = _MARKER.sub(replace, markdown)
        missing = sorted(set(figures) - seen)
        if missing:
            raise ValueError("docs/paper.md has no marker pair for: " + ", ".join(missing))
        return self.renumber(result)

    def drift(self, markdown: str, skip: frozenset[str] = frozenset()) -> list[str]:
        figures = self.figures(skip)
        changed = []
        for match in _MARKER.finditer(markdown):
            name = match["name"]
            if name in skip:
                continue
            wanted = figures.get(name)
            if wanted is None or match.group(0) != self.block(name, wanted):
                changed.append(name)
        present = {m["name"] for m in _MARKER.finditer(markdown)}
        changed.extend(sorted(set(figures) - present))
        if self.renumber(markdown) != markdown:
            changed.append("figure-references")
        return changed

    @staticmethod
    def figure_numbers(markdown: str) -> dict[str, int]:
        """Each figure label with the number the PDF prints, in order of appearance."""
        numbers: dict[str, int] = {}
        for fence in _FENCE.finditer(markdown):
            if "\\begin{figure" not in fence.group(1):
                continue
            label = _LABEL.search(fence.group(1))
            if label and label.group(1) not in numbers:
                numbers[label.group(1)] = len(numbers) + 1
        return numbers

    @classmethod
    def renumber(cls, markdown: str) -> str:
        """`markdown` with every `[Fig. N](#fig:label)` carrying the figure's actual number.

        The digits in the source are for the reader of the Markdown; the PDF numbers the
        figure itself and the site recomputes the number at build time. Keeping the source
        right is toil, so it is automated here and checked with the figures.
        """
        numbers = cls.figure_numbers(markdown)
        return _REF.sub(
            lambda m: (
                f"[Fig. {numbers[m.group(1)]}](#{m.group(1)})"
                if m.group(1) in numbers
                else m.group(0)
            ),
            markdown,
        )


def revisions_in(markdown: str) -> set[str]:
    """Every revision the paper's generated blocks were computed at."""
    return {m["rev"] for m in _MARKER.finditer(markdown)}


def build_atlas(repo: Path, revision: str) -> PaperFigureAtlas:
    storm_dir = repo / DEFAULT_STORM_DIR
    stress_path = repo / DEFAULT_STRESS_RECORD
    return PaperFigureAtlas(
        revision=revision,
        stress=StressTable(stress_path, StressRecord(stress_path)),
        qwen=QwenRuns(repo / DEFAULT_QWEN_STORM_RECORD),
        storm=StormLedger(storm_dir),
        bench=HostBench(storm_dir),
        forecast=DeliveryForecast(repo / DEFAULT_FORECAST_LEDGER),
        test_time=TestTimeEvidence(repo / DEFAULT_TEST_TIME_RECORD),
        commits=CommitSeries(repo, revision),
        shape=CodebaseShape(repo, revision),
    )


# The figures whose only source is the git log; a shallow clone cannot recompute them.
HISTORY_FIGURES: frozenset[str] = frozenset(
    {"commits-daily", "commit-rhythm", "cumulative-commits", "release-cadence", "codebase-shape"}
)


def _is_shallow(repo: Path) -> bool:
    done = subprocess.run(
        ["git", "rev-parse", "--is-shallow-repository"],
        cwd=repo,
        capture_output=True,
        text=True,
        check=False,
    )
    return done.stdout.strip() == "true"


# A bare function because it is this script's `__main__` entry point (ADR-0016): it parses
# flags, builds the atlas and either rewrites, checks or emits.
def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--repo", type=Path, default=Path("."))
    parser.add_argument("--paper", default=DEFAULT_PAPER, help="relative to --repo")
    parser.add_argument(
        "--rev",
        default=None,
        help="the revision to pin the history figures at (default: the paper's markers, else HEAD)",
    )
    parser.add_argument(
        "--check", action="store_true", help="exit 1 if regeneration would change any block"
    )
    parser.add_argument(
        "--emit", type=Path, default=None, help="write one .tex spec per figure into this directory"
    )
    args = parser.parse_args(argv)

    paper_path = args.repo / args.paper
    markdown = paper_path.read_text(encoding="utf-8")
    pinned = revisions_in(markdown)
    revision = args.rev or (next(iter(pinned)) if len(pinned) == 1 else None)
    if revision is None:
        revision = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=args.repo, check=True, capture_output=True, text=True
        ).stdout.strip()
    revision = subprocess.run(
        ["git", "rev-parse", revision], cwd=args.repo, check=True, capture_output=True, text=True
    ).stdout.strip()

    # A shallow clone has no log to recompute the history figures from: the check covers
    # the rest and says which figures it could not check, rather than failing on a source
    # it cannot read or passing over one it never looked at.
    skipped = HISTORY_FIGURES if args.check and _is_shallow(args.repo) else frozenset()
    if skipped:
        print(
            f"{SCRIPT}: shallow clone; not checked here, they need the full history: "
            + ", ".join(sorted(skipped))
        )
    atlas = build_atlas(args.repo, revision)

    if args.emit is not None:
        args.emit.mkdir(parents=True, exist_ok=True)
        for name, block in atlas.figures().items():
            env_match = re.search(r"\\begin\{(figure\*?)\}", block)
            label = re.search(r"\\label\{([^}]+)\}", block)
            caption = re.search(r"\\caption\{(.*)\}\n\\label", block, re.DOTALL)
            tikz = re.search(r"(\\begin\{tikzpicture\}.*\\end\{tikzpicture\})", block, re.DOTALL)
            spec = "\n".join(
                [
                    f"% label: {label.group(1) if label else name}",
                    f"% wide: {'true' if env_match and env_match.group(1) == 'figure*' else 'false'}",
                    "% caption: " + (caption.group(1).replace("\n", " ") if caption else ""),
                    tikz.group(1) if tikz else block,
                    "",
                ]
            )
            (args.emit / f"{name}.tex").write_text(spec, encoding="utf-8")
        print(f"emitted {len(atlas.figures())} figure specs into {args.emit}")
        return 0

    if args.check:
        changed = atlas.drift(markdown, skipped)
        if changed:
            print(
                f"{SCRIPT}: these generated figures are out of date: {', '.join(changed)}",
                file=sys.stderr,
            )
            return 1
        checked = "every generated figure" if not skipped else "every checkable figure"
        print(f"{SCRIPT}: {checked} matches its sources at {revision[:12]}")
        return 0

    paper_path.write_text(atlas.apply(markdown), encoding="utf-8")
    print(
        f"{SCRIPT}: regenerated {len(atlas.figures())} figures at {revision[:12]} into {paper_path}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
