# Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
"""Binaries of every user interface, for every supported platform, on every GitHub Release.

    python scripts/release_binaries.py context                 # the release's tag, branch, workflow
    python scripts/release_binaries.py plan --mode M --target SHA [--github-output F]
    python scripts/release_binaries.py check                   # exit 1 when anything drifted
    python scripts/release_binaries.py render                  # rewrite the downloads table
    python scripts/release_binaries.py flatpak-manifest --manifest M --module X --source D --out F
    python scripts/release_binaries.py pypi-fetch --project P --version V --out D
    python scripts/release_binaries.py collect --dir D --expected JSON --optional JSON

`scripts/release_binaries.toml` declares every target: one user interface on one platform,
and whether it is built on every release, is built only while a credential is set (a
release without it says so and keeps one tracking issue open), or is not supported (with
the reason). `.github/workflows/release-binaries.yml` runs
after every successful `Release` on main; its `plan` job asks this script for the matrix,
so the workflow builds what the configuration declares and nothing it does not. `check`
holds the two together in the other direction too -- every declared builder has its job,
every job is a declared builder or one of the workflow's own -- and holds the downloads
page to the configuration (sub-doctrine 12.e: the check that says out loud when the step
was missed). CI runs it from tests/meta/test_release_binaries.py.

Nothing here reimplements what the family already does (sub-doctrine 10.e): the release's
tag, its branch and the name of the workflow it follows are read through vibey-gh's own
configuration loader and version reader, exactly as `vibey-gh github-release` computes the
tag it creates; the Linux architectures and their runners are read from the requirements
matrix (`scripts/minimum_specs.toml`), the one place the supported set is declared.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import time
import tomllib
import urllib.request
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

try:
    from scripts.interfaces.release_binaries_interface import (
        DownloadsRendererInterface,
        HttpFetcherInterface,
        MatrixPlannerInterface,
        PypiFetcherInterface,
        TargetCatalogueInterface,
        WorkflowCheckerInterface,
    )
except ModuleNotFoundError:  # Direct execution keeps the script directory on sys.path.
    from interfaces.release_binaries_interface import (  # type: ignore[import-not-found,no-redef]
        DownloadsRendererInterface,
        HttpFetcherInterface,
        MatrixPlannerInterface,
        PypiFetcherInterface,
        TargetCatalogueInterface,
        WorkflowCheckerInterface,
    )

SCRIPT = "scripts/release_binaries.py"
#: Where this script finds its own configuration: the one location derived rather than
#: declared, because a tool must find its configuration before it can read anything out of
#: it (sub-doctrine 12.h states this exception and forbids widening it).
DEFAULT_CONFIG = Path(__file__).resolve().with_suffix(".toml")
REPO = Path(__file__).resolve().parents[1]
STATUSES = ("build", "credential", "unsupported")
SIGNING = {
    "unsigned": "Unsigned",
    "debug-key": "Android debug key: sideload only, not a store build",
    "pypi": "The bytes PyPI serves, SHA-256 checked against PyPI",
    "apple-ad-hoc": "Ad-hoc signed, not notarised: macOS asks you to confirm the first launch",
    "apple-app-store": (
        "Apple Distribution certificate and an App Store profile: it installs through "
        "TestFlight or the App Store, not by opening the file"
    ),
}
MODES = ("publish", "dry-run", "skip")
BEGIN = "<!-- BEGIN GENERATED release:downloads — regenerated by scripts/release_binaries.py -->"
END = "<!-- END GENERATED release:downloads -->"
#: What a file name shows in place of a version on the downloads page. The page states the
#: names a release produces, not one release's numbers, so bumping a version never drifts it.
VERSION_PLACEHOLDER = "<version>"


class ReleaseBinariesError(RuntimeError):
    """A declaration, a workflow or a fetched file that is not what it must be."""


# ------------------------------------------------------------------------ settings


@dataclass(frozen=True)
class Settings:
    """`[release_binaries]` from the TOML, with every path resolved against the repository."""

    root: Path
    workflow: Path
    downloads_page: Path
    gh_config: Path
    linux_arches_source: Path
    linux_arches_table: str
    checksums_asset: str
    infrastructure_jobs: tuple[str, ...]
    release_wait_s: int
    poll_s: int
    pypi_wait_s: int
    pypi_json_url: str
    uis: Mapping[str, Mapping[str, Any]]
    targets: tuple[Mapping[str, Any], ...]

    @classmethod
    def load(cls, path: Path = DEFAULT_CONFIG, root: Path = REPO) -> Settings:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
        section = data.get("release_binaries")
        if not isinstance(section, dict):
            raise ReleaseBinariesError(f"{path} declares no [release_binaries] table")
        try:
            return cls(
                root=root,
                workflow=root / section["workflow"],
                downloads_page=root / section["downloads_page"],
                gh_config=root / section["gh_config"],
                linux_arches_source=root / section["linux_arches_source"],
                linux_arches_table=str(section["linux_arches_table"]),
                checksums_asset=str(section["checksums_asset"]),
                infrastructure_jobs=tuple(section["infrastructure_jobs"]),
                release_wait_s=int(section["release_wait_s"]),
                poll_s=int(section["poll_s"]),
                pypi_wait_s=int(section["pypi_wait_s"]),
                pypi_json_url=str(section["pypi_json_url"]),
                uis=dict(section["uis"]),
                targets=tuple(section["targets"]),
            )
        except KeyError as missing:
            raise ReleaseBinariesError(f"{path}: [release_binaries] lacks {missing}") from None


# ------------------------------------------------------------------------- targets


@dataclass(frozen=True)
class Target:
    """One user interface on one platform (and one architecture, where that matters)."""

    id: str
    ui: str
    ui_name: str
    builder: str
    status: str
    platform: str
    arch: str
    runner: str
    version: str
    assets: tuple[str, ...]
    #: The asset names with the version left as a placeholder: what the downloads page shows.
    asset_patterns: tuple[str, ...]
    signing: str
    install: str = ""
    note: str = ""
    reason: str = ""
    needs: str = ""
    credentials: tuple[str, ...] = ()
    tracking_key: str = ""
    #: A built target whose signing a credential would raise: what it reads, and the issue
    #: the release keeps open while any of it is missing.
    signing_credentials: tuple[str, ...] = ()
    signing_tracking_key: str = ""
    signing_needs: str = ""
    with_: Mapping[str, Any] = field(default_factory=dict)

    def row(self) -> dict[str, Any]:
        """The builder's matrix row: what its job reads as `matrix.*`."""
        row: dict[str, Any] = {
            "id": self.id,
            "runner": self.runner,
            "arch": self.arch,
            "version": self.version,
            "assets": " ".join(self.assets),
            "artifact": f"release-binary-{self.id}",
        }
        if self.status == "credential":
            row["tracking_key"] = self.tracking_key
            row["credentials"] = " ".join(self.credentials)
            row["needs"] = self.needs
        if self.signing_credentials:
            row["signing_tracking_key"] = self.signing_tracking_key
            row["signing_credentials"] = " ".join(self.signing_credentials)
            row["signing_needs"] = self.signing_needs
        row.update(self.with_)
        return row


class VersionReader:
    """Reads one interface's version: the first group of a pattern in a declared file."""

    def __init__(self, root: Path) -> None:
        self._root = root

    def read(self, ui: str, declaration: Mapping[str, Any]) -> str:
        path = self._root / str(declaration["version_file"])
        match = re.search(str(declaration["version_pattern"]), path.read_text(encoding="utf-8"))
        if match is None:
            raise ReleaseBinariesError(
                f"[release_binaries.uis.{ui}]: no version matches its pattern in {path}"
            )
        return match.group(1)


class LinuxArches:
    """The supported Linux architectures and the native runner of each, read from the
    requirements matrix: the one place the supported set is declared."""

    def __init__(self, source: Path, table: str) -> None:
        self._source = source
        self._table = table

    def runners(self) -> dict[str, str]:
        node: Any = tomllib.loads(self._source.read_text(encoding="utf-8"))
        for key in self._table.split("."):
            if not isinstance(node, dict) or key not in node:
                raise ReleaseBinariesError(f"{self._source} has no [{self._table}] table")
            node = node[key]
        if not isinstance(node, dict) or not node:
            raise ReleaseBinariesError(f"[{self._table}] in {self._source} declares no arch")
        return {str(arch): str(spec["runner"]) for arch, spec in node.items()}


class TargetCatalogue(TargetCatalogueInterface):
    """Implements `TargetCatalogueInterface` over `[release_binaries]`."""

    def __init__(
        self,
        settings: Settings,
        versions: VersionReader | None = None,
        arches: LinuxArches | None = None,
    ) -> None:
        self._settings = settings
        self._versions = versions or VersionReader(settings.root)
        self._arches = arches or LinuxArches(
            settings.linux_arches_source, settings.linux_arches_table
        )
        self._targets: list[Target] | None = None

    def targets(self) -> list[Target]:
        if self._targets is None:
            self._targets = self._expand()
        return list(self._targets)

    def builders(self) -> list[str]:
        seen: list[str] = []
        for target in self.targets():
            if target.status != "unsupported" and target.builder not in seen:
                seen.append(target.builder)
        return seen

    def _expand(self) -> list[Target]:
        found: list[Target] = []
        versions: dict[str, str] = {}
        for index, spec in enumerate(self._settings.targets):
            where = f"[[release_binaries.targets]] #{index + 1}"
            ui = str(spec.get("ui", ""))
            if ui not in self._settings.uis:
                raise ReleaseBinariesError(f"{where}: ui {ui!r} is not a [release_binaries.uis]")
            status = str(spec.get("status", ""))
            if status not in STATUSES:
                raise ReleaseBinariesError(f"{where}: status must be one of {STATUSES}")
            signing = str(spec.get("signing", ""))
            if signing not in SIGNING:
                raise ReleaseBinariesError(f"{where}: signing must be one of {tuple(SIGNING)}")
            self._require(where, spec, status)
            if ui not in versions:
                versions[ui] = self._versions.read(ui, self._settings.uis[ui])
            if spec.get("per_linux_arch", False):
                cells = list(self._arches.runners().items())
            else:
                cells = [(str(spec.get("arch", "any")), str(spec.get("runner", "")))]
            for arch, runner in cells:
                found.append(self._target(spec, ui, status, signing, arch, runner, versions[ui]))
        ids = [target.id for target in found]
        duplicates = sorted({one for one in ids if ids.count(one) > 1})
        if duplicates:
            raise ReleaseBinariesError(f"target ids declared twice: {', '.join(duplicates)}")
        assets = [asset for target in found for asset in target.assets]
        clashes = sorted({one for one in assets if assets.count(one) > 1})
        if clashes:
            raise ReleaseBinariesError(f"asset names produced twice: {', '.join(clashes)}")
        return found

    @staticmethod
    def _require(where: str, spec: Mapping[str, Any], status: str) -> None:
        needed = {
            "build": ("id", "builder", "platform", "assets"),
            "credential": ("id", "builder", "platform", "assets", "credentials", "tracking_key"),
            "unsupported": ("id", "builder", "platform", "reason"),
        }[status]
        missing = [key for key in needed if not spec.get(key)]
        if status == "credential" and not spec.get("needs"):
            missing.append("needs")
        if status != "unsupported" and not spec.get("per_linux_arch") and not spec.get("runner"):
            missing.append("runner (or per_linux_arch)")
        if spec.get("signing_credentials"):
            if status != "build":
                missing.append("status = build (only a built target has signing to raise)")
            missing += [
                key for key in ("signing_tracking_key", "signing_needs") if not spec.get(key)
            ]
        if missing:
            raise ReleaseBinariesError(f"{where} ({status}) lacks {', '.join(missing)}")

    def _target(
        self,
        spec: Mapping[str, Any],
        ui: str,
        status: str,
        signing: str,
        arch: str,
        runner: str,
        version: str,
    ) -> Target:
        def fill(text: str, shown: str) -> str:
            return text.replace("{arch}", arch).replace("{version}", shown)

        patterns = tuple(str(asset) for asset in spec.get("assets", []))
        return Target(
            id=fill(str(spec["id"]), version),
            ui=ui,
            ui_name=str(self._settings.uis[ui]["name"]),
            builder=str(spec["builder"]),
            status=status,
            platform=str(spec["platform"]),
            arch=arch,
            runner=runner,
            version=version,
            assets=tuple(fill(asset, version) for asset in patterns),
            asset_patterns=tuple(fill(asset, VERSION_PLACEHOLDER) for asset in patterns),
            signing=signing,
            install=fill(str(spec.get("install", "")), VERSION_PLACEHOLDER),
            note=str(spec.get("note", "")),
            reason=str(spec.get("reason", "")),
            needs=str(spec.get("needs", "")),
            credentials=tuple(str(one) for one in spec.get("credentials", [])),
            tracking_key=str(spec.get("tracking_key", "")),
            signing_credentials=tuple(str(one) for one in spec.get("signing_credentials", [])),
            signing_tracking_key=str(spec.get("signing_tracking_key", "")),
            signing_needs=str(spec.get("signing_needs", "")),
            with_=dict(spec.get("with", {})),
        )


# ------------------------------------------------------------------------- release


@dataclass(frozen=True)
class ReleaseContext:
    """The tag the release's GitHub Release carries, its branch, and the workflow it follows."""

    tag: str
    release_branch: str
    release_workflow: str

    @classmethod
    def read(cls, settings: Settings) -> ReleaseContext:
        # Imported here, not at the top: every other command runs on a bare interpreter in
        # the workflow (collect, pypi-fetch, flatpak-manifest), and only this one needs the
        # tree's own vibey-gh installed -- the plan job installs it, as openvsx.yml does.
        from vibey_gh.config import load_config
        from vibey_gh.versioning import read_version

        cfg = load_config(settings.root, settings.gh_config)
        return cls(
            tag=f"{cfg.github_release.tag_prefix}{read_version(cfg)}",
            release_branch=cfg.release_branch,
            release_workflow=cfg.workflow_names.release,
        )


class MatrixPlanner(MatrixPlannerInterface):
    """Implements `MatrixPlannerInterface`: one matrix per builder, from the catalogue."""

    def __init__(self, catalogue: TargetCatalogueInterface, settings: Settings) -> None:
        self._catalogue = catalogue
        self._settings = settings

    def plan(self, *, mode: str, target: str, tag: str) -> dict[str, Any]:
        if mode not in MODES:
            raise ReleaseBinariesError(f"mode must be one of {MODES}, not {mode!r}")
        targets: list[Target] = list(self._catalogue.targets())
        builders: dict[str, dict[str, list[dict[str, Any]]]] = {}
        for builder in self._catalogue.builders():
            rows = [t.row() for t in targets if t.builder == builder and t.status != "unsupported"]
            builders[builder] = {"include": rows}
        return {
            "mode": mode,
            "target": target,
            "tag": tag,
            "expected": [a for t in targets if t.status == "build" for a in t.assets],
            "optional": [a for t in targets if t.status == "credential" for a in t.assets],
            "checksums": self._settings.checksums_asset,
            "release_wait_s": self._settings.release_wait_s,
            "poll_s": self._settings.poll_s,
            "builders": builders,
        }

    @staticmethod
    def github_output(plan: Mapping[str, Any]) -> str:
        """The plan as `key=value` lines for `$GITHUB_OUTPUT`: one per builder, as JSON."""
        lines = [
            f"mode={plan['mode']}",
            f"target={plan['target']}",
            f"tag={plan['tag']}",
            f"expected={json.dumps(plan['expected'], separators=(',', ':'))}",
            f"optional={json.dumps(plan['optional'], separators=(',', ':'))}",
            f"checksums={plan['checksums']}",
            f"release_wait_s={plan['release_wait_s']}",
            f"poll_s={plan['poll_s']}",
        ]
        for builder, matrix in plan["builders"].items():
            lines.append(f"{builder}={json.dumps(matrix, separators=(',', ':'))}")
        return "\n".join(lines) + "\n"


# ------------------------------------------------------------------------- the check


class WorkflowChecker(WorkflowCheckerInterface):
    """Implements `WorkflowCheckerInterface`: the workflow builds exactly what is declared."""

    def __init__(
        self,
        catalogue: TargetCatalogueInterface,
        settings: Settings,
        context: ReleaseContext,
    ) -> None:
        self._catalogue = catalogue
        self._settings = settings
        self._context = context

    def problems(self, workflow: Mapping[Any, Any]) -> list[str]:
        found: list[str] = []
        jobs: Mapping[str, Any] = workflow.get("jobs") or {}
        builders = list(self._catalogue.builders())
        infrastructure = list(self._settings.infrastructure_jobs)
        found += self._trigger(workflow)
        for job in infrastructure:
            if job not in jobs:
                found.append(f"the workflow has no `{job}` job")
        unsupported = {
            t.builder for t in self._catalogue.targets() if t.status == "unsupported"
        } - set(builders)
        for job in jobs:
            if job not in builders and job not in infrastructure and job not in unsupported:
                found.append(
                    f"job `{job}` builds nothing scripts/release_binaries.toml declares "
                    "(declare its targets, or remove the job)"
                )
        plan_outputs = (jobs.get("plan") or {}).get("outputs") or {}
        for builder in builders:
            spec = jobs.get(builder)
            if spec is None:
                found.append(f"builder `{builder}` is declared but the workflow has no job for it")
                continue
            found += self._builder(builder, spec, plan_outputs)
        for builder in sorted(unsupported & set(jobs)):
            found.append(f"job `{builder}` builds a target declared unsupported")
        collect = jobs.get("collect") or {}
        waits = set(self._needs(collect))
        missing = [builder for builder in builders if builder not in waits]
        if collect and missing:
            found.append(f"`collect` does not wait for: {', '.join(missing)}")
        return found

    def _trigger(self, workflow: Mapping[Any, Any]) -> list[str]:
        on = workflow.get("on", workflow.get(True)) or {}
        expected = {
            "workflows": [self._context.release_workflow],
            "types": ["completed"],
            "branches": [self._context.release_branch],
        }
        if not isinstance(on, dict) or on.get("workflow_run") != expected:
            return [
                f"the workflow must follow a completed `{self._context.release_workflow}` run on "
                f"`{self._context.release_branch}` (on.workflow_run == {expected})"
            ]
        return []

    @staticmethod
    def _needs(job: Mapping[str, Any]) -> list[str]:
        needs = job.get("needs") or []
        return [needs] if isinstance(needs, str) else list(needs)

    def _builder(
        self, builder: str, job: Mapping[str, Any], plan_outputs: Mapping[str, Any]
    ) -> list[str]:
        found: list[str] = []
        output = f"${{{{ steps.plan.outputs.{builder} }}}}"
        if plan_outputs.get(builder) != output:
            found.append(f"the `plan` job must declare output `{builder}: {output}`")
        if "plan" not in self._needs(job):
            found.append(f"job `{builder}` must need `plan`")
        matrix = (job.get("strategy") or {}).get("matrix")
        expected = f"${{{{ fromJSON(needs.plan.outputs.{builder}) }}}}"
        if matrix != expected:
            found.append(f"job `{builder}`'s matrix must be `{expected}`, not {matrix!r}")
        if job.get("runs-on") != "${{ matrix.runner }}":
            found.append(f"job `{builder}` must run on `${{{{ matrix.runner }}}}`")
        text = json.dumps(job)
        for target in self._catalogue.targets():
            if target.builder != builder:
                continue
            if target.status == "credential":
                found += self._tracked(builder, text, target.credentials, "matrix.tracking_key")
            if target.signing_credentials:
                found += self._tracked(
                    builder, text, target.signing_credentials, "matrix.signing_tracking_key"
                )
        return sorted(set(found), key=found.index)

    @staticmethod
    def _tracked(builder: str, text: str, secrets: Sequence[str], key: str) -> list[str]:
        """A credential the repository may lack: read, said out loud, tracked by one issue."""
        found: list[str] = []
        for secret in secrets:
            if f"secrets.{secret}" not in text:
                found.append(f"job `{builder}` never reads the credential `{secret}`")
        for verb in ("raise", "resolve"):
            if f"vibey-gh tracking-issue {verb}" not in text:
                found.append(
                    f"job `{builder}` waits for a credential but never runs "
                    f"`vibey-gh tracking-issue {verb}`"
                )
        if key not in text:
            found.append(
                f"job `{builder}` must key its tracking issue on the target's key (`{key}`)"
            )
        return found


# ------------------------------------------------------------------------ the page


class DownloadsRenderer(DownloadsRendererInterface):
    """Implements `DownloadsRendererInterface`: the catalogue as the downloads page's table."""

    def __init__(self, catalogue: TargetCatalogueInterface, settings: Settings) -> None:
        self._catalogue = catalogue
        self._settings = settings

    @staticmethod
    def _credentials(target: Target) -> str:
        """`A` is / `A` and `B` are: the credentials a target is built under, named."""
        names = [f"`{name}`" for name in target.credentials]
        joined = names[0] if len(names) == 1 else ", ".join(names[:-1]) + " and " + names[-1]
        return f"{joined} {'is' if len(names) == 1 else 'are'} set"

    def render(self) -> str:
        targets: list[Target] = list(self._catalogue.targets())
        built = [t for t in targets if t.status == "build"]
        # A target waiting for a credential is built by any release run while the credential
        # is set, so it is listed with the rest; the page cannot know whether the secret is set
        # today, so it says on what the file depends, never that it is or is not built.
        waiting = [t for t in targets if t.status == "credential"]
        listed = [t for t in targets if t.status in ("build", "credential")]
        lines = [
            f"*Generated from [`scripts/release_binaries.toml`]"
            f"(https://github.com/the-vibey-project/vibey/blob/develop/scripts/release_binaries.toml) "
            f"by `{SCRIPT} render`; do not edit inside these markers. `{VERSION_PLACEHOLDER}` "
            "is each interface's own version.*",
            "",
            "| Interface | Platform | Architecture | File | Signing |",
            "|---|---|---|---|---|",
        ]
        for t in listed:
            files = "<br>".join(f"`{asset}`" for asset in t.asset_patterns)
            signing = SIGNING[t.signing]
            if t.status == "credential":
                signing += f" (built only while {self._credentials(t)})"
            lines.append(f"| {t.ui_name} | {t.platform} | {t.arch} | {files} | {signing} |")
        lines += [
            "",
            f"Every file is listed in `{self._settings.checksums_asset}` beside it, with its "
            "SHA-256, and carries a GitHub build-provenance attestation.",
            "",
            "### Installing each",
            "",
        ]
        for t in listed:
            if t.status == "credential" and not t.note:
                continue
            title = f"**{t.ui_name}, {t.platform}" + (f", {t.arch}**" if t.arch != "any" else "**")
            lines.append(f"- {title}: {t.note}" + (f" `{t.install}`" if t.install else ""))
        raised: dict[str, Target] = {}
        for t in built:
            if t.signing_credentials:
                raised.setdefault(t.signing_tracking_key, t)
        if raised:
            lines += ["", "### Signing that waits for a credential", ""]
            for t in raised.values():
                lines.append(
                    f"- **{t.ui_name}, {t.platform}**: built and attached on every release, "
                    f"{SIGNING[t.signing][0].lower()}{SIGNING[t.signing][1:]}. {t.signing_needs} "
                    f"The release workflow keeps one tracking issue open until they are set "
                    f"(`{t.signing_tracking_key}`)."
                )
        if waiting:
            lines += ["", "### Built only while a credential is set", ""]
            for t in waiting:
                lines.append(
                    f"- **{t.ui_name}, {t.platform}**: built and attached by a release only "
                    f"while {self._credentials(t)}. {t.needs} Without it nothing is built for "
                    f"this target, the release says so and keeps one tracking issue open "
                    f"(`{t.tracking_key}`), and the release itself is unaffected."
                )
        unsupported = [t for t in targets if t.status == "unsupported"]
        if unsupported:
            lines += ["", "### Not supported", ""]
            for t in unsupported:
                lines.append(f"- **{t.ui_name}, {t.platform}**: {t.reason}")
        return "\n".join(lines)

    def apply(self, text: str) -> str:
        """`text` with its GENERATED block replaced by a fresh render."""
        if text.count(BEGIN) != 1 or text.count(END) != 1:
            raise ReleaseBinariesError(
                f"{self._settings.downloads_page} must carry exactly one GENERATED "
                "release:downloads block"
            )
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return f"{head}{BEGIN}\n{self.render()}\n{END}{tail}"


# -------------------------------------------------------------------------- PyPI


class UrllibFetcher(HttpFetcherInterface):
    """Implements `HttpFetcherInterface` with the standard library."""

    def __init__(self, timeout_s: float = 120.0) -> None:
        self._timeout = timeout_s

    def get(self, url: str) -> bytes:
        if not url.startswith("https://"):
            raise ReleaseBinariesError(f"refusing a non-HTTPS URL: {url}")
        with urllib.request.urlopen(url, timeout=self._timeout) as response:  # noqa: S310
            body: bytes = response.read()
            return body


class PypiFetcher(PypiFetcherInterface):
    """Implements `PypiFetcherInterface` over PyPI's JSON API, waiting for a late upload."""

    def __init__(
        self,
        http: HttpFetcherInterface,
        url_template: str,
        *,
        wait_s: int,
        poll_s: int,
        sleep: Callable[[float], None] = time.sleep,
    ) -> None:
        self._http = http
        self._template = url_template
        self._wait_s = wait_s
        self._poll_s = poll_s
        self._sleep = sleep

    def fetch(self, project: str, version: str, out: Path) -> list[Path]:
        files = self._listing(project, version)
        out.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []
        for entry in files:
            name = str(entry["filename"])
            if "/" in name or name.startswith("."):
                raise ReleaseBinariesError(f"PyPI listed an unsafe file name: {name!r}")
            body = self._http.get(str(entry["url"]))
            digest = hashlib.sha256(body).hexdigest()
            if digest != entry["digests"]["sha256"]:
                raise ReleaseBinariesError(
                    f"{name}: SHA-256 {digest} is not the {entry['digests']['sha256']} PyPI records"
                )
            path = out / name
            path.write_bytes(body)
            written.append(path)
        return written

    def _listing(self, project: str, version: str) -> list[Mapping[str, Any]]:
        url = self._template.format(project=project, version=version)
        waited = 0
        while True:
            try:
                data = json.loads(self._http.get(url))
                files = list(data.get("urls") or [])
                if files:
                    return files
                reason = "no files are listed yet"
            except Exception as error:  # noqa: BLE001 -- every failure is retried, then reported
                reason = str(error)
            if waited >= self._wait_s:
                raise ReleaseBinariesError(
                    f"{project} {version} is not on PyPI after {waited}s: {reason}"
                )
            print(f"{project} {version}: {reason}; waiting {self._poll_s}s", file=sys.stderr)
            self._sleep(self._poll_s)
            waited += self._poll_s


# ------------------------------------------------------------------------ collect


class AssetCollector:
    """Holds the gathered files to the plan, then writes their checksum file."""

    def __init__(self, directory: Path, checksums_asset: str) -> None:
        self._directory = directory
        self._checksums = checksums_asset

    def collect(self, expected: Sequence[str], optional: Sequence[str]) -> list[str]:
        present = sorted(
            path.name
            for path in self._directory.iterdir()
            if path.is_file() and path.name != self._checksums
        )
        missing = [name for name in expected if name not in present]
        unexpected = [name for name in present if name not in expected and name not in optional]
        problems = []
        if missing:
            problems.append(f"missing: {', '.join(missing)}")
        if unexpected:
            problems.append(f"not declared: {', '.join(unexpected)}")
        if problems:
            raise ReleaseBinariesError("; ".join(problems))
        lines = []
        for name in present:
            digest = hashlib.sha256((self._directory / name).read_bytes()).hexdigest()
            lines.append(f"{digest}  {name}")
        (self._directory / self._checksums).write_text("\n".join(lines) + "\n", encoding="utf-8")
        return present


# ------------------------------------------------------------------------ flatpak


class FlatpakManifestLocalizer:
    """The declared Flatpak manifest with one module built from a local checkout.

    The declared manifest fetches the source from git, as Flathub requires. A release
    builds the commit it is releasing, already checked out, so the module's sources are
    replaced by that directory; nothing else in the manifest changes.
    """

    def localize(self, manifest: Path, module: str, source: Path) -> dict[str, Any]:
        import yaml  # type: ignore[import-untyped]  # PyYAML: only this command needs it.

        data = yaml.safe_load(manifest.read_text(encoding="utf-8"))
        modules = data.get("modules") or []
        hits = [m for m in modules if isinstance(m, dict) and m.get("name") == module]
        if len(hits) != 1:
            raise ReleaseBinariesError(f"{manifest} has no single module named {module!r}")
        hits[0]["sources"] = [{"type": "dir", "path": str(source.resolve())}]
        result: dict[str, Any] = data
        return result


# ---------------------------------------------------------------------------- CLI


class Cli:
    """The command line: each subcommand is one of the classes above, wired to real I/O."""

    def __init__(self, config: Path = DEFAULT_CONFIG, root: Path = REPO) -> None:
        self._config = config
        self._root = root

    def run(self, argv: Sequence[str] | None = None) -> int:
        args = self._parser().parse_args(argv)
        try:
            result: int = args.func(args)
            return result
        except ReleaseBinariesError as error:
            print(f"error: {error}", file=sys.stderr)
            return 1

    def _parser(self) -> argparse.ArgumentParser:
        parser = argparse.ArgumentParser(prog=SCRIPT, description=__doc__.split("\n")[0])
        sub = parser.add_subparsers(required=True)
        sub.add_parser("context", help="print the release's tag, branch and workflow").set_defaults(
            func=self._context
        )
        plan = sub.add_parser("plan", help="print the workflow's matrix for one run")
        plan.add_argument("--mode", required=True, choices=MODES)
        plan.add_argument("--target", required=True)
        plan.add_argument("--github-output", type=Path)
        plan.set_defaults(func=self._plan)
        sub.add_parser("check", help="exit 1 when the workflow or the page drifted").set_defaults(
            func=self._check
        )
        sub.add_parser("render", help="rewrite the downloads page's table").set_defaults(
            func=self._render
        )
        flatpak = sub.add_parser("flatpak-manifest", help="the manifest, built from a checkout")
        flatpak.add_argument("--manifest", required=True, type=Path)
        flatpak.add_argument("--module", required=True)
        flatpak.add_argument("--source", required=True, type=Path)
        flatpak.add_argument("--out", required=True, type=Path)
        flatpak.set_defaults(func=self._flatpak)
        pypi = sub.add_parser("pypi-fetch", help="fetch one version's files from PyPI")
        pypi.add_argument("--project", required=True)
        pypi.add_argument("--version", required=True)
        pypi.add_argument("--out", required=True, type=Path)
        pypi.set_defaults(func=self._pypi)
        collect = sub.add_parser("collect", help="hold the files to the plan; write checksums")
        collect.add_argument("--dir", required=True, type=Path)
        collect.add_argument("--expected", required=True)
        collect.add_argument("--optional", default="[]")
        collect.set_defaults(func=self._collect)
        return parser

    def _settings(self) -> Settings:
        return Settings.load(self._config, self._root)

    def _context(self, _args: argparse.Namespace) -> int:
        context = ReleaseContext.read(self._settings())
        print(f"tag={context.tag}")
        print(f"release_branch={context.release_branch}")
        print(f"release_workflow={context.release_workflow}")
        return 0

    def _plan(self, args: argparse.Namespace) -> int:
        settings = self._settings()
        planner = MatrixPlanner(TargetCatalogue(settings), settings)
        plan = planner.plan(
            mode=args.mode, target=args.target, tag=ReleaseContext.read(settings).tag
        )
        if args.github_output:
            with args.github_output.open("a", encoding="utf-8") as handle:
                handle.write(MatrixPlanner.github_output(plan))
        print(json.dumps(plan, indent=2))
        return 0

    def _check(self, _args: argparse.Namespace) -> int:
        import yaml  # a dev dependency; CI's gates run this (typed once, above)

        settings = self._settings()
        catalogue = TargetCatalogue(settings)
        workflow = yaml.safe_load(settings.workflow.read_text(encoding="utf-8"))
        problems = WorkflowChecker(catalogue, settings, ReleaseContext.read(settings)).problems(
            workflow
        )
        page = settings.downloads_page.read_text(encoding="utf-8")
        renderer = DownloadsRenderer(catalogue, settings)
        if renderer.apply(page) != page:
            problems.append(
                f"{settings.downloads_page.relative_to(settings.root)} is out of date: "
                f"run `python {SCRIPT} render`"
            )
        for problem in problems:
            print(f"drift: {problem}", file=sys.stderr)
        return 1 if problems else 0

    def _render(self, _args: argparse.Namespace) -> int:
        settings = self._settings()
        page = settings.downloads_page
        renderer = DownloadsRenderer(TargetCatalogue(settings), settings)
        page.write_text(renderer.apply(page.read_text(encoding="utf-8")), encoding="utf-8")
        print(f"rendered {page.relative_to(settings.root)}")
        return 0

    def _flatpak(self, args: argparse.Namespace) -> int:
        data = FlatpakManifestLocalizer().localize(args.manifest, args.module, args.source)
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {args.out}")
        return 0

    def _pypi(self, args: argparse.Namespace) -> int:
        settings = self._settings()
        fetcher = PypiFetcher(
            UrllibFetcher(),
            settings.pypi_json_url,
            wait_s=settings.pypi_wait_s,
            poll_s=settings.poll_s,
        )
        for path in fetcher.fetch(args.project, args.version, args.out):
            print(f"fetched {path.name} (SHA-256 matches PyPI)")
        return 0

    def _collect(self, args: argparse.Namespace) -> int:
        settings = self._settings()
        collector = AssetCollector(args.dir, settings.checksums_asset)
        names = collector.collect(json.loads(args.expected), json.loads(args.optional))
        for name in names:
            print(f"collected {name}")
        print(f"wrote {settings.checksums_asset} over {len(names)} files")
        return 0


if __name__ == "__main__":
    sys.exit(Cli().run())
