# Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
"""The JavaScript the repository still has to commit, compiled from its TypeScript.

    python3 scripts/typescript_artifacts.py           # compile and write every artifact
    python3 scripts/typescript_artifacts.py --check   # exit 1, naming each stale file

Sub-doctrine 9.f: JavaScript is not authored, TypeScript is. A browser cannot run a `.ts`
file, and neither can Metro or Babel when they `require` a config, so a handful of `.js`
files must exist at fixed paths. Each is *generated*: compiled by the repository's own `tsc`
from a TypeScript source, behind a banner that says so, from the artifacts declared in
`scripts/typescript_artifacts.toml`. `tests/meta/test_typescript_artifacts.py` fails when a
committed file differs from what its source compiles to, and when any other `.js` is tracked
(sub-doctrine 12.e: the check that says out loud when the step was missed).

The compiler is the one `npm ci` installs at the repository root: TypeScript is what the
family already uses for `@vibey/core` and the krypton clients (10.e), so there is no second
toolchain here. The same strict flags those packages use are applied to every artifact.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
import tomllib
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

try:
    from scripts.interfaces.typescript_artifacts_interface import (
        ArtifactInterface,
        TypeScriptCompilerInterface,
    )
except ModuleNotFoundError:  # Direct execution keeps the script directory on sys.path.
    from interfaces.typescript_artifacts_interface import (  # type: ignore[import-not-found,no-redef]
        ArtifactInterface,
        TypeScriptCompilerInterface,
    )

REPO = Path(__file__).resolve().parents[1]
CONFIG = Path("scripts/typescript_artifacts.toml")


class TypeScriptMissing(RuntimeError):
    """The compiler is not installed; the message says how to install it."""


@dataclass(frozen=True, slots=True)
class Artifact:
    """One TypeScript source and the places its JavaScript is committed."""

    source: str
    module: str
    targets: tuple[str, ...]


class Banner:
    """The "generated, do not edit" line every artifact starts with."""

    TEXT = (
        "// GENERATED by scripts/typescript_artifacts.py from {source}. Do not edit: change the "
        "TypeScript and run `python3 scripts/typescript_artifacts.py`. "
        "tests/meta/test_typescript_artifacts.py fails on drift.\n"
    )

    @classmethod
    def line(cls, source: str) -> str:
        return cls.TEXT.format(source=source)

    @classmethod
    def marks(cls, text: str) -> str | None:
        """The source a file's first line says it was generated from, or None."""
        head, _, tail = cls.TEXT.partition("{source}")
        first = text.split("\n", 1)[0] + "\n"
        if first.startswith(head) and first.endswith(tail):
            return first[len(head) : len(first) - len(tail)]
        return None


class TypeScriptCompiler:
    """Runs the repository's `tsc` on one source, under the flags the family already uses."""

    STRICT = (
        "--target",
        "ES2022",
        "--strict",
        "--noUncheckedIndexedAccess",
        "--noImplicitOverride",
        "--noImplicitReturns",
        "--noFallthroughCasesInSwitch",
        "--noUnusedLocals",
        "--noUnusedParameters",
        "--exactOptionalPropertyTypes",
        "--forceConsistentCasingInFileNames",
        "--skipLibCheck",
    )
    MODULES = {
        # A classic script: no imports, so TypeScript leaves it a script.
        "script": ("--lib", "ES2022,DOM", "--types", ""),
        # A Node config the tool `require`s: `export =` compiles to `module.exports =`.
        "commonjs": ("--lib", "ES2022", "--module", "commonjs", "--types", "node"),
    }

    def __init__(self, repo: Path, tsc: Path) -> None:
        self._repo = repo
        self._tsc = tsc

    def compile(self, artifact: ArtifactInterface) -> str:
        if not self._tsc.exists():
            raise TypeScriptMissing(
                f"{self._tsc} is missing: run `npm ci` at the repository root to install TypeScript"
            )
        if artifact.module not in self.MODULES:
            raise ValueError(f"{artifact.source}: module must be one of {sorted(self.MODULES)}")
        source = self._repo / artifact.source
        with tempfile.TemporaryDirectory(prefix="vibey-ts-") as out:
            command = [
                str(self._tsc),
                *self.STRICT,
                *self.MODULES[artifact.module],
                "--rootDir",
                str(source.parent),
                "--outDir",
                out,
                str(source),
            ]
            done = subprocess.run(  # noqa: S603 -- the repository's own tsc, a fixed argument list
                command, cwd=self._repo, check=False, capture_output=True, text=True
            )
            if done.returncode != 0:
                raise ValueError(f"{artifact.source} does not compile:\n{done.stdout}{done.stderr}")
            return (Path(out) / f"{source.stem}.js").read_text(encoding="utf-8")


class TypeScriptArtifacts:
    """Every committed JavaScript file, as its TypeScript source compiles it today."""

    def __init__(
        self,
        repo: Path = REPO,
        config: Path = CONFIG,
        compiler: TypeScriptCompilerInterface | None = None,
    ) -> None:
        self._repo = repo
        declared = tomllib.loads((repo / config).read_text(encoding="utf-8"))
        self._artifacts = tuple(
            Artifact(a["source"], a["module"], tuple(a["targets"])) for a in declared["artifact"]
        )
        self._compiler = compiler or TypeScriptCompiler(
            repo, repo / declared["typescript"]["compiler"]
        )

    @property
    def artifacts(self) -> tuple[Artifact, ...]:
        return self._artifacts

    def outputs_declared(self) -> list[Path]:
        """Every path an artifact writes, without compiling anything."""
        return [Path(target) for artifact in self._artifacts for target in artifact.targets]

    def outputs(self) -> dict[Path, bytes]:
        out: dict[Path, bytes] = {}
        for artifact in self._artifacts:
            text = Banner.line(artifact.source) + self._compiler.compile(artifact)
            for target in artifact.targets:
                if Path(target) in out:
                    raise ValueError(f"{target} is the target of two artifacts")
                out[Path(target)] = text.encode()
        return out

    def stale(self) -> list[Path]:
        wrong = []
        for path, data in self.outputs().items():
            target = self._repo / path
            if not target.exists() or target.read_bytes() != data:
                wrong.append(path)
        return wrong

    def write(self) -> list[Path]:
        written = []
        for path, data in self.outputs().items():
            target = self._repo / path
            if not target.exists() or target.read_bytes() != data:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(data)
                written.append(path)
        return written


# A bare function because it is this script's `__main__` entry point (ADR-0016).
def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1, naming each stale file")
    args = parser.parse_args(argv)
    artifacts = TypeScriptArtifacts()
    try:
        if args.check:
            stale = artifacts.stale()
            for path in stale:
                print(f"stale: {path}", file=sys.stderr)
            if stale:
                print("run `python3 scripts/typescript_artifacts.py`", file=sys.stderr)
            return 1 if stale else 0
        written = artifacts.write()
    except (TypeScriptMissing, ValueError) as error:
        print(error, file=sys.stderr)
        return 2
    print(f"wrote {len(written)} file(s)" if written else "up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
