# Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
"""The declared seams of `vibey_gh` (vibey ADR-0016).

Interfaces declare; they never consume. A module here may import the standard library,
`vibey_gh.config` (data, not behaviour) and other interfaces — nothing else from this
tree. `.importlinter` enforces it.
"""

from __future__ import annotations

from vibey_gh.interfaces.book_interface import (
    BookChapterInterface,
    BookErrorInterface,
    EpubPackageInterface,
    MainExtractorInterface,
    NavReaderInterface,
    PrintInteriorInterface,
    TableOfContentsInterface,
)
from vibey_gh.interfaces.chapter_sanitizer_interface import ChapterSanitizerInterface
from vibey_gh.interfaces.class_contracts import (
    AutomationStateInterface,
    ChangeRequestInterface,
    CheckResultInterface,
    CoordinateInterface,
    DarwinMemorySamplerInterface,
    DocumentationConfigInterface,
    EstimateConfigInterface,
    FeasibilityEvaluatorClassInterface,
    FitLoopInterface,
    FlattenErrorInterface,
    FlattenPlanInterface,
    ForgeClassInterface,
    ForgeCommentInterface,
    ForgeIssueInterface,
    ForgejoForgeInterface,
    ForgeKindInterface,
    ForgeLabelInterface,
    ForgeReleaseInterface,
    ForgeRepositoryInterface,
    ForgeReviewInterface,
    ForgeTransportInterface,
    ForgeUserInterface,
    GapInterface,
    GhConfigInterface,
    GitHubForgeInterface,
    GitLabForgeInterface,
    GitLabTransportInterface,
    GradedEstimatorClassInterface,
    GradeInterface,
    JsonlSnapshotStoreInterface,
    LinearFitInterface,
    LinuxMemorySamplerInterface,
    MachineInterface,
    MarketplaceConfigInterface,
    MarketplaceErrorInterface,
    MergeQueueConfigInterface,
    ModelInterface,
    ObservationInterface,
    OllamaModelSamplerInterface,
    OperationEstimateInterface,
    PipelineVerdictInterface,
    PlatformConfigInterface,
    PrAutomationConfigInterface,
    PrAutomationFallbackConfigInterface,
    PredictionInterface,
    ProtectedPathsGuardInterface,
    ProtectedRefInterface,
    RangeCommitInterface,
    RequirementInterface,
    ReviewComposerClassInterface,
    ReviewContractClassInterface,
    ReviewThreadInterface,
    RulesetConfigInterface,
    RulesetsConfigInterface,
    SampleInterface,
    SnapshotStoreErrorInterface,
    StageInterface,
    StageVerdictInterface,
    StateVectorInterface,
    TidyConfigInterface,
    TrackRecordInterface,
    VerdictInterface,
    _ChainInterface,
)
from vibey_gh.interfaces.docx_interface import (
    DocxErrorInterface,
    DocxWriterInterface,
    HtmlToDocxInterface,
)
from vibey_gh.interfaces.fallback_pin_resolver_interface import FallbackPinInterface
from vibey_gh.interfaces.forge_snapshot_interface import (
    AppendOutcomeInterface,
    ChainHeadInterface,
    ForgeReadInterface,
)
from vibey_gh.interfaces.paper_interface import PaperDocumentInterface, PaperErrorInterface
from vibey_gh.interfaces.review_composition_interface import (
    ReviewComposerInterface,
    ReviewComposerPort,
)
from vibey_gh.interfaces.review_contract_interface import (
    ReviewContractInterface,
    ReviewContractPort,
)

__all__ = [
    "AppendOutcomeInterface",
    "AutomationStateInterface",
    "BookChapterInterface",
    "BookErrorInterface",
    "ChainHeadInterface",
    "ChangeRequestInterface",
    "ChapterSanitizerInterface",
    "CheckResultInterface",
    "CoordinateInterface",
    "DarwinMemorySamplerInterface",
    "DocumentationConfigInterface",
    "DocxErrorInterface",
    "DocxWriterInterface",
    "EpubPackageInterface",
    "EstimateConfigInterface",
    "FallbackPinInterface",
    "FeasibilityEvaluatorClassInterface",
    "FitLoopInterface",
    "FlattenErrorInterface",
    "FlattenPlanInterface",
    "ForgeClassInterface",
    "ForgeCommentInterface",
    "ForgeIssueInterface",
    "ForgeKindInterface",
    "ForgeLabelInterface",
    "ForgeReadInterface",
    "ForgeReleaseInterface",
    "ForgeRepositoryInterface",
    "ForgeReviewInterface",
    "ForgeTransportInterface",
    "ForgeUserInterface",
    "ForgejoForgeInterface",
    "GapInterface",
    "GhConfigInterface",
    "GitHubForgeInterface",
    "GitLabForgeInterface",
    "GitLabTransportInterface",
    "GradeInterface",
    "GradedEstimatorClassInterface",
    "HtmlToDocxInterface",
    "JsonlSnapshotStoreInterface",
    "LinearFitInterface",
    "LinuxMemorySamplerInterface",
    "MachineInterface",
    "MainExtractorInterface",
    "MarketplaceConfigInterface",
    "MarketplaceErrorInterface",
    "MergeQueueConfigInterface",
    "ModelInterface",
    "NavReaderInterface",
    "ObservationInterface",
    "OllamaModelSamplerInterface",
    "OperationEstimateInterface",
    "PaperDocumentInterface",
    "PaperErrorInterface",
    "PipelineVerdictInterface",
    "PlatformConfigInterface",
    "PrAutomationConfigInterface",
    "PrAutomationFallbackConfigInterface",
    "PredictionInterface",
    "PrintInteriorInterface",
    "ProtectedPathsGuardInterface",
    "ProtectedRefInterface",
    "RangeCommitInterface",
    "RequirementInterface",
    "ReviewComposerClassInterface",
    "ReviewComposerInterface",
    "ReviewComposerPort",
    "ReviewContractClassInterface",
    "ReviewContractInterface",
    "ReviewContractPort",
    "ReviewThreadInterface",
    "RulesetConfigInterface",
    "RulesetsConfigInterface",
    "SampleInterface",
    "SnapshotStoreErrorInterface",
    "StageInterface",
    "StageVerdictInterface",
    "StateVectorInterface",
    "TableOfContentsInterface",
    "TidyConfigInterface",
    "TrackRecordInterface",
    "VerdictInterface",
    "_ChainInterface",
]
