// GENERATED by scripts/typescript_artifacts.py from src/vibey_tools/gh/web/analytics.ts. Do not edit: change the TypeScript and run `python3 scripts/typescript_artifacts.py`. tests/meta/test_typescript_artifacts.py fails on drift.
"use strict";
// Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
// Google Analytics, started the way Google documents it, with the cookie-consent default
// (documentation.cookie_consent). TypeScript is the only authored form (sub-doctrine 9.f);
// scripts/typescript_artifacts.py compiles this file to `analytics.js`, which the
// release-surfaces workflow inlines into every published page with its two settings as the
// `data-ga-id` and `data-consent` attributes of the script element, so the workflow carries
// configuration and no JavaScript.
//
// Because the file is inlined into HTML, nothing in it, comments included, may spell out the
// markup that closes or opens a script element: the HTML parser ends an inline script at the
// first such closing tag wherever it appears, and prints the rest of the file as page text.
// tests/meta/test_typescript_artifacts.py fails on any inlined asset that does.
//
// With consent on, analytics storage stays denied until the reader accepts (Google Consent
// Mode v2); consent.ts records the choice. The `gtag` function pushes its `arguments` object,
// not an array, because that is what gtag.js reads.
(() => {
    const script = document.currentScript;
    const id = script?.dataset.gaId ?? "";
    if (!id) {
        return;
    }
    const consent = script?.dataset.consent === "true";
    const page = window;
    const dataLayer = (page.dataLayer = page.dataLayer || []);
    function gtag(..._args) {
        // eslint-disable-next-line prefer-rest-params -- gtag.js reads an `arguments` object
        dataLayer.push(arguments);
    }
    page.gtag = gtag;
    if (consent) {
        gtag("consent", "default", {
            ad_storage: "denied",
            ad_user_data: "denied",
            ad_personalization: "denied",
            analytics_storage: "denied",
        });
    }
    gtag("js", new Date());
    gtag("config", id);
})();
