# Made with ❤️ by [Vibey](https://the-vibey-project.github.io/vibey/), Developed by [Adam Matthew Steinberger](https://vibewithadam.matthewsteinberger.com/) ([@adammatthewsteinberger](https://github.com/adammatthewsteinberger/)).
"""`scripts/continuation_prompts.py` against a small repository built in a temporary directory.

Each guarantee `check` holds is shown passing on a sound repository and failing on one broken
the way it guards against. Commands are answered by a fake runner, so nothing reaches the
network or the real `vibey-gh`.

Module-level test functions rather than a class with an interface beside it (ADR-0016):
pytest collects `test_*` functions, and the rule is about production code.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from scripts import continuation_prompts as cp

LANE = """name: Continuation prompts
# a comment that names a self-hosted runner is not where a job runs
on:
  schedule:
    - cron: "41 3 * * 1"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-24.04-arm
"""

TOML = """
[pages]
directory = "docs/continuation"
index = "docs/continuation/index.md"

[[prompt]]
id = "resume"
title = "Resume"
page = "docs/continuation/resume.md"
mode = "act"
purpose = "Continue."
gather = ["echo evidence"]
covers = ["ci.yml", "continuation-prompts.yml", "vibey-testing"]

[[prompt]]
id = "rebuild"
title = "Rebuild"
page = "docs/continuation/rebuild.md"
mode = "drill"
purpose = "Rebuild."
covers = []

[authority]
drill_only = ["rebuild"]

[lane]
workflow = ".github/workflows/continuation-prompts.yml"

[run]
runs_on = "ubuntu-24.04-arm"
model = "gpt-oss:20b"
max_turns = 7
timeout_minutes = 99
evidence_chars = 40
gather_timeout_s = 5

[exempt]
"""

STATE = (
    "<!-- BEGIN GENERATED continuation:state — regenerated by scripts/continuation_prompts.py -->\n"
    "<!-- END GENERATED continuation:state -->\n"
)
INDEX = (
    "# Continuation prompts\n\n"
    "<!-- BEGIN GENERATED continuation:index — regenerated by scripts/continuation_prompts.py -->\n"
    "<!-- END GENERATED continuation:index -->\n"
)


def page(body: str) -> str:
    return f"# A prompt\n\n{STATE}\n## The prompt\n\n```text\n{body}\n```\n"


class FakeRunner:
    """Answers `vibey-gh <sub> --help` for a fixed set of commands; echoes anything else."""

    def __init__(self, commands: set[str] | None = None, output: str = "evidence") -> None:
        self.commands = commands if commands is not None else {"version"}
        self.output = output
        self.calls: list[str] = []

    def run(self, command: str, timeout_s: float) -> tuple[int, str]:
        self.calls.append(command)
        if "-m vibey_gh" in command:
            sub = command.split("-m vibey_gh ", 1)[1].split()[0]
            return (0, "") if sub in self.commands else (2, "unknown")
        return 0, self.output


def world(tmp_path: Path) -> Path:
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "vibey-engine"\nversion = "9.9.9"\n'
    )
    decisions = tmp_path / "docs" / "architecture" / "decisions"
    decisions.mkdir(parents=True)
    (decisions / "0001-first.md").write_text("# 0001 — First\n")
    (decisions / "0002-second.md").write_text("# 0002 — Second\n")
    workflows = tmp_path / ".github" / "workflows"
    workflows.mkdir(parents=True)
    (workflows / "ci.yml").write_text(
        "name: CI\non: push\njobs:\n  a:\n    runs-on: ubuntu-latest\n"
    )
    (workflows / "continuation-prompts.yml").write_text(LANE)
    skill = tmp_path / ".claude" / "skills" / "vibey-testing"
    skill.mkdir(parents=True)
    (skill / "SKILL.md").write_text("---\nname: vibey-testing\n---\n")
    (tmp_path / "scripts").mkdir()
    (tmp_path / "scripts" / "continuation_prompts.toml").write_text(TOML)
    (tmp_path / "scripts" / "continuation_prompts.py").write_text(
        "# the generated blocks name it\n"
    )
    (tmp_path / "CLAUDE.md").write_text("# rules\n")
    pages = tmp_path / "docs" / "continuation"
    pages.mkdir(parents=True)
    (pages / "index.md").write_text(INDEX)
    (pages / "resume.md").write_text(
        page("Read CLAUDE.md, then ADR-0002, then run `vibey-gh version`.")
    )
    (pages / "rebuild.md").write_text(page("Clone it; read .github/workflows/ci.yml."))
    return tmp_path


def prompts(root: Path, runner: FakeRunner | None = None) -> cp.ContinuationPrompts:
    runner = runner or FakeRunner()
    return cp.ContinuationPrompts(
        root,
        cp.Settings.load(root),
        cp.RepositoryFacts(root),
        cp.ReferenceProbe(root, runner),
        runner,
    )


def sound(tmp_path: Path) -> Path:
    root = world(tmp_path)
    prompts(root).render()
    return root


def test_a_rendered_sound_repository_holds_every_guarantee(tmp_path: Path) -> None:
    root = sound(tmp_path)
    assert prompts(root).problems() == []
    resume = (root / "docs/continuation/resume.md").read_text()
    assert "vibey-engine 9.9.9" in resume and "0002 — Second" in resume
    assert "[CI](https://github.com/the-vibey-project/vibey/actions/workflows/ci.yml)" in resume
    index = (root / "docs/continuation/index.md").read_text()
    assert "| [Rebuild](rebuild.md) | drill | Rebuild. |" in index


def test_render_is_idempotent(tmp_path: Path) -> None:
    root = sound(tmp_path)
    assert prompts(root).render() == []


def test_a_stale_block_fails(tmp_path: Path) -> None:
    root = sound(tmp_path)
    (root / "pyproject.toml").write_text('[project]\nname = "vibey-engine"\nversion = "10.0.0"\n')
    found = prompts(root).problems()
    assert any("resume: generated block 'state' is stale" in p for p in found)
    assert any("index.md: generated block 'index' is stale" in p for p in found)


def test_a_named_file_that_does_not_exist_fails(tmp_path: Path) -> None:
    root = sound(tmp_path)
    path = root / "docs/continuation/rebuild.md"
    path.write_text(path.read_text().replace(".github/workflows/ci.yml", "scripts/gone.py"))
    assert "rebuild: names scripts/gone.py, which does not exist" in prompts(root).problems()


def test_a_glob_resolves_when_anything_matches(tmp_path: Path) -> None:
    root = sound(tmp_path)
    path = root / "docs/continuation/rebuild.md"
    path.write_text(path.read_text().replace(".github/workflows/ci.yml", ".github/workflows/*.yml"))
    assert prompts(root).problems() == []
    path.write_text(path.read_text().replace(".github/workflows/*.yml", "research/*/LOG.md"))
    assert "rebuild: names research/*/LOG.md, which does not exist" in prompts(root).problems()


def test_an_unknown_adr_and_an_unknown_command_fail(tmp_path: Path) -> None:
    root = sound(tmp_path)
    path = root / "docs/continuation/resume.md"
    path.write_text(
        path.read_text()
        .replace("ADR-0002", "ADR-0099")
        .replace("vibey-gh version", "vibey-gh reconcile")
    )
    found = prompts(root).problems()
    assert "resume: names ADR-0099, which does not exist" in found
    assert "resume: names `vibey-gh reconcile`, which is not a vibey-gh command" in found


def test_each_vibey_gh_command_is_probed_once(tmp_path: Path) -> None:
    root = sound(tmp_path)
    runner = FakeRunner()
    prompts(root, runner).problems()
    assert sum("vibey_gh version" in c for c in runner.calls) == 1


def test_an_uncovered_lane_or_skill_fails_until_covered_or_exempted(tmp_path: Path) -> None:
    root = sound(tmp_path)
    (root / ".github/workflows/new.yml").write_text("name: New\non: push\njobs: {}\n")
    found = prompts(root).problems()
    assert "new.yml is covered by no continuation prompt and has no exemption" in found
    toml = root / "scripts/continuation_prompts.toml"
    toml.write_text(toml.read_text() + '"new.yml" = ""\n')
    assert "exemption for new.yml gives no reason" in prompts(root).problems()
    toml.write_text(toml.read_text().replace('"new.yml" = ""', '"new.yml" = "a probe"'))
    prompts(root).render()
    assert prompts(root).problems() == []


def test_covering_something_that_is_not_there_fails(tmp_path: Path) -> None:
    root = world(tmp_path)
    toml = root / "scripts/continuation_prompts.toml"
    toml.write_text(toml.read_text().replace('"vibey-testing"]', '"vibey-testing", "ghost.yml"]'))
    prompts(root).render()
    assert (
        "resume: covers 'ghost.yml', which is neither a workflow nor a skill"
        in prompts(root).problems()
    )


def test_a_drill_only_prompt_declared_to_act_fails(tmp_path: Path) -> None:
    root = world(tmp_path)
    toml = root / "scripts/continuation_prompts.toml"
    text = toml.read_text().replace('mode = "drill"', 'mode = "act"')
    toml.write_text(text)
    prompts(root).render()
    assert "rebuild: declared drill-only, but its mode is 'act'" in prompts(root).problems()
    toml.write_text(
        text.replace('mode = "act"\npurpose = "Rebuild."', 'mode = "both"\npurpose = "Rebuild."')
    )
    prompts(root).render()
    assert any("rebuild: mode 'both' is not one of" in p for p in prompts(root).problems())


def test_a_missing_page_or_prompt_block_fails(tmp_path: Path) -> None:
    root = sound(tmp_path)
    (root / "docs/continuation/rebuild.md").write_text("# Rebuild\n\nno prompt here\n")
    assert any("has no ```text block" in p for p in prompts(root).problems())
    (root / "docs/continuation/rebuild.md").unlink()
    assert (
        "rebuild: its page docs/continuation/rebuild.md does not exist" in prompts(root).problems()
    )


def test_two_prompts_sharing_an_id_fail(tmp_path: Path) -> None:
    root = sound(tmp_path)
    toml = root / "scripts/continuation_prompts.toml"
    toml.write_text(toml.read_text().replace('id = "rebuild"', 'id = "resume"'))
    assert "two prompts share an id" in prompts(root).problems()


def test_the_lane_must_exist_be_scheduled_dispatchable_and_hosted_by_github(tmp_path: Path) -> None:
    root = sound(tmp_path)
    lane = root / ".github/workflows/continuation-prompts.yml"
    assert prompts(root).problems() == []  # the comment naming a self-hosted runner is no job
    lane.write_text(LANE.replace("runs-on: ubuntu-24.04-arm", "runs-on: [self-hosted, linux]"))
    assert any("must run on GitHub-hosted runners" in p for p in prompts(root).problems())
    lane.write_text(
        LANE.replace('    - cron: "41 3 * * 1"\n', "").replace("  workflow_dispatch:\n", "")
    )
    found = prompts(root).problems()
    assert any("has no schedule" in p for p in found)
    assert any("no workflow_dispatch" in p for p in found)
    lane.unlink()
    assert any(
        "does not exist" in p and "continuation-prompts.yml" in p for p in prompts(root).problems()
    )


def test_a_self_hosted_run_setting_fails(tmp_path: Path) -> None:
    root = sound(tmp_path)
    toml = root / "scripts/continuation_prompts.toml"
    toml.write_text(
        toml.read_text().replace('runs_on = "ubuntu-24.04-arm"', 'runs_on = "self-hosted"')
    )
    assert any("must run on GitHub-hosted runners" in p for p in prompts(root).problems())


def test_the_matrix_carries_the_declared_run_settings(tmp_path: Path) -> None:
    root = sound(tmp_path)
    matrix = prompts(root).matrix()
    assert [m["id"] for m in matrix] == ["resume", "rebuild"]
    assert matrix[0] == {
        "id": "resume",
        "mode": "act",
        "title": "Resume",
        "runs_on": "ubuntu-24.04-arm",
        "model": "gpt-oss:20b",
        "models": "gpt-oss:20b",
        "max_turns": 7,
        "timeout_minutes": 99,
    }


def test_extract_returns_the_prompt_text_alone(tmp_path: Path) -> None:
    root = sound(tmp_path)
    assert prompts(root).extract("rebuild") == "Clone it; read .github/workflows/ci.yml."
    with pytest.raises(KeyError):
        prompts(root).extract("nobody")
    (root / "docs/continuation/rebuild.md").write_text("# no block\n")
    with pytest.raises(ValueError):
        prompts(root).extract("rebuild")


def test_the_plan_bounds_its_evidence_and_says_where_it_cut(tmp_path: Path) -> None:
    root = sound(tmp_path)
    runner = FakeRunner(output="x" * 100)
    plan = prompts(root, runner).plan("resume")
    assert plan.startswith("Read CLAUDE.md")
    assert "ONE draft pull request" in plan
    assert "$ echo evidence   (exit 0)" in plan
    assert "[... cut at 40 characters of 100 ...]" in plan
    drill = prompts(root, runner).plan("rebuild")
    assert "DRILL: change nothing" in drill and "'Does not hold:'" in drill


def test_the_subprocess_runner_reports_exit_codes_and_timeouts(tmp_path: Path) -> None:
    runner = cp.SubprocessRunner(tmp_path)
    assert runner.run("echo hi; exit 3", timeout_s=10) == (3, "hi\n")
    code, _ = runner.run("sleep 5", timeout_s=0.2)
    assert code == 124


def test_the_cli_renders_checks_and_hands_over(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    root = world(tmp_path)
    cli = cp.ContinuationCli(root)
    assert cli.run([]) == 2
    assert cli.run(["render"]) == 0
    assert "rendered docs/continuation/resume.md" in capsys.readouterr().out
    assert cli.run(["matrix"]) == 0
    assert json.loads(capsys.readouterr().out)[1]["mode"] == "drill"
    assert cli.run(["extract"]) == 2
    assert cli.run(["extract", "rebuild"]) == 0
    assert "Clone it" in capsys.readouterr().out
    assert cli.run(["plan", "rebuild"]) == 0
    assert "DRILL" in capsys.readouterr().out


# ------------------------------------------------------------------ the chat (#1384)

CHAT_LANE = """name: Chat
on:
  issue_comment:
  pull_request_review_comment:
  workflow_dispatch:
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - run: echo author_association
  reply:
    runs-on: ubuntu-latest
    steps:
      - run: python3 scripts/continuation_prompts.py guard p && python3 scripts/continuation_prompts.py defuse r
"""

CHAT_TOML = """
[[prompt]]
id = "chat"
title = "Chat"
page = "docs/continuation/chat.md"
mode = "chat"
purpose = "Answer."
covers = ["chat.yml"]
"""

CHAT_SECTION = """
[chat]
workflow = ".github/workflows/chat.yml"
trigger = "/vibey"
trusted = ["OWNER"]
reply_file = ".reply.md"
thread_chars = 30
request_chars = 20
"""


def chat_world(tmp_path: Path) -> Path:
    root = world(tmp_path)
    toml = root / "scripts/continuation_prompts.toml"
    text = toml.read_text().replace("[authority]", CHAT_TOML + "\n[authority]")
    text = text.replace(
        'drill_only = ["rebuild"]',
        'drill_only = ["rebuild"]\nprotected = ["^\\\\.github/", "^secret\\\\.toml$"]',
    )
    text = text.replace('model = "gpt-oss:20b"', 'model = "gpt-oss:20b"\nmodels = ["big", "small"]')
    toml.write_text(text + CHAT_SECTION)
    (root / ".github/workflows/chat.yml").write_text(CHAT_LANE)
    (root / "docs/continuation/chat.md").write_text(page("Read CLAUDE.md, then answer."))
    prompts(root).render()
    return root


def test_a_sound_chat_lane_holds_and_the_weekly_matrix_leaves_it_out(tmp_path: Path) -> None:
    root = chat_world(tmp_path)
    assert prompts(root).problems() == []
    matrix = prompts(root).matrix()
    assert [m["id"] for m in matrix] == ["resume", "rebuild"]
    assert matrix[0]["model"] == "big" and matrix[0]["models"] == "big small"


def test_the_chat_lane_must_keep_every_guard(tmp_path: Path) -> None:
    root = chat_world(tmp_path)
    lane = root / ".github/workflows/chat.yml"
    lane.write_text(CHAT_LANE.replace("author_association", "anyone").replace("guard p && ", ""))
    found = prompts(root).problems()
    assert "chat.yml: it no longer refuses strangers (12.j)" in found
    assert "chat.yml: it applies a patch without the shared guard" in found
    lane.write_text(CHAT_LANE + "      - run: git fetch origin refs/pull/1/head\n")
    assert any("names refs/pull/" in p for p in prompts(root).problems())
    lane.write_text(CHAT_LANE.replace("runs-on: ubuntu-latest", "runs-on: self-hosted", 1))
    assert (
        "chat.yml must run on GitHub-hosted runners, not a self-hosted one"
        in prompts(root).problems()
    )
    lane.unlink()
    assert "the chat lane (chat.yml) does not exist" in prompts(root).problems()


def test_the_model_chain_falls_back_to_the_single_model(tmp_path: Path) -> None:
    assert cp.Settings.load(chat_world(tmp_path)).models() == ["big", "small"]
    plain = tmp_path / "plain"
    plain.mkdir()
    assert cp.Settings.load(world(plain)).models() == ["gpt-oss:20b"]


def test_the_guard_refuses_any_protected_path_and_passes_the_rest() -> None:
    guard = cp.PatchGuard(["^\\.github/", "^secret\\.toml$"])
    patch = (
        "diff --git a/docs/x.md b/docs/x.md\n+ok\n"
        "diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml\n+bad\n"
        "diff --git a/old.toml b/secret.toml\nrename\n"
    )
    assert guard.refused(patch) == [".github/workflows/ci.yml", "secret.toml"]
    assert guard.refused("diff --git a/docs/x.md b/docs/x.md\n") == []


def test_a_reply_cannot_mention_anyone_or_trigger_the_chat_and_is_cut_loudly() -> None:
    defuser = cp.ReplyDefuser("/vibey", cap=500)
    out = defuser.defuse(
        "Thanks @vibey and @someone-else; mail a@b.com; `@code`\n  /vibey act again"
    )
    assert "@​vibey" in out and "@​someone-else" in out
    assert "a@b.com" in out and "`@code`" in out
    assert "/​vibey act again" in out
    long = cp.ReplyDefuser("/vibey", cap=60).defuse("x" * 100)
    assert long.endswith("[... cut at 60 characters of 100 ...]")
    assert cp.ReplyDefuser("").defuse("/vibey stays") == "/vibey stays"


def test_a_chat_plan_fences_the_thread_and_states_its_authority(tmp_path: Path) -> None:
    root = chat_world(tmp_path)
    answer = prompts(root).chat("answer", "what is ADR-0001?", "a thread " * 10)
    assert answer.startswith("Read CLAUDE.md, then answer.")
    assert "ANSWER: change no file" in answer and ".reply.md" in answer
    assert "````text\nwhat is ADR-0001?\n````" in answer
    assert "[... cut at 30 characters of 90 ...]" in answer
    act = prompts(root).chat("act", "change it", "")
    assert "ONE draft pull request" in act


def test_a_chat_plan_needs_a_chat_prompt(tmp_path: Path) -> None:
    with pytest.raises(KeyError):
        prompts(sound(tmp_path)).chat("answer", "hi", "")


def test_the_cli_serves_the_chat(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    root = chat_world(tmp_path)
    cli = cp.ContinuationCli(root)
    assert cli.run(["models"]) == 0 and capsys.readouterr().out.strip() == "big small"
    request, thread = root / "req.txt", root / "thread.txt"
    request.write_text("hello")
    thread.write_text("")
    assert cli.run(["chat", "answer", str(request), str(thread)]) == 0
    assert "hello" in capsys.readouterr().out
    assert cli.run(["chat", "shout", str(request), str(thread)]) == 2
    patch = root / "change.patch"
    patch.write_text("diff --git a/docs/a.md b/docs/a.md\n")
    assert cli.run(["guard", str(patch)]) == 0
    patch.write_text("diff --git a/.github/x.yml b/.github/x.yml\n")
    assert cli.run(["guard", str(patch)]) == 1
    assert "may not change .github/x.yml" in capsys.readouterr().out
    assert cli.run(["guard"]) == 2
    reply = root / "reply.md"
    reply.write_text("ping @vibey")
    assert cli.run(["defuse", str(reply)]) == 0
    assert "@​vibey" in capsys.readouterr().out
    assert cli.run(["defuse"]) == 2


def test_the_guard_refuses_a_new_file_outside_the_declared_roots() -> None:
    guard = cp.PatchGuard([], ["^(src|docs)/"])
    scratch = "diff --git a/pr_list.txt b/pr_list.txt\nnew file mode 100644\n+x\n"
    kept = "diff --git a/docs/a.md b/docs/a.md\nnew file mode 100644\n+x\n"
    edit = "diff --git a/pr_list.txt b/pr_list.txt\nindex 1..2 100644\n+x\n"
    assert guard.refused(scratch) == ["pr_list.txt"]
    assert guard.refused(kept) == []
    assert guard.refused(edit) == []
    assert cp.PatchGuard([], []).refused(scratch) == []


def test_a_run_is_believed_only_with_an_exit_of_zero_and_a_log(tmp_path: Path) -> None:
    receipt = cp.RunReceipt()
    assert len(receipt.problems(tmp_path)) == 2
    (tmp_path / "code").write_text("0\n")
    (tmp_path / "agent.log").write_text("  \n")
    assert receipt.problems(tmp_path) == [
        "the agent left no log: a run with no evidence is not believed"
    ]
    (tmp_path / "agent.log").write_text("did the thing")
    assert receipt.problems(tmp_path) == []
    (tmp_path / "code").write_text("1")
    assert receipt.problems(tmp_path) == ["the agent did not exit 0"]


def test_the_transcript_reads_the_run_store_the_runner_writes(tmp_path: Path) -> None:
    run = tmp_path / ".qwenloop" / "runs" / "r1"
    run.mkdir(parents=True)
    (run / "events.jsonl").write_text(
        '{"type": "text_delta", "text": "All holds."}\n'
        "not json\n"
        '{"type": "tool.call", "name": "shell", "arguments": {"cmd": "ls"}}\n'
        '{"type": "tool_result", "name": "shell", "result": "x"}\n'
        '{"type": "completed", "turn": 3}\n'
    )
    text = cp.RunReceipt().transcript(tmp_path)
    assert "All holds." in text and "[tool] shell" in text and "[completed]" in text
    assert cp.RunReceipt().transcript(tmp_path / "nowhere") == ""


def test_the_cli_exports_the_transcript_and_checks_the_receipt(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    cli = cp.ContinuationCli(chat_world(tmp_path))
    assert cli.run(["transcript"]) == 2 and cli.run(["receipt"]) == 2
    assert cli.run(["transcript", str(tmp_path)]) == 0
    out = tmp_path / "out"
    out.mkdir()
    assert cli.run(["receipt", str(out)]) == 1
    assert "the agent did not exit 0" in capsys.readouterr().out
    (out / "code").write_text("0")
    (out / "agent.log").write_text("report")
    assert cli.run(["receipt", str(out)]) == 0
